// src/modules/vue-components/countdown/Countdown.vue
<template>
    <span class="countdown">{{ text }}</span>
</template>

<script setup lang="ts">
import { useInterval } from "../../interfaces/generic/hooks/useInterval.vue";
import { onMounted, ref, computed } from 'vue';
import { defaultTimeUnits, reduceTimeUnits, TimeUnit } from 'src/modules/interfaces/component/countdown/types';

const props = defineProps<{
    units?: TimeUnit[];
    date?: Date;
}>();
const text = ref<string>("");

const defaultedProps = computed(() => ({
    units: props.units ?? reduceTimeUnits(defaultTimeUnits),
    date: props.date ?? new Date('May 6, 2085 11:00:00')
}));
const renderTexts = (units: TimeUnit[]) => {
    let timeString = "", distance = defaultedProps.value.date.getTime() - new Date().getTime();
    for (const { timeFactor, name } of units) {
        const value = Math.floor(distance / timeFactor);
        timeString += value <= 0 ? '' : `${value} ${String(value).slice(-1) === '1' ? name : name + 's'} `;
        distance %= timeFactor;
    }
    
    text.value = timeString ? timeString.trim() : "0 seconds";
};

useInterval(() => {
    renderTexts(defaultedProps.value.units);
}, 1000);

onMounted(() => {
    renderTexts(defaultedProps.value.units);
});
</script>

<style scoped>
.countdown {
    display: block;
}
</style>

// src/modules/web-components/countdown/countdown.ts
import { LitElement, html } from "lit";
import {
  customElement,
  property,
  queryAssignedElements
} from "lit/decorators.js";
import { defaultTimeUnits, reduceTimeUnits } from "src/modules/interfaces/component/countdown/types";

declare global {
  interface HTMLElementTagNameMap {
    "countdown-component": CountdownComponent;
  }
}

export interface TimeUnit {
  name: string;
  timeFactor: number;
}

@customElement("countdown-component")
export class CountdownComponent extends LitElement {
  private static units: TimeUnit[] = reduceTimeUnits(defaultTimeUnits);

  @property({ converter: {
    fromAttribute: (string) => new Date(string ?? 'May 6, 2085 11:00:00'),
    toAttribute: (date: Date) => date.toString()
  } })
  date = new Date('May 6, 2085 11:00:00');

  @queryAssignedElements({ selector: '[data-countdown]', flatten: true })
  _countdownItems!: HTMLElement[];

  private intervalId = 0;

  protected firstUpdated(): void {
    this.renderTexts();
  }

  renderTexts(units = CountdownComponent.units) {
    let timeString = "", distance = this.date.getTime() - new Date().getTime();
    units.forEach(({ timeFactor, name }) => {
      const value = Math.floor(distance / timeFactor);
      timeString += value <= 0 ? '' : `${value} ${String(value).slice(-1) === '1' ? name : name + 's'} `;
      distance %= timeFactor;
    });
    timeString = timeString ? timeString.trim() : "0 seconds";

    for (const element of this._countdownItems) element.textContent = timeString;
  }

  connectedCallback(): void {
    super.connectedCallback();
    this.intervalId = window.setInterval(() => { this.renderTexts(); }, 1000);
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    window.clearInterval(this.intervalId);
  }

  render() {
    return html`<slot></slot>`;
  }
}
