// src/modules/vue-components/image-comparator/ImageComparatorItem.vue
<template>
    <li class="image-comparator-item" ref="item">
        <slot></slot>
    </li>
</template>

<script setup lang="ts">
import { uid } from 'src/modules/utils';
import { useLinkedItem } from '../../interfaces/generic/hooks/useLinkedItem.vue';
import { ref } from 'vue';

const item = ref<HTMLElement | null>(null);
useLinkedItem(uid, item);
</script>

<style scoped>
.image-comparator-item {
  position: absolute;
  width: auto;
  height: auto;
  overflow: hidden;
}
</style>

// lit/src/components/image-comparator/imageComparatorItem.ts
import { LitElement, css, html } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { LinkedItemMixin } from "../../interfaces/hooks/linkedItems";

export class ImageComparatorItem extends LinkedItemMixin(LitElement) {
	static styles = css`
		:host {
			display: contents;
		}

		.image-comparator-item {
			position: absolute;
			width: auto;
			height: auto;
			overflow: hidden;
		}
	`;

	render() {
		return html`<div class="image-comparator-item" style=${styleMap(this.linkedItemStyles)}>
			<slot></slot>
		</div>`;
	}
}
