// lit/src/components/backface-carousel/backfaceCarouselItem.ts
import { LitElement, css, html } from "lit";
import { LinkedItemMixin } from "../../interfaces/hooks/linkedItems";
import { styleMap } from "lit/directives/style-map.js";

export class BackfaceCarouselItem extends LinkedItemMixin(LitElement) {
	static styles = css`
		:host {
			display: contents;
		}

		.backface-carousel-item {
			position: relative;
			width: 100%;
			height: auto;
			padding: 0;
			opacity: 0.9999;
			backface-visibility: hidden;
		}

		:host(:not(:first-of-type)) .backface-carousel-item {
			position: absolute;
			left: 0;
			top: 0;
			margin: 0 auto;
			padding: 0 auto;
		}
	`;

	render() {
		return html`<li class="backface-carousel-item" style=${styleMap(this.linkedItemStyles)}>
			<slot></slot>
		</li>`;
	}
}

// src/modules/vue-components/backface-carousel/BackfaceCarouselItem.vue
<template>
    <li class="backface-carousel-item" ref="item">
        <slot></slot>
    </li>
</template>

<script setup lang="ts">
import { uid } from 'src/modules/utils';
import { useLinkedItem } from '../../interfaces/generic/hooks/useLinkedItem.vue';
import { ref } from 'vue';

const item = ref<HTMLElement | null>(null);
useLinkedItem(uid, item);
</script>

<style scoped>
.backface-carousel-item {
    position: relative;
    width: 100%;
    height: auto;
    padding: 0;
    opacity: 0.9999;
    backface-visibility: hidden;
}

.backface-carousel-item:not(:first-of-type) {
    position: absolute;
    left: 0;
    top: 0;
    margin: 0 auto;
    padding: 0 auto;
}
</style>
