// src/modules/vue-components/one-page-scroll/OnePageScroll.vue
<template>
	<article>
		<div class="wrap" :class="{ 'wrap--horizontal': isHorizontal, 'wrap--no-scrollbar': noScrollbar }" @wheel="onWheel" ref="wrap">
			<slot></slot>
		</div>
	</article>
</template>

<script setup lang="ts">
import { OnePageScrollConfiguration, easeInOutQuad } from "src/modules/interfaces/component/one-page-scroll/types";
import { CarouselDirection } from "src/modules/interfaces/generic/carousel/carousel";
import { useInjectedLinkedItems } from "src/modules/interfaces/generic/hooks/useLinkedItem.vue";
import { computed, onUnmounted, ref } from "vue";

const props = withDefaults(defineProps<Partial<OnePageScrollConfiguration>>(), {
	isHorizontal: false,
	noScrollbar: true,
	increment: 6,
	duration: 500
});
const elements = useInjectedLinkedItems();
const elementsLength = computed(() => Object.keys(elements).length);
const firstElement = computed(() => Object.values(elements)[0].element);
const selectedItem = ref(0);
const isScrolling = ref(false);
const wrap = ref<HTMLElement | null>(null);
const animationTimeout = ref<number | undefined>();

const smoothScrollTo = (to: number) => {
	if (!wrap.value) return;
	isScrolling.value = true;
	const property = props.isHorizontal ? "scrollLeft" : "scrollTop";
	const start = wrap.value[property],
		change = to - start;
	let currentTime = 0;

	const animateScroll = () => {
		if (!wrap.value) return;
		currentTime += props.increment;
		const quad = easeInOutQuad(currentTime, start, change, props.duration);
		if (quad > props.increment) {
			wrap.value[property] = quad - props.increment / 2;
		} else wrap.value[property] = quad;

		if (currentTime < props.duration) {
			setTimeout(animateScroll, props.increment);
		} else if (currentTime >= props.duration) {
			wrap.value[property] = to;
			isScrolling.value = false;
		}
	};
	animateScroll();
};

const scrollSlide = (direction: CarouselDirection) => {
	if (isScrolling.value) return;
	selectedItem.value += direction;
	smoothScrollTo(
		Object.values(elements)[selectedItem.value].element[props.isHorizontal ? "offsetWidth" : "offsetHeight"] * selectedItem.value
	);
};

const onWheel = (event: WheelEvent) => {
	if (event.deltaY > 0) {
		if (selectedItem.value >= elementsLength.value - 1) {
			if (isScrolling.value) return;
			selectedItem.value = 0;
			smoothScrollTo(0);
		} else scrollSlide(CarouselDirection.FORWARDS);
	} else {
		if (selectedItem.value === 0) {
			if (isScrolling.value || !wrap.value) return;
			selectedItem.value = elementsLength.value - 1;
			smoothScrollTo(
				(props.isHorizontal ? wrap.value.scrollWidth : wrap.value.scrollHeight) -
					(props.isHorizontal ? firstElement.value.offsetWidth : firstElement.value.offsetHeight)
			);
		} else scrollSlide(CarouselDirection.BACKWARDS);
	}
};

onUnmounted(() => {
	window.clearTimeout(animationTimeout.value);
});
</script>

<style scoped>
.wrap {
	width: 100%;
	height: 100%;
	min-height: 100%;
	max-height: 100%;
	overflow-x: hidden;
	overflow-y: scroll;
}

.wrap--horizontal {
	display: flex;
	overflow-x: scroll;
	overflow-y: hidden;
}

.wrap--no-scrollbar {
	overflow: hidden;
}
</style>

// src/modules/web-components/one-page-scroll/onePageScroll.ts
import { LitElement, css, html } from "lit";
import { customElement, property, query, queryAssignedElements, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { OnePageScrollConfiguration, easeInOutQuad } from "src/modules/interfaces/component/one-page-scroll/types";
import { CarouselDirection } from "src/modules/interfaces/generic/carousel/carousel";

declare global {
	interface HTMLElementTagNameMap {
		"one-page-scroll-component": OnePageScrollComponent;
	}
}

@customElement("one-page-scroll-component")
export class OnePageScrollComponent extends LitElement implements OnePageScrollConfiguration {
	static styles = css`
		.wrap {
			width: 100%;
			height: 100%;
			min-height: 100%;
			max-height: 100%;
			overflow-x: hidden;
			overflow-y: scroll;
		}

		.wrap--horizontal {
			display: flex;
			overflow-x: scroll;
			overflow-y: hidden;
		}

		.wrap--no-scrollbar {
			overflow: hidden;
		}
	`;

	@property({ type: Boolean })
	isHorizontal = false;
	@property({ type: Number })
	duration = 500;
	@property({ type: Number })
	increment = 6;
	@property({ type: Boolean })
	noScrollbar = false;

	@state()
	_selectedItem = 0;
	@state()
	_isScrolling = false;

	private scrollEventListener?: (event: WheelEvent) => void;

	@queryAssignedElements()
	_onePageScrollElements!: HTMLElement[];
	@query(".wrap")
	_wrapElement!: HTMLDivElement;

	protected smoothScrollTo(to: number) {
		this._isScrolling = true;
		const wrap = this._wrapElement;
		const start = this.isHorizontal ? wrap.scrollLeft : wrap.scrollTop,
			change = to - start;
		let currentTime = 0;
		const property = this.isHorizontal ? "scrollLeft" : "scrollTop";

		const animateScroll = () => {
			if (!this.scrollEventListener) return;
			currentTime += this.increment;
			const quad = easeInOutQuad(currentTime, start, change, this.duration);
			if (quad > this.increment) {
				wrap[property] = quad - this.increment / 2;
			} else wrap[property] = quad;
			if (currentTime < this.duration) {
				setTimeout(animateScroll, this.increment);
			} else if (currentTime >= this.duration) {
				wrap[property] = to;
				this._isScrolling = false;
			}
		};
		animateScroll();
	}

	protected scrollSlide(direction: CarouselDirection) {
		if (this._isScrolling) return;
		this._selectedItem += direction;
		this.smoothScrollTo(
			this._onePageScrollElements[this._selectedItem][this.isHorizontal ? "offsetWidth" : "offsetHeight"] * this._selectedItem
		);
	}

	protected firstUpdated() {
		const items = this._onePageScrollElements;
		this._wrapElement.addEventListener(
			"wheel",
			(this.scrollEventListener = (event) => {
				if (event.deltaY > 0) {
					if (this._selectedItem >= items.length - 1) {
						if (!this._isScrolling) this.smoothScrollTo((this._selectedItem = 0));
					} else this.scrollSlide(CarouselDirection.FORWARDS);
				} else {
					if (this._selectedItem === 0) {
						if (!this._isScrolling) {
							this._selectedItem = items.length - 1;
							this.smoothScrollTo(
								(this.isHorizontal ? this._wrapElement.scrollWidth : this._wrapElement.scrollHeight) -
									(this.isHorizontal ? items[0].offsetWidth : items[0].offsetHeight)
							);
						}
					} else this.scrollSlide(CarouselDirection.BACKWARDS);
				}
			}),
			{ passive: true }
		);
	}

	disconnectedCallback(): void {
		if (this.scrollEventListener) this._wrapElement.removeEventListener("wheel", this.scrollEventListener);
		super.disconnectedCallback();
	}

	render() {
		return html`<div class="wrap ${classMap({ "wrap--horizontal": this.isHorizontal, "wrap--no-scrollbar": this.noScrollbar })}">
			<slot></slot>
		</div>`;
	}
}
