// vue/src/components/table-filtering/TableFilteringHeader.vue
<template>
    <th ref="header">
        <slot></slot>
    </th>
</template>

<script setup lang="ts">
import { useLinkedItem } from '../../interfaces/hooks/useLinkedItem';
import { ref } from 'vue';
import { uid } from 'shared/utils/utils';

const header = ref<HTMLElement | null>(null);
useLinkedItem(() => `table-header-${uid()}`, header);
</script>

// react/src/components/table-filtering/TableFilteringHeader.tsx
import React, { useRef } from "react";
import { useLinkedItem } from "../../../src/interfaces/hooks/useLinkedItem";
import { uid } from "shared/utils/utils";
import { TableHeaderConfiguration } from "../../interfaces/component/tableFiltering";

export const TableFilteringHeader = (props: TableHeaderConfiguration) => {
	const item = useRef<HTMLTableCellElement | null>(null);
	const styleObject = useLinkedItem(() => `table-header-${uid()}`, item);

	return (
		<th
			ref={item}
			style={styleObject}
			className={props.className}
			onClick={() => {
				props.onClick();
			}}
		>
			{props.children}
		</th>
	);
};
