// src/modules/vue-components/table-filtering/TableFilteringRow.vue
<template>
    <tr ref="row">
        <slot></slot>
    </tr>
</template>

<script setup lang="ts">
import { useLinkedItem } from '../../interfaces/generic/hooks/useLinkedItem.vue';
import { ref } from 'vue';
import { uid } from '../../utils';

const row = ref<HTMLElement | null>(null);
useLinkedItem(() => `table-row-${uid()}`, row);
</script>

// react/src/components/table-filtering/TableFilteringRow.tsx
import React, { useRef } from "react";
import { useLinkedItem } from "../../../src/interfaces/hooks/useLinkedItem";
import { uid } from "shared/utils/utils";
import { WithChildren } from "../../utils/utils";
import { GenericReactComponentProps } from "../../interfaces/generic/classNameFallthrough";

export const TableFilteringRow = (props: WithChildren<object> & GenericReactComponentProps) => {
	const item = useRef<HTMLTableRowElement | null>(null);
	const styleObject = useLinkedItem(() => `table-row-${uid()}`, item);

	return (
		<tr ref={item} style={styleObject} className={props.className}>
			{props.children}
		</tr>
	);
};
