// lit/src/components/countdown/countdown.ts
import { LitElement } from "lit";
import { property, state } from "lit/decorators.js";
import { IntervalController } from "../../interfaces/hooks/intervalController";
import { CountdownConfiguration, defaultTimeUnits, reduceTimeUnits } from "shared/component/countdown";

export class CountdownComponent extends LitElement implements CountdownConfiguration {
	@property({ type: Date })
	date = new Date("May 6, 2085 11:00:00");
	@property({ type: Array })
	units = reduceTimeUnits(defaultTimeUnits);
	@state()
	_text = "";

	protected intervalController = new IntervalController(
		this,
		() => {
			this.renderTexts();
		},
		1000
	);

	protected firstUpdated(): void {
		this.renderTexts();
	}

	renderTexts() {
		let timeString = "",
			distance = this.date.getTime() - new Date().getTime();
		this.units.forEach(({ timeFactor, name }) => {
			const value = Math.floor(distance / timeFactor);
			timeString += value <= 0 ? "" : `${String(value)} ${String(value).slice(-1) === "1" ? name : name + "s"} `;
			distance %= timeFactor;
		});

		this._text = timeString ? timeString.trim() : "0 seconds";
	}

	render() {
		return this._text;
	}
}

// vue/src/components/countdown/Countdown.vue
<template>
    <span class="countdown">{{ text }}</span>
</template>

<script setup lang="ts">
import { useInterval } from "../../interfaces/hooks/useInterval";
import { onMounted, ref } from 'vue';
import { defaultTimeUnits, reduceTimeUnits, TimeUnit } from 'shared/component/countdown';
import { CountdownConfiguration } from "shared/component/countdown";

const props = withDefaults(defineProps<Partial<CountdownConfiguration>>(), {
    units: () => reduceTimeUnits(defaultTimeUnits),
    date: () => new Date('May 6, 2085 11:00:00')
});
const text = ref<string>("");

const renderTexts = (units: TimeUnit[]) => {
    let timeString = "", distance = props.date.getTime() - new Date().getTime();
    for (const { timeFactor, name } of units) {
        const value = Math.floor(distance / timeFactor);
        timeString += value <= 0 ? '' : `${value} ${String(value).slice(-1) === '1' ? name : name + 's'} `;
        distance %= timeFactor;
    }
    
    text.value = timeString ? timeString.trim() : "0 seconds";
};

useInterval(() => {
    renderTexts(props.units);
}, 1000);

onMounted(() => {
    renderTexts(props.units);
});
</script>

<style scoped>
.countdown {
    display: block;
}
</style>
