// react/src/components/one-page-scroll/OnePageScroll.tsx
import React, { useCallback, useEffect, useRef } from "react";
import { ExposedContextFunctions, ContextLinkedItems } from "../../interfaces/hooks/useLinkedItem";
import { easeInOutQuad } from "shared/component/onePageScroll";
import { OnePageScrollConfiguration } from "../../interfaces/component/onePageScroll";
import styles from "./OnePageScroll.module.css";
import { CarouselDirection } from "shared/interfaces/carousel";

export const OnePageScroll = ({
	isHorizontal = false,
	noScrollbar = true,
	increment = 6,
	duration = 500,
	...props
}: OnePageScrollConfiguration) => {
	const linkedItemsContext = useRef<ExposedContextFunctions | null>(null);
	const wrap = useRef<HTMLDivElement | null>(null);
	const animationTimeout = useRef<{ timer?: number }>({ timer: undefined });
	const selectedItem = useRef(0);
	const isScrolling = useRef(false);

	const smoothScrollTo = useCallback((to: number) => {
		if (!wrap.current) return;
		isScrolling.current = true;
		const property = isHorizontal ? "scrollLeft" : "scrollTop";
		const start = wrap.current[property],
			change = to - start;
		let currentTime = 0;

        const animateScroll = () => {
            if (!wrap.current) return;
            currentTime += increment;
            const quad = easeInOutQuad(currentTime, start, change, duration);
            if (quad > increment) {
                wrap.current[property] = quad - increment / 2;
            } else wrap.current[property] = quad;
    
            if (currentTime < duration) {
                animationTimeout.current.timer = window.setTimeout(animateScroll, increment);
            } else if (currentTime >= duration) {
                wrap.current[property] = to;
                isScrolling.current = false;
            }
        };
        
        animateScroll();    
	}, [duration, increment, isHorizontal]);

	const scrollSlide = useCallback(
		(direction: CarouselDirection) => {
			const element = Object.values(linkedItemsContext.current?.getState() ?? {})[selectedItem.current]?.element?.current;
			if (isScrolling.current || !element) return;
			selectedItem.current += direction;

			smoothScrollTo(element[isHorizontal ? "offsetWidth" : "offsetHeight"] * selectedItem.current);
		},
		[isHorizontal, smoothScrollTo]
	);

	const onWheel = useCallback(
		(event: React.WheelEvent<HTMLDivElement>) => {
			const elements = linkedItemsContext.current?.getState();
			if (!elements) return;
			const elementsLength = Object.keys(elements).length;
			const firstElement = Object.values(elements)[0].element.current;
			if (!firstElement) return;

			if (event.deltaY > 0) {
				if (selectedItem.current >= elementsLength - 1) {
					if (isScrolling.current) return;
					selectedItem.current = 0;
					smoothScrollTo(0);
				} else scrollSlide(CarouselDirection.FORWARDS);
			} else {
				if (selectedItem.current === 0) {
					if (isScrolling.current || !wrap.current) return;
					selectedItem.current = elementsLength - 1;
					smoothScrollTo(
						(isHorizontal ? wrap.current.scrollWidth : wrap.current.scrollHeight) -
							(isHorizontal ? firstElement.offsetWidth : firstElement.offsetHeight)
					);
				} else scrollSlide(CarouselDirection.BACKWARDS);
			}
		},
		[isHorizontal, scrollSlide, smoothScrollTo]
	);

	useEffect(() => {
		const animationTimeoutObject = animationTimeout.current;

		return () => {
			window.clearTimeout(animationTimeoutObject.timer);
		};
	}, []);

	return (
		<ContextLinkedItems ref={linkedItemsContext} innerChildren={props.children}>
			<article className={props.className}>
				<div
					ref={wrap}
					onWheel={onWheel}
					className={`${styles.wrap} ${isHorizontal ? styles["wrap--horizontal"] : ""} ${noScrollbar ? styles["wrap--no-scrollbar"] : ""}`}
				>
					{props.children}
				</div>
			</article>
		</ContextLinkedItems>
	);
};

// src/modules/vue-components/one-page-scroll/OnePageScroll.vue
<template>
	<article>
		<div class="wrap" :class="{ 'wrap--horizontal': isHorizontal, 'wrap--no-scrollbar': noScrollbar }" @wheel="onWheel" ref="wrap">
			<slot></slot>
		</div>
	</article>
</template>

<script setup lang="ts">
import { OnePageScrollConfiguration, easeInOutQuad } from "src/modules/interfaces/component/one-page-scroll/types";
import { CarouselDirection } from "src/modules/interfaces/generic/carousel/carousel";
import { useInjectedLinkedItems } from "src/modules/interfaces/generic/hooks/useLinkedItem.vue";
import { computed, onUnmounted, ref } from "vue";

const props = withDefaults(defineProps<Partial<OnePageScrollConfiguration>>(), {
	isHorizontal: false,
	noScrollbar: true,
	increment: 6,
	duration: 500
});
const elements = useInjectedLinkedItems();
const elementsLength = computed(() => Object.keys(elements).length);
const firstElement = computed(() => Object.values(elements)[0].element);
const selectedItem = ref(0);
const isScrolling = ref(false);
const wrap = ref<HTMLElement | null>(null);
const animationTimeout = ref<number | undefined>();

const smoothScrollTo = (to: number) => {
	if (!wrap.value) return;
	isScrolling.value = true;
	const property = props.isHorizontal ? "scrollLeft" : "scrollTop";
	const start = wrap.value[property],
		change = to - start;
	let currentTime = 0;

	const animateScroll = () => {
		if (!wrap.value) return;
		currentTime += props.increment;
		const quad = easeInOutQuad(currentTime, start, change, props.duration);
		if (quad > props.increment) {
			wrap.value[property] = quad - props.increment / 2;
		} else wrap.value[property] = quad;

		if (currentTime < props.duration) {
			setTimeout(animateScroll, props.increment);
		} else if (currentTime >= props.duration) {
			wrap.value[property] = to;
			isScrolling.value = false;
		}
	};
	animateScroll();
};

const scrollSlide = (direction: CarouselDirection) => {
	if (isScrolling.value) return;
	selectedItem.value += direction;
	smoothScrollTo(
		Object.values(elements)[selectedItem.value].element[props.isHorizontal ? "offsetWidth" : "offsetHeight"] * selectedItem.value
	);
};

const onWheel = (event: WheelEvent) => {
	if (event.deltaY > 0) {
		if (selectedItem.value >= elementsLength.value - 1) {
			if (isScrolling.value) return;
			selectedItem.value = 0;
			smoothScrollTo(0);
		} else scrollSlide(CarouselDirection.FORWARDS);
	} else {
		if (selectedItem.value === 0) {
			if (isScrolling.value || !wrap.value) return;
			selectedItem.value = elementsLength.value - 1;
			smoothScrollTo(
				(props.isHorizontal ? wrap.value.scrollWidth : wrap.value.scrollHeight) -
					(props.isHorizontal ? firstElement.value.offsetWidth : firstElement.value.offsetHeight)
			);
		} else scrollSlide(CarouselDirection.BACKWARDS);
	}
};

onUnmounted(() => {
	window.clearTimeout(animationTimeout.value);
});
</script>

<style scoped>
.wrap {
	width: 100%;
	height: 100%;
	min-height: 100%;
	max-height: 100%;
	overflow-x: hidden;
	overflow-y: scroll;
}

.wrap--horizontal {
	display: flex;
	overflow-x: scroll;
	overflow-y: hidden;
}

.wrap--no-scrollbar {
	overflow: hidden;
}
</style>
