// vue/src/components/parallax/Parallax.vue
<template>
  <div
    ref="wrap"
    class="wrap"
    :style="styles"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ParallaxConfiguration } from "shared/component/parallax";
import { getFirstScrollableParent } from "shared/utils/domUtils";
import { ref, onMounted, onUnmounted, reactive, CSSProperties } from "vue";

const wrap = ref<HTMLElement | null>(null);
const styles = reactive<CSSProperties>({});
const props = withDefaults(defineProps<Partial<ParallaxConfiguration>>(), {
	isHorizontal: false,
	isHorizontalTranslation: false,
	effect: 1.968,
	speed: 2.7,
	margin: 0
});

const scrollListener = ref<EventListener | undefined>();

const rerender = () => {
	if (!wrap.value) return;
	const parent = getFirstScrollableParent(wrap.value, props.isHorizontal);
	if (scrollListener.value) parent.removeEventListener("scroll", scrollListener.value);
	const getScrollPoint = (parent: HTMLElement | Window) => {
		if (parent instanceof HTMLElement) {
			return props.isHorizontal ? parent.scrollLeft : parent.scrollTop;
		} else return props.isHorizontal ? parent.scrollX : parent.scrollY;
	};

	const animationOffset = wrap.value.getBoundingClientRect()[props.isHorizontal ? "left" : "top"] + getScrollPoint(parent);
	const innerHeight =
		(parent instanceof HTMLElement
			? props.isHorizontal
				? parent.clientWidth
				: parent.clientHeight
			: props.isHorizontal
			? parent.innerWidth
			: parent.innerHeight) / props.effect;

	const scrollEventListener = () => {
        if (!wrap.value) return;
		const scrollPoint = getScrollPoint(getFirstScrollableParent(wrap.value, props.isHorizontal));
		if (scrollPoint > animationOffset - innerHeight * 2 && scrollPoint < animationOffset + innerHeight) {
			const point = (scrollPoint - (animationOffset - innerHeight)) / props.speed - props.margin;
			styles.transform = `translate${props.isHorizontalTranslation ? "X" : "Y"}(${point}px)`;
		}
	};

	scrollListener.value = scrollEventListener;
	parent.addEventListener("scroll", scrollEventListener, { passive: true });
	scrollEventListener();
};

onMounted(() => {
	rerender();
	window.addEventListener("resize", rerender);
});

onUnmounted(() => {
	window.removeEventListener("resize", rerender);
});
</script>

<style scoped>
.wrap {
	position: relative;
	transition: 0.1s;
}
</style>

// lit/src/components/parallax/parallax.ts
import { LitElement, html, css } from "lit";
import { property, query } from "lit/decorators.js";
import { ParallaxConfiguration } from "shared/component/parallax";
import { getFirstScrollableParent } from "shared/utils/domUtils";

export class ParallaxComponent extends LitElement implements ParallaxConfiguration {
	static styles = css`
		.wrap {
			position: relative;
            transition: 0.1s;
		}
	`;

	@property({ type: Boolean })
	isHorizontal = false;
	@property({ type: Boolean })
	isHorizontalTranslation = false;
	@property({ type: Number })
	effect = 1.968;
	@property({ type: Number })
	speed = 2.7;
	@property({ type: Number })
	margin = 0;

	@query(".wrap")
	_wrapper!: HTMLElement;

	private scrollListener!: EventListener;
	private resizeListener!: EventListener;

	protected rerender() {
		const wrap = this._wrapper;
		const parent = getFirstScrollableParent(this, this.isHorizontal);
		parent.removeEventListener("scroll", this.scrollListener);
		const getScrollPoint = () => {
			if (parent instanceof HTMLElement) {
				return this.isHorizontal ? parent.scrollLeft : parent.scrollTop;
			} else return this.isHorizontal ? parent.scrollX : parent.scrollY;
		};

		const animationOffset = wrap.getBoundingClientRect()[this.isHorizontal ? "left" : "top"] + getScrollPoint();
		const innerHeight =
			(parent instanceof HTMLElement
				? this.isHorizontal
					? parent.clientWidth
					: parent.clientHeight
				: this.isHorizontal
				? parent.innerWidth
				: parent.innerHeight) / this.effect;
		parent.addEventListener(
			"scroll",
			(this.scrollListener = () => {
				const scrollPoint = getScrollPoint();
				if (scrollPoint > animationOffset - innerHeight * 2 && scrollPoint < animationOffset + innerHeight) {
					const point = (scrollPoint - (animationOffset - innerHeight)) / this.speed - this.margin;
					wrap.style.transform = `translate${this.isHorizontalTranslation ? "X" : "Y"}(${point}px)`;
				}
			}),
			{ passive: true }
		);
		this.scrollListener(new Event("scroll"));
	}

	protected firstUpdated() {
		this.rerender();
		window.addEventListener(
			"resize",
			(this.resizeListener = () => {
				this.rerender();
			})
		);
	}

	disconnectedCallback(): void {
		super.disconnectedCallback();
		window.removeEventListener("resize", this.resizeListener);
	}

	render() {
		return html`<div class="wrap">
			<slot></slot>
		</div>`;
	}
}
