// src/modules/web-components/typing-text/typingText.ts
import { customElement, property } from "lit/decorators.js";
import { TypingTextLitConfiguration } from "src/modules/interfaces/component/typing-text/types.lit";
import { SelfModifyingText } from "src/modules/interfaces/generic/selfModifyingText/selfModifyingText.lit";

declare global {
	interface HTMLElementTagNameMap {
		"typing-text-component": TypingTextComponent;
	}
}

@customElement("typing-text-component")
export class TypingTextComponent extends SelfModifyingText implements TypingTextLitConfiguration {
	@property({ type: Number })
	interval = 4500;
	@property({ type: Number })
	typingSpeed = 35;
	@property({ type: Number })
	unTypingSpeed?: number;
	@property({ type: Boolean })
	eachLetterAsSpan = false;

	splitText(newString?: string) {
        if (this.eachLetterAsSpan) super.splitTextAlgorithm(newString);
	}

	async triggerTextAnimation(fromText: string, toText: string) {
		const elements = this._elements;
		for (let i = 1; i < fromText.length + 1; i++) {
			await new Promise<void>((resolve) =>
				setTimeout(() => {
                    if (this.eachLetterAsSpan) {
                        for (const element of elements) {
                            element.lastChild?.remove();
                        }
                    } else for (const element of elements) element.textContent = fromText.slice(0, -i);
					resolve();
				}, this.unTypingSpeed ?? this.typingSpeed)
			);
		}

		for (let i = 1; i < toText.length + 1; i++) {
			await new Promise<void>((resolve) =>
				setTimeout(() => {
                    if (this.eachLetterAsSpan) {
                        const spanElement = document.createElement("span");
                        spanElement.textContent = toText[i - 1];
                        for (const element of elements) element.append(spanElement);
                    } else for (const element of elements) element.textContent = toText.slice(0, i);
					resolve();
				}, this.typingSpeed)
			);
		}

		setTimeout(() => { this.onInterval(); }, this.interval);
	}
}

// src/modules/vue-components/typing-text/TypingText.vue
<template>
	<pre>
        <span v-for="letter in settings.currentTextValue.value" v-text="letter.letter" :class="letter.classes.join('')"></span>
    </pre>
</template>

<script setup lang="ts">
import { onUnmounted, ref } from "vue";
import { TypingTextConfiguration } from "../../interfaces/component/typing-text/types";
import { useSelfModifyingText } from "../../interfaces/generic/selfModifyingText/selfModifyingText.vue";

const props = withDefaults(defineProps<TypingTextConfiguration>(), {
	repetitions: 1,
	interval: 4500,
	typingSpeed: 35
});
const settings = useSelfModifyingText({
	strings: props.strings,
	repetitions: props.repetitions,
	interval: props.interval,
	typingSpeed: props.typingSpeed,
	triggerTextAnimation
});

const timeout = ref<number | undefined>();

async function triggerTextAnimation(fromText: string, toText: string) {
	const fromArray = fromText.split("").map((letter) => ({ letter, classes: [] }));
	const toArray = toText.split("").map((letter) => ({ letter, classes: [] }));

	for (let i = 1; i < fromText.length + 1; i++) {
		await new Promise<void>(
			(resolve) =>
				(timeout.value = window.setTimeout(() => {
					settings.currentTextValue.value = fromArray.slice(0, -i);
					resolve();
				}, props.unTypingSpeed ?? props.typingSpeed))
		);
	}

	for (let i = 1; i < toText.length + 1; i++) {
		await new Promise<void>(
			(resolve) =>
				(timeout.value = window.setTimeout(() => {
					settings.currentTextValue.value = toArray.slice(0, i);
					resolve();
				}, props.unTypingSpeed ?? props.typingSpeed))
		);
	}

	setTimeout(() => {
		clearTimeout(timeout.value);
		settings.onInterval();
	}, props.interval);
}

onUnmounted(() => {
	clearTimeout(timeout.value);
});
</script>
