// react/src/components/typing-text/TypingText.tsx
import React, { useCallback, useEffect, useRef } from "react";
import { ModifyingTextContext, useSelfModifyingText } from "../../interfaces/hooks/useSelfModifyingText";
import { TypingTextConfiguration } from "shared/component/typingText";
import { TriggerTextAnimationCallback } from "shared/interfaces/selfModifyingText";
import { GenericReactComponentProps } from "react/src/interfaces/generic/classNameFallthrough";

export const TypingText = ({
	repetitions = 1,
	interval = 4500,
	typingSpeed = 35,
	...props
}: TypingTextConfiguration & GenericReactComponentProps) => {
	const timeout = useRef<number>();

	const triggerTextAnimation = useCallback<TriggerTextAnimationCallback<ModifyingTextContext>>(
		async ({ context, toText, fromText }) => {
			const fromArray = fromText.split("").map((letter) => ({ letter, classes: [] }));
			const toArray = toText.split("").map((letter) => ({ letter, classes: [] }));

			for (let i = 1; i < fromText.length + 1; i++) {
				await new Promise<void>(
					(resolve) =>
						(timeout.current = window.setTimeout(() => {
							context.setCurrentTextValue(fromArray.slice(0, -i));
							resolve();
						}, props.unTypingSpeed ?? typingSpeed))
				);
			}

			for (let i = 1; i < toText.length + 1; i++) {
				await new Promise<void>(
					(resolve) =>
						(timeout.current = window.setTimeout(() => {
							context.setCurrentTextValue(toArray.slice(0, i));
							resolve();
						}, props.unTypingSpeed ?? typingSpeed))
				);
			}

			timeout.current = window.setTimeout(() => {
				timeout.current = undefined;
				context.onInterval();
			}, interval);
		},
		[interval, props.unTypingSpeed, typingSpeed]
	);

	useEffect(() => {
		return () => {
			window.clearTimeout(timeout.current);
		};
	}, []);

	const currentTextValue = useSelfModifyingText({
		strings: props.strings,
		repetitions,
		interval,
		typingSpeed,
		triggerTextAnimation
	});

	return (
		<pre className={props.className}>
			{currentTextValue.map((letter, i) => (
				<span className={letter.classes.join("")} key={`${letter.letter}-${i}`}>
					{letter.letter}
				</span>
			))}
		</pre>
	);
};

// src/modules/vue-components/typing-text/TypingText.vue
<template>
	<pre>
        <span v-for="letter in settings.currentTextValue.value" v-text="letter.letter" :class="letter.classes.join('')"></span>
    </pre>
</template>

<script setup lang="ts">
import { onUnmounted, ref } from "vue";
import { TypingTextConfiguration } from "../../interfaces/component/typing-text/types";
import { useSelfModifyingText } from "../../interfaces/generic/selfModifyingText/selfModifyingText.vue";

const props = withDefaults(defineProps<TypingTextConfiguration>(), {
	repetitions: 1,
	interval: 4500,
	typingSpeed: 35
});
const settings = useSelfModifyingText({
	strings: props.strings,
	repetitions: props.repetitions,
	interval: props.interval,
	typingSpeed: props.typingSpeed,
	triggerTextAnimation
});

const timeout = ref<number | undefined>();

async function triggerTextAnimation(fromText: string, toText: string) {
	const fromArray = fromText.split("").map((letter) => ({ letter, classes: [] }));
	const toArray = toText.split("").map((letter) => ({ letter, classes: [] }));

	for (let i = 1; i < fromText.length + 1; i++) {
		await new Promise<void>(
			(resolve) =>
				(timeout.value = window.setTimeout(() => {
					settings.currentTextValue.value = fromArray.slice(0, -i);
					resolve();
				}, props.unTypingSpeed ?? props.typingSpeed))
		);
	}

	for (let i = 1; i < toText.length + 1; i++) {
		await new Promise<void>(
			(resolve) =>
				(timeout.value = window.setTimeout(() => {
					settings.currentTextValue.value = toArray.slice(0, i);
					resolve();
				}, props.unTypingSpeed ?? props.typingSpeed))
		);
	}

	setTimeout(() => {
		clearTimeout(timeout.value);
		settings.onInterval();
	}, props.interval);
}

onUnmounted(() => {
	clearTimeout(timeout.value);
});
</script>
