// react/src/components/typing-text/TypingText.tsx
import React, { useCallback, useEffect, useRef } from "react";
import { ModifyingTextContext, useSelfModifyingText } from "../../interfaces/hooks/useSelfModifyingText";
import { TypingTextConfiguration } from "shared/component/typingText";
import { LetterSettings, LetterState, TriggerTextAnimationCallback } from "shared/interfaces/selfModifyingText";
import { GenericReactComponentProps } from "react/src/interfaces/generic/classNameFallthrough";

export const TypingText = ({
	repetitions = 1,
	interval = 4500,
	typingSpeed = 35,
	...props
}: TypingTextConfiguration & GenericReactComponentProps) => {
	const timeout = useRef<number>();

	const triggerTextAnimation = useCallback<TriggerTextAnimationCallback<ModifyingTextContext>>(
		async ({ context, toText, fromText }) => {
			const fromArray = fromText.split("").map<LetterSettings>((letter) => ({ letter, letterState: LetterState.idle }));
			const toArray = toText.split("").map<LetterSettings>((letter) => ({ letter, letterState: LetterState.idle }));

			for (let i = 1; i < fromText.length + 1; i++) {
				await new Promise<void>(
					(resolve) =>
						(timeout.current = window.setTimeout(() => {
							context.setCurrentTextValue(fromArray.slice(0, -i));
							resolve();
						}, props.unTypingSpeed ?? typingSpeed))
				);
			}

			for (let i = 1; i < toText.length + 1; i++) {
				await new Promise<void>(
					(resolve) =>
						(timeout.current = window.setTimeout(() => {
							context.setCurrentTextValue(toArray.slice(0, i));
							resolve();
						}, typingSpeed))
				);
			}

			timeout.current = window.setTimeout(() => {
				timeout.current = undefined;
				context.onInterval();
			}, interval);
		},
		[interval, props.unTypingSpeed, typingSpeed]
	);

	useEffect(() => {
		return () => {
			window.clearTimeout(timeout.current);
		};
	}, []);

	const currentTextValue = useSelfModifyingText({
		strings: props.strings,
		repetitions,
		interval,
		typingSpeed,
		triggerTextAnimation
	});

	return (
		<pre className={props.className}>
			{currentTextValue.map((letter, i) => (
				<span key={`${letter.letter}-${String(i)}`}>
					{letter.letter}
				</span>
			))}
		</pre>
	);
};

// lit/src/components/typing-text/typingText.ts
import { property } from "lit/decorators.js";
import { SelfModifyingText, TriggerTextParams } from "../../interfaces/generic/selfModifyingText";
import { TypingTextConfiguration } from "shared/component/typingText";
import { LetterSettings, LetterState } from "shared/interfaces/selfModifyingText";

export class TypingTextComponent extends SelfModifyingText implements TypingTextConfiguration {
	@property({ type: Number })
	interval = 4500;
	@property({ type: Number })
	typingSpeed = 35;
	@property({ type: Number })
	unTypingSpeed?: number;

	private _timeout?: number;

	async triggerTextAnimation({ context, fromText, toText }: TriggerTextParams) {
		const fromArray = fromText.split("").map<LetterSettings>((letter) => ({ letter, letterState: LetterState.idle }));
		const toArray = toText.split("").map<LetterSettings>((letter) => ({ letter, letterState: LetterState.idle }));

		for (let i = 1; i < fromText.length + 1; i++) {
			await new Promise<void>(
				(resolve) =>
					(this._timeout = window.setTimeout(() => {
						this._currentTextValue = fromArray.slice(0, -i);
						resolve();
					}, this.unTypingSpeed ?? this.typingSpeed))
			);
		}

		for (let i = 1; i < toText.length + 1; i++) {
			await new Promise<void>(
				(resolve) =>
					(this._timeout = window.setTimeout(() => {
						this._currentTextValue = toArray.slice(0, i);
						resolve();
					}, this.typingSpeed))
			);
		}

		this._timeout = window.setTimeout(() => {
			this._timeout = undefined;
			context.onInterval();
		}, this.interval);
	}

	disconnectedCallback(): void {
		super.disconnectedCallback();
		window.clearTimeout(this._timeout);
	}
}
