// vue/src/components/floating-panel/FloatingPanel.vue
<template>
  <div
    v-if="isOpen"
    ref="panel"
    class="panel"
    :style="panelStyles"
    @mousemove="changePosition"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, reactive, CSSProperties } from "vue";
import { FloatingPanelConfiguration, FloatingPanelInternalSettings } from "shared/component/floatingPanel";

const props = defineProps<FloatingPanelConfiguration>();
const panel = ref<HTMLDivElement | null>(null);
const panelProperties = reactive<FloatingPanelInternalSettings>({
    panelX: panel.value?.offsetLeft ?? 0,
    panelY: panel.value?.offsetTop ?? 0,
    clientX: 0,
    clientY: 0,
    dragging: false
});
const panelStyles = reactive<CSSProperties>({});

const changePosition = ({ clientX, clientY }: MouseEvent) => {
    if (!panelProperties.dragging || !props.isOpen) return;
    panelStyles.left = String(panelProperties.panelX + clientX - panelProperties.clientX) + "px";
    panelStyles.top = String(panelProperties.panelY + clientY - panelProperties.clientY) + "px";
};

const onMouseDown = ({ clientX, clientY }: MouseEvent) => {
    if (!panel.value || !props.isOpen) return;
    panelProperties.panelX = panel.value.offsetLeft;
    panelProperties.panelY = panel.value.offsetTop;
    panelProperties.clientX = clientX;
    panelProperties.clientY = clientY;
    panelProperties.dragging = true;
};

const onMouseUp = () => {
    panelProperties.dragging = false;
};

onMounted(() => {
    window.addEventListener("mouseup", onMouseUp, false);
    document.addEventListener("mousedown", onMouseDown);
});

onUnmounted(() => {
    window.removeEventListener("mouseup", onMouseUp, false);
    document.removeEventListener("mousedown", onMouseDown);
});
</script>

// react/src/components/floating-panel/FloatingPanel.tsx
import React, { CSSProperties, useCallback, useEffect, useRef, useState } from "react";
import { WithChildren } from "react/src/utils/utils";
import { FloatingPanelConfiguration, FloatingPanelInternalSettings } from "shared/component/floatingPanel";

export const FloatingPanel = (props: WithChildren<FloatingPanelConfiguration>) => {
	const panel = useRef<HTMLDivElement>(null);
	const [panelProperties, setPanelProperties] = useState<FloatingPanelInternalSettings>({
		panelX: panel.current?.offsetLeft ?? 0,
		panelY: panel.current?.offsetTop ?? 0,
		clientX: 0,
		clientY: 0,
		dragging: false
	});
	const [panelStyles, setPanelStyles] = useState<CSSProperties>({});

	const changePosition = useCallback(
		({ clientX, clientY }: MouseEvent) => {
			if (!panelProperties.dragging || !props.isOpen) return;
			setPanelStyles({
				left: String(panelProperties.panelX + clientX - panelProperties.clientX) + "px",
				top: String(panelProperties.panelY + clientY - panelProperties.clientY) + "px"
			});
		},
		[
			panelProperties.clientX,
			panelProperties.clientY,
			panelProperties.dragging,
			panelProperties.panelX,
			panelProperties.panelY,
			props.isOpen
		]
	);

	const onMouseDown = useCallback(
		({ clientX, clientY }: MouseEvent) => {
			if (!panel.current || !props.isOpen) return;
			setPanelProperties((panelProperties) => ({
				panelX: panel.current?.offsetLeft ?? panelProperties.panelX,
				panelY: panel.current?.offsetTop ?? panelProperties.panelY,
				clientX,
				clientY,
				dragging: true
			}));
		},
		[props.isOpen]
	);

	const onMouseUp = useCallback(() => {
		setPanelProperties((panelProperties) => ({
			...panelProperties,
			dragging: false
		}));
	}, []);

	useEffect(() => {
		window.addEventListener("mouseup", onMouseUp, false);
		document.addEventListener("mousedown", onMouseDown);

		return () => {
			window.removeEventListener("mouseup", onMouseUp, false);
			document.removeEventListener("mousedown", onMouseDown);
		};
	}, [onMouseDown, onMouseUp]);

	if (!props.isOpen) return null;
	return (
		<div
			className={props.className}
			ref={panel}
			onMouseMove={(e) => {
				changePosition(e.nativeEvent);
			}}
			style={panelStyles}
		>
			{props.children}
		</div>
	);
};
