// react/src/components/perspective-carousel/PerspectiveCarousel.tsx
import React, { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { PerspectiveCarouselConfiguration } from "../../interfaces/component/perspectiveCarousel";
import { PerspectiveCarouselItemState, resetInternalState } from "shared/component/perspectiveCarousel";
import { ContextLinkedItems, ExposedContextFunctions, LinkedReactItem } from "../../interfaces/hooks/useLinkedItem";
import carouselControlsStyles from "../../interfaces/generic/CarouselControls.module.css";
import styles from "./PerspectiveCarousel.module.css";
import { assertNonUndefined } from "shared/utils/utils";
import { CarouselDirection } from "shared/interfaces/carousel";
import { getCurrentItemCallback } from "../../utils/carousel";
import { useAutoplay } from "../../interfaces/hooks/useAutoplay";

const getDataFromExposedFunctions = (contextObject: React.MutableRefObject<ExposedContextFunctions | null>) => {
	const linkedItemsContextsState = contextObject.current?.getState();
	const keys = Object.keys(linkedItemsContextsState ?? {});
	const entries = Object.entries(linkedItemsContextsState ?? {});

	return { keys, entries: [...entries].map(([k, v]): [string, LinkedReactItem] => [k, { ...v }]) };
};

export const enum PerspectiveCarouselState {
	INITIALIZING,
	AWAITING_LAYOUT_EFFECT,
	FINISHED
}

export const PerspectiveCarousel = ({
	imageSize = "300px",
	margin = "250px auto",
	startingItem: propsStartingItem = 1,
	separation: propsSeparation = 175,
	separationMultiplier = 0.6,
	horizonOffset: propsHorizonOffset = 0,
	horizonOffsetMultiplier = 1,
	sizeMultiplier = 0.7,
	opacityMultiplier = 0.87,
	horizon: propsHorizon = 0,
	flankingItems = 3,
	isVertical: propsIsVertical = false,
	forcedImageWidth = 0,
	forcedImageHeight = 0,
	animationLength = 300,
	allowSwitchingOrientation = false,
	showArrows = true,
	showToggles = false,
	autoplay,
	movingToCenter,
	movedToCenter,
	movingFromCenter,
	children,
	className
}: Partial<PerspectiveCarouselConfiguration>) => {
	const imageStyles = useMemo(
		() => ({
			margin,
			height: imageSize
		}),
		[imageSize, margin]
	);

	const timeouts = useRef<number[]>();
	const [isInitializing, setInitializing] = useState(PerspectiveCarouselState.INITIALIZING);
	const [currentItem, setCurrentItem] = useState(0);
	const isStateCurrentlyMoving = useRef<Promise<void>>();
	const resolveStateCurrentlyMoving = useRef<() => void>();
	const isNavigatingByToggles = useRef(false);

	const linkedItemsContext = useRef<ExposedContextFunctions | null>(null);
	const state = useRef(resetInternalState<number>());
	const elementsState = useRef<Record<string, Partial<PerspectiveCarouselItemState>>>({});
	const parent = useRef<HTMLUListElement>(null);
	const horizon = useRef(propsHorizon);
	const startingItem = useRef(propsStartingItem);
	const isVertical = useRef(propsIsVertical);

	const forceImageDimensionsIfEnabled = useCallback(() => {
		const { entries } = getDataFromExposedFunctions(linkedItemsContext);
		for (const [, image] of entries) {
			image.styles = { display: "none" };
			if (!forcedImageWidth || !forcedImageHeight) continue;
			image.styles = {
				...image.styles,
				width: `${String(forcedImageWidth)}px`,
				height: `${String(forcedImageHeight)}px`
			};
		}

		linkedItemsContext.current?.updateState(Object.fromEntries(entries));
	}, [forcedImageHeight, forcedImageWidth]);

	const initializeCarouselData = useCallback(() => {
		const { keys } = getDataFromExposedFunctions(linkedItemsContext);
		assertNonUndefined(parent.current);
		const parentStyle = window.getComputedStyle(parent.current);
		state.current.totalItems = keys.length;
		state.current.containerDimensions = [parseInt(parentStyle.width, 10), parseInt(parentStyle.height, 10)];
	}, []);

	const setOriginalItemDimensions = useCallback(() => {
		const { entries } = getDataFromExposedFunctions(linkedItemsContext);
		for (const [key, { element }] of entries) {
			if (!element.current) continue;

			const state = elementsState.current[key];
			if ((!state.originalWidth && !state.originalHeight) || forcedImageWidth > 0 || forcedImageHeight > 0) {
				const initialDisplay = element.current.style.display;
				element.current.style.display = "";
				if (!state.originalWidth || forcedImageWidth > 0) state.originalWidth = element.current.clientWidth;
				if (!state.originalHeight || forcedImageHeight > 0) state.originalHeight = element.current.clientHeight;
				element.current.style.display = initialDisplay;
			}
		}
	}, [forcedImageHeight, forcedImageWidth]);

	const calculatePositionProperties = useCallback(() => {
		let horizonOffset = propsHorizonOffset;
		let separation = propsSeparation;
		for (let i = 1; i <= flankingItems + 2; i++) {
			if (i > 1) {
				horizonOffset *= horizonOffsetMultiplier;
				separation *= separationMultiplier;
			}

			const { distance, offset, opacity } = state.current.calculations[i - 1];
			state.current.calculations[i] = {
				distance: distance + separation,
				offset: offset + horizonOffset,
				opacity: opacity * opacityMultiplier
			};
		}

		state.current.calculations[flankingItems + 1] = {
			distance: 0,
			offset: 0,
			opacity: 0
		};
	}, [flankingItems, horizonOffsetMultiplier, opacityMultiplier, propsHorizonOffset, propsSeparation, separationMultiplier]);

	const setupCarousel = useCallback(() => {
		horizon.current ||= state.current.containerDimensions[Number(!isVertical.current)] / 2;
		const { entries } = getDataFromExposedFunctions(linkedItemsContext);

		for (const [key, item] of entries) {
			const itemState = elementsState.current[key];
			let left, top;
			if (isVertical.current) {
				left = horizon.current - Number(itemState.originalWidth) / 2;
				top = state.current.containerDimensions[1] / 2 - Number(itemState.originalHeight) / 2;
			} else {
				left = state.current.containerDimensions[0] / 2 - Number(itemState.originalWidth) / 2;
				top = horizon.current - Number(itemState.originalHeight) / 2;
			}

			item.styles = {
				...item.styles,
				left: `${String(left)}px`,
				top: `${String(top)}px`,
				visibility: "visible",
				position: "absolute",
				zIndex: 0,
				opacity: 0,
				display: ""
			};
		}

		linkedItemsContext.current?.updateState(Object.fromEntries(entries));
	}, [isVertical]);

	const performCalculations = useCallback(
		(elementIndex: number, newPosition: number) => {
			const { keys } = getDataFromExposedFunctions(linkedItemsContext);
			const itemState = elementsState.current[keys[elementIndex]];

			const newDistanceFromCenter = Math.abs(newPosition);
			const calculations =
				newDistanceFromCenter < flankingItems + 1
					? state.current.calculations[newDistanceFromCenter]
					: state.current.calculations[flankingItems + 1];
			const distanceFactor = sizeMultiplier ** newDistanceFromCenter;
			const newWidth = distanceFactor * Number(itemState.originalWidth);
			const newHeight = distanceFactor * Number(itemState.originalHeight);
			const newDistance = newPosition < 0 ? -calculations.distance : calculations.distance;

			const center = state.current.containerDimensions[Number(isVertical.current)] / 2;
			let top: number, left: number;
			if (isVertical.current) {
				left = horizon.current - calculations.offset - newWidth / 2;
				top = center + newDistance - newHeight / 2;
			} else {
				left = center + newDistance - newWidth / 2;
				top = horizon.current - calculations.offset - newHeight / 2;
			}

			itemState.width = newWidth;
			itemState.height = newHeight;
			itemState.top = top;
			itemState.left = left;
			itemState.oldPosition ??= 0;
			itemState.depth = flankingItems + 2 - newDistanceFromCenter;
			itemState.opacity = newPosition ? calculations.opacity : 1;
		},
		[flankingItems, sizeMultiplier]
	);

	const { setupStarterRotation, rotateCarousel } = useMemo(() => {
		const rotateCarousel = () => {
			if (state.current.currentlyMoving) return;
			state.current.currentlyMoving = true;
			state.current.itemsAnimating = 0;
			state.current.carouselRotationsLeft++;
			isStateCurrentlyMoving.current = new Promise((resolve) => {
				resolveStateCurrentlyMoving.current = resolve;
			});

			getDataFromExposedFunctions(linkedItemsContext).keys.forEach((key, i) => {
				const currentPosition = elementsState.current[key].currentPosition ?? NaN;
				let newPosition = currentPosition + -Number(state.current.currentDirection);

				if (Math.abs(newPosition) > state.current[newPosition > 0 ? "rightItemsCount" : "leftItemsCount"]) {
					newPosition = -currentPosition;
					if (state.current.totalItems % 2 === 0) newPosition++;
				}

				moveItem(i, newPosition);
			});
		};

		const itemAnimationComplete = (elementIndex: number, newPosition: number) => {
			const { keys } = getDataFromExposedFunctions(linkedItemsContext);
			const itemState = elementsState.current[keys[elementIndex]];
			state.current.itemsAnimating--;
			itemState.currentPosition = newPosition;
			if (newPosition === 0) {
				state.current.currentCenterItem = elementIndex;
				setCurrentItem(state.current.currentCenterItem);
			}

			if (state.current.itemsAnimating) return;
			state.current.currentlyMoving = false;

			if (--state.current.carouselRotationsLeft <= 0) {
				if (!state.current.performingSetup) {
					movingToCenter?.();
					movedToCenter?.();
				} else state.current.performingSetup = false;
			}

			if (isStateCurrentlyMoving.current && resolveStateCurrentlyMoving.current) {
				resolveStateCurrentlyMoving.current();
				resolveStateCurrentlyMoving.current = isStateCurrentlyMoving.current = undefined;
			}
		};

		const moveItem = (elementIndex: number, newPosition: number) => {
			linkedItemsContext.current?.updateState((linkedItemsContextsState) => {
				const keys = Object.keys(linkedItemsContextsState);
				const entries = Object.entries(linkedItemsContextsState).map(([k, v]): [string, LinkedReactItem] => [k, { ...v }]);

				const item = entries[elementIndex][1];
				const itemState = elementsState.current[keys[elementIndex]];

				const assignToItem = () => {
					item.styles = {
						...item.styles,
						left: `${String(itemState.left)}px`,
						width: `${String(itemState.width)}px`,
						height: `${String(itemState.height)}px`,
						top: `${String(itemState.top)}px`,
						opacity: String(itemState.opacity)
					};
				};

				if (Math.abs(newPosition) <= flankingItems + 1) {
					performCalculations(elementIndex, newPosition);
					state.current.itemsAnimating++;

					item.styles = {
						...item.styles,
						zIndex: itemState.depth ?? ""
					};
					
					assignToItem();
					if (newPosition === 0) {
						const timeout = window.setTimeout(() => {
							setCurrentItem(elementIndex);
						}, 1);
						timeouts.current?.push(timeout);
					}

					const timeout = window.setTimeout(() => {
						itemAnimationComplete(elementIndex, newPosition);
					}, animationLength);
					timeouts.current?.push(timeout);
				} else {
					itemState.currentPosition = newPosition;
					if (!itemState.oldPosition) {
						performCalculations(elementIndex, newPosition);
						assignToItem();
					}
				}

				return Object.fromEntries(entries);
			});
		};

		const setupStarterRotation = () => {
			const { entries } = getDataFromExposedFunctions(linkedItemsContext);
			startingItem.current ||= Math.round(state.current.totalItems / 2);
			state.current.rightItemsCount = Math.ceil((state.current.totalItems - 1) / 2);
			state.current.leftItemsCount = Math.floor((state.current.totalItems - 1) / 2);
			state.current.carouselRotationsLeft = 1;

			let itemIndex = startingItem.current - 1;
			const moveToIndex = (pos: number) => {
				entries[itemIndex][1].styles = {
					...entries[itemIndex][1].styles,
					opacity: 1
				};

				moveItem(itemIndex, pos);
			};
			moveToIndex(0);

			for (let pos = 1; pos <= state.current.rightItemsCount; pos++) {
				itemIndex < state.current.totalItems - 1 ? itemIndex++ : (itemIndex = 0);
				moveToIndex(pos);
			}
			itemIndex = startingItem.current - 1;
			for (let pos = -1; pos >= -state.current.leftItemsCount; pos--) {
				itemIndex > 0 ? itemIndex-- : (itemIndex = state.current.totalItems - 1);
				moveToIndex(pos);
			}
		};

		return { setupStarterRotation, rotateCarousel };
	}, [animationLength, flankingItems, movedToCenter, movingToCenter, performCalculations]);

	const moveOnce = useCallback(
		(direction: CarouselDirection) => {
			if (state.current.currentlyMoving) return;
			if (direction === CarouselDirection.BACKWARDS && state.current.currentCenterItem !== undefined) {
				movingFromCenter?.(state.current.currentCenterItem - 1 < 0 ? undefined : state.current.currentCenterItem - 1);
			} else if (direction === CarouselDirection.FORWARDS && state.current.currentCenterItem !== undefined) {
				movingFromCenter?.(
					state.current.currentCenterItem + 1 > state.current.totalItems ? undefined : state.current.currentCenterItem + 1
				);
			} else movingFromCenter?.(state.current.currentCenterItem);

			state.current.currentDirection = direction;
		},
		[movingFromCenter]
	);

	const previousSlide = useCallback(() => {
		moveOnce(CarouselDirection.BACKWARDS);
		rotateCarousel();
	}, [moveOnce, rotateCarousel]);

	const switchOrientation = useCallback(() => {
		if (!allowSwitchingOrientation) return;
		isVertical.current = !isVertical.current;
		state.current.currentDirection = CarouselDirection.STILL;
		rotateCarousel();
	}, [allowSwitchingOrientation, rotateCarousel]);

	const nextSlide = useCallback(() => {
		moveOnce(CarouselDirection.FORWARDS);
		rotateCarousel();
	}, [moveOnce, rotateCarousel]);

	const initCarousel = useCallback(() => {
		if (!parent.current) return;
		setInitializing(PerspectiveCarouselState.INITIALIZING);
		state.current = resetInternalState();

		const { keys } = getDataFromExposedFunctions(linkedItemsContext);
		for (const key of keys) {
			if (typeof elementsState.current[key] === "undefined") elementsState.current[key] = {};
		}

		initializeCarouselData();
		forceImageDimensionsIfEnabled();
		setInitializing(PerspectiveCarouselState.AWAITING_LAYOUT_EFFECT);
	}, [forceImageDimensionsIfEnabled, initializeCarouselData]);

	const { abortTimeout } = useAutoplay({ autoplay, nextSlide, previousSlide });
	const { realCurrentItem, childrenLength, getCurrentItem } = getCurrentItemCallback({ children, currentItem });

	const navigateByDifference = useCallback(
		async (difference: number) => {
			isNavigatingByToggles.current = true;
			const direction = Math.sign(difference);
			if (direction === 1 || direction === -1) {
				state.current.currentDirection = direction;
			} else {
				state.current.currentDirection = CarouselDirection.STILL;
				return;
			}

			for (let i = 0; i < Math.abs(difference); i++) {
				rotateCarousel();
				await isStateCurrentlyMoving.current;
				abortTimeout();
			}
		},
		[abortTimeout, rotateCarousel]
	);

	useLayoutEffect(() => {
		if (isInitializing !== PerspectiveCarouselState.AWAITING_LAYOUT_EFFECT) return;
		setOriginalItemDimensions();
		calculatePositionProperties();
		setupCarousel();
		setupStarterRotation();
		setInitializing(PerspectiveCarouselState.FINISHED);

		const timeoutsRef = timeouts.current;
		return () => {
			const isInitializingCurrent: number = isInitializing;
			const awaitingLayoutEffect: number = PerspectiveCarouselState.AWAITING_LAYOUT_EFFECT;
			if (isInitializingCurrent === awaitingLayoutEffect) return;
			timeoutsRef?.forEach(window.clearTimeout);
			timeouts.current = [];
		};
	}, [calculatePositionProperties, isInitializing, setOriginalItemDimensions, setupCarousel, setupStarterRotation]);

	useEffect(() => {
		window.addEventListener("resize", initCarousel);

		return () => {
			window.removeEventListener("resize", initCarousel);
		};
	}, [initCarousel]);

	return (
		<ContextLinkedItems ref={linkedItemsContext} innerChildren={children} onAllElementsLoaded={initCarousel}>
			<div className={`${styles.wrap} ${className ?? ""}`}>
				<ul className={styles.images} style={imageStyles} ref={parent}>
					{children}
				</ul>
				{(allowSwitchingOrientation || showArrows || showToggles) && (
					<div className={styles["carousel-controls"]}>
						{(allowSwitchingOrientation || showArrows) && (
							<div className={carouselControlsStyles["carousel-controls"]}>
								{showArrows && (
									<button
										className={carouselControlsStyles["carousel-controls__previous-button"]}
										onClick={() => {
											abortTimeout();
											previousSlide();
										}}
									></button>
								)}
								{allowSwitchingOrientation && (
									<button
										className={carouselControlsStyles["carousel-controls__perspective-button"]}
										onClick={() => {
											abortTimeout();
											switchOrientation();
										}}
									>
										Switch
									</button>
								)}
								{showArrows && (
									<button
										className={carouselControlsStyles["carousel-controls__next-button"]}
										onClick={() => {
											abortTimeout();
											nextSlide();
										}}
									></button>
								)}
							</div>
						)}
						{showToggles && (
							<ul className={carouselControlsStyles["carousel-controls__toggles"]}>
								{Array.from({ length: childrenLength }, (_, i) => (
									<li
										key={i}
										className={`${carouselControlsStyles["carousel-controls__toggle"]} ${i === realCurrentItem ? carouselControlsStyles["carousel-controls__toggle--active"] : ""}`}
										onClick={() => {
											if (isNavigatingByToggles.current) return;
											abortTimeout();
											const difference = (getCurrentItem(i) % childrenLength) - (currentItem % childrenLength);
											navigateByDifference(difference)
												.catch((e: unknown) => {
													console.log(e);
												})
												.finally(() => {
													isNavigatingByToggles.current = false;
												});
										}}
									></li>
								))}
							</ul>
						)}
					</div>
				)}
			</div>
		</ContextLinkedItems>
	);
};

// vue/src/components/perspective-carousel/PerspectiveCarousel.vue
<template>
  <div class="wrap">
    <ul
      ref="parent"
      class="images"
      :style="imagesStyles"
    >
      <slot />
    </ul>
    <div class="root-carousel-controls">
      <div
        v-if="showArrows || allowSwitchingOrientation"
        class="carousel-controls"
      >
        <button
          v-if="showArrows"
          class="carousel-controls__previous-button"
          @click="onPreviousSlide"
        />
        <button
          v-if="allowSwitchingOrientation"
          class="carousel-controls__perspective-button"
          @click="switchOrientation"
        >
          Switch
        </button>
        <button
          v-if="showArrows"
          class="carousel-controls__next-button"
          @click="onNextSlide"
        />
      </div>
      <ul
        v-if="showToggles"
        class="carousel-controls__toggles"
      >
        <li
          v-for="i in currentItemSettings.childrenLength"
          :key="i"
          class="carousel-controls__toggle"
          :class="{ 'carousel-controls__toggle--active': currentItemSettings.realCurrentItem === i - 1 }"
          @click="() => {
            if (isNavigatingByToggles) return;
            abortTimeout();
            const difference = (currentItemSettings.getCurrentItem(i - 1) % currentItemSettings.childrenLength) - (currentItem % currentItemSettings.childrenLength);
            navigateByDifference(difference).catch((e: unknown) => {
              console.log(e);
            }).finally(() => {
              isNavigatingByToggles = false;
            })
          }"
        />
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { PerspectiveCarouselConfiguration, PerspectiveCarouselItemState, resetInternalState } from "shared/component/perspectiveCarousel";
import { CSSProperties, computed, onMounted, onUnmounted, ref, nextTick } from "vue";
import { useInjectedLinkedItems } from "../../interfaces/hooks/useLinkedItem";
import { CarouselDirection } from "shared/interfaces/carousel";
import { getCurrentItemInfo } from "shared/utils/carousel";
import { useAutoplay } from "../../interfaces/hooks/useAutoplay";

const props = withDefaults(defineProps<Partial<PerspectiveCarouselConfiguration>>(), {
	imageSize: "300px",
	margin: "250px auto",
	startingItem: 1,
	separation: 175,
	separationMultiplier: 0.6,
	horizonOffset: 0,
	horizonOffsetMultiplier: 1,
	sizeMultiplier: 0.7,
	opacityMultiplier: 0.87,
	horizon: 0,
	flankingItems: 3,
	isVertical: false,
	forcedImageWidth: 0,
	forcedImageHeight: 0,
	animationLength: 300,
	allowSwitchingOrientation: false,
	showArrows: true,
	showToggles: false
});
const imagesStyles = computed<CSSProperties>(() => ({
	margin: props.margin,
	height: props.imageSize
}));

const emit = defineEmits<{
	(e: "movingToCenter"): void;
	(e: "movingFromCenter", elementIndex?: number): void;
}>();

const state = ref(resetInternalState<number>());
const elements = useInjectedLinkedItems();
const elementsAccessors = computed(() => ({
	keys: Object.keys(elements),
	values: Object.values(elements),
	entries: Object.entries(elements)
}));

const parent = ref<HTMLElement | null>(null);
const elementsState = ref<Record<string, Partial<PerspectiveCarouselItemState>>>({});
const horizon = ref(props.horizon);
const startingItem = ref(props.startingItem);
const isVertical = ref(props.isVertical);
const currentItem = ref(0);
const isStateCurrentlyMoving = ref<Promise<void>>();
const resolveStateCurrentlyMoving = ref<() => void>();
const isNavigatingByToggles = ref(false);	
const currentItemSettings = computed(() => {
  return getCurrentItemInfo({ childrenLength: Object.keys(elements).length, currentItem: currentItem.value });
});

const calculatePositionProperties = async () => {
	let horizonOffset = props.horizonOffset;
	let separation = props.separation;
	for (let i = 1; i <= props.flankingItems + 2; i++) {
		if (i > 1) {
			horizonOffset *= props.horizonOffsetMultiplier;
			separation *= props.separationMultiplier;
		}

		const { distance, offset, opacity } = state.value.calculations[i - 1];
		state.value.calculations[i] = {
			distance: distance + separation,
			offset: offset + horizonOffset,
			opacity: opacity * props.opacityMultiplier
		};
		await nextTick();
	}

	state.value.calculations[props.flankingItems + 1] = {
		distance: 0,
		offset: 0,
		opacity: 0
	};
};

const performCalculations = (elementIndex: number, newPosition: number) => {
	const itemState = elementsState.value[elementsAccessors.value.keys[elementIndex]];

	const newDistanceFromCenter = Math.abs(newPosition);
	const calculations =
		newDistanceFromCenter < props.flankingItems + 1
			? state.value.calculations[newDistanceFromCenter]
			: state.value.calculations[props.flankingItems + 1];
	const distanceFactor = props.sizeMultiplier ** newDistanceFromCenter;
	const newWidth = distanceFactor * Number(itemState.originalWidth);
	const newHeight = distanceFactor * Number(itemState.originalHeight);
	const newDistance = newPosition < 0 ? -calculations.distance : calculations.distance;

	const center = state.value.containerDimensions[Number(isVertical.value)] / 2;
	let top: number, left: number;
	if (isVertical.value) {
		left = horizon.value - calculations.offset - newWidth / 2;
		top = center + newDistance - newHeight / 2;
	} else {
		left = center + newDistance - newWidth / 2;
		top = horizon.value - calculations.offset - newHeight / 2;
	}

	itemState.width = newWidth;
	itemState.height = newHeight;
	itemState.top = top;
	itemState.left = left;
	itemState.oldPosition ??= 0;
	itemState.depth = props.flankingItems + 2 - newDistanceFromCenter;
	itemState.opacity = newPosition ? calculations.opacity : 1;
};

const rotateCarousel = async () => {
	if (state.value.currentlyMoving) return;
	state.value.currentlyMoving = true;
	state.value.itemsAnimating = 0;
	state.value.carouselRotationsLeft++;
	isStateCurrentlyMoving.value = new Promise((resolve) => {
		resolveStateCurrentlyMoving.value = resolve;
	});
	await nextTick();

	elementsAccessors.value.keys.forEach((key, i) => {
		const currentPosition = elementsState.value[key].currentPosition ?? NaN;
		let newPosition = currentPosition + -Number(state.value.currentDirection);
		if (Math.abs(newPosition) > state.value[newPosition > 0 ? "rightItemsCount" : "leftItemsCount"]) {
			newPosition = -currentPosition;
			if (state.value.totalItems % 2 === 0) newPosition++;
		}

		moveItem(i, newPosition).catch((e: unknown) => { 
			console.trace(e);
		});
	});
};

const itemAnimationComplete = async (elementIndex: number, newPosition: number) => {
	const itemState = elementsState.value[elementsAccessors.value.keys[elementIndex]];

	state.value.itemsAnimating--;
	itemState.currentPosition = newPosition;
	if (newPosition === 0) {
		state.value.currentCenterItem = elementIndex;
		currentItem.value = state.value.currentCenterItem;
	}

	if (state.value.itemsAnimating) return;
	state.value.currentlyMoving = false;

	await nextTick();
	if (--state.value.carouselRotationsLeft <= 0) {
		if (!state.value.performingSetup) {
			emit("movingToCenter");
		} else state.value.performingSetup = false;
	} else await rotateCarousel();

	if (isStateCurrentlyMoving.value && resolveStateCurrentlyMoving.value) {
		resolveStateCurrentlyMoving.value();
		resolveStateCurrentlyMoving.value = isStateCurrentlyMoving.value = undefined;
	}
};

const moveItem = async (elementIndex: number, newPosition: number) => {
	const item = elementsAccessors.value.values[elementIndex];
	const itemState = elementsState.value[elementsAccessors.value.keys[elementIndex]];

	const assignToItem = () => {
		item.styles = {
			...item.styles,
			left: `${String(itemState.left)}px`,
			width: `${String(itemState.width)}px`,
			height: `${String(itemState.height)}px`,
			top: `${String(itemState.top)}px`,
			opacity: String(itemState.opacity)
		};
	};

	if (Math.abs(newPosition) <= props.flankingItems + 1) {
		performCalculations(elementIndex, newPosition);
		state.value.itemsAnimating++;
		await nextTick();

		item.styles = {
			...item.styles,
			zIndex: itemState.depth ?? ""
		};
		
		assignToItem();
		if (newPosition === 0) {
			window.setTimeout(() => {
				currentItem.value = elementIndex;
			}, 1);
		}
		
		setTimeout(() => {
			itemAnimationComplete(elementIndex, newPosition).catch((e: unknown) => {
				console.trace(e);
			});
		}, props.animationLength);
	} else {
		itemState.currentPosition = newPosition;
		if (!itemState.oldPosition) {
			await nextTick();
			performCalculations(elementIndex, newPosition);
			assignToItem();
		}
	}
};

const moveOnce = (direction: CarouselDirection) => {
	if (state.value.currentlyMoving) return;
	if (direction === CarouselDirection.BACKWARDS && state.value.currentCenterItem !== undefined) {
		emit("movingFromCenter", state.value.currentCenterItem - 1 < 0 ? undefined : state.value.currentCenterItem - 1);
	} else if (direction === CarouselDirection.FORWARDS && state.value.currentCenterItem !== undefined) {
		emit("movingFromCenter", state.value.currentCenterItem + 1 > state.value.totalItems ? undefined : state.value.currentCenterItem + 1);
	} else emit("movingFromCenter", state.value.currentCenterItem);

	state.value.currentDirection = direction;
};

const previousSlide = () => {
	moveOnce(CarouselDirection.BACKWARDS);
	rotateCarousel().catch((e: unknown) => { 
		console.trace(e);
	});
};

const switchOrientation = () => {
	if (!props.allowSwitchingOrientation) return;
	isVertical.value = !isVertical.value;
	state.value.currentDirection = CarouselDirection.STILL;
	rotateCarousel().catch((e: unknown) => { 
		console.trace(e);
	});
};

const nextSlide = () => {
	moveOnce(CarouselDirection.FORWARDS);
	rotateCarousel().catch((e: unknown) => { 
		console.trace(e);
	});
};

const { abortTimeout } = useAutoplay({ autoplay: props.autoplay, nextSlide, previousSlide });
const navigateByDifference = async (difference: number) => {
	isNavigatingByToggles.value = true;
	const direction = Math.sign(difference);
	if (direction === 1 || direction === -1) {
		state.value.currentDirection = direction;
	} else {
		state.value.currentDirection = CarouselDirection.STILL;
		return;
	}

	for (let i = 0; i < Math.abs(difference); i++) {
		await rotateCarousel();
		await isStateCurrentlyMoving.value;
		abortTimeout();
	}
};

const onNextSlide = () => {
  abortTimeout();
  nextSlide();
};

const onPreviousSlide = () => {
  abortTimeout();
  previousSlide();
};

const initializeCarouselData = (parent: HTMLElement) => {
	const parentStyle = window.getComputedStyle(parent);
	state.value.totalItems = elementsAccessors.value.values.length;
	state.value.containerDimensions = [parseInt(parentStyle.width, 10), parseInt(parentStyle.height, 10)];
};

const forceImageDimensionsIfEnabled = async () => {
	for (const image of elementsAccessors.value.values) {
		image.styles = { display: "none" };
		if (!props.forcedImageWidth || !props.forcedImageHeight) continue;
		image.styles = {
			...image.styles,
			width: `${String(props.forcedImageWidth)}px`,
			height: `${String(props.forcedImageHeight)}px`
		};
	}

	await nextTick();
};

const setOriginalItemDimensions = async () => {
	for (const [key, image] of elementsAccessors.value.entries) {
		const state = elementsState.value[key];
		if ((!state.originalWidth && !state.originalHeight) || props.forcedImageWidth > 0 || props.forcedImageHeight > 0) {
			image.styles = {
				...image.styles,
				display: ""
			};
			await nextTick();
			if (!state.originalWidth || props.forcedImageWidth > 0) state.originalWidth = image.element.clientWidth;
			if (!state.originalHeight || props.forcedImageHeight > 0) state.originalHeight = image.element.clientHeight;
			image.styles = {
				...image.styles,
				display: "none"
			};
		}
	}
};

const setupCarousel = async () => {
	if (horizon.value === 0) horizon.value = state.value.containerDimensions[Number(!isVertical.value)] / 2;
	await nextTick();

	for (const [key, item] of elementsAccessors.value.entries) {
		const itemState = elementsState.value[key];
		let left, top;
		if (isVertical.value) {
			left = horizon.value - Number(itemState.originalWidth) / 2;
			top = state.value.containerDimensions[1] / 2 - Number(itemState.originalHeight) / 2;
		} else {
			left = state.value.containerDimensions[0] / 2 - Number(itemState.originalWidth) / 2;
			top = horizon.value - Number(itemState.originalHeight) / 2;
		}

		item.styles = {
			...item.styles,
			left: `${String(left)}px`,
			top: `${String(top)}px`,
			visibility: "visible",
			position: "absolute",
			"z-index": 0,
			opacity: 0,
			display: ""
		};
	}

	await nextTick();
};

const setupStarterRotation = async () => {
	startingItem.value ||= Math.round(state.value.totalItems / 2);
	state.value.rightItemsCount = Math.ceil((state.value.totalItems - 1) / 2);
	state.value.leftItemsCount = Math.floor((state.value.totalItems - 1) / 2);
	state.value.carouselRotationsLeft = 1;
	await nextTick();

	let itemIndex = startingItem.value - 1;
	const moveToIndex = async (pos: number) => {
		elementsAccessors.value.values[itemIndex].styles = {
			...elementsAccessors.value.values[itemIndex].styles,
			opacity: 1
		};
		await moveItem(itemIndex, pos);
	};
	await moveToIndex(0);

	for (let pos = 1; pos <= state.value.rightItemsCount; pos++) {
		itemIndex < state.value.totalItems - 1 ? itemIndex++ : (itemIndex = 0);
		await moveToIndex(pos);
	}
	itemIndex = startingItem.value - 1;
	for (let pos = -1; pos >= -state.value.leftItemsCount; pos--) {
		itemIndex > 0 ? itemIndex-- : (itemIndex = state.value.totalItems - 1);
		await moveToIndex(pos);
	}
};

const initCarousel = () => {
	(async () => {
		if (!parent.value) return;
		state.value = resetInternalState();
		for (const key of elementsAccessors.value.keys) elementsState.value[key] ??= {};
		await nextTick();

		initializeCarouselData(parent.value);
		await forceImageDimensionsIfEnabled();
		await setOriginalItemDimensions();
		await calculatePositionProperties();
		await setupCarousel();
		await setupStarterRotation();
	})().catch((e: unknown) => {
		console.trace(e);
	});
};

onMounted(() => {
	initCarousel();
	window.addEventListener("resize", initCarousel);
});

onUnmounted(() => {
	window.removeEventListener("resize", initCarousel);
});
</script>

<style scoped src="../../interfaces/generic/carousel/carouselControlStyles.css"></style>
<style scoped>
.wrap {
	position: relative;
}

.images {
	width: 80%;
	padding: 0;
	margin: 0;
	list-style-type: none;
}

.root-carousel-controls {
	position: absolute;
	left: 40%;
	transform: translateX(-50%);
	bottom: -20%;
	z-index: 99;
}
</style>
