// react/src/components/rebuilding-text/RebuildingText.tsx
import React, { useCallback } from "react";
import { ModifyingTextConfiguration, TriggerTextAnimationCallback } from "shared/interfaces/selfModifyingText";
import { ModifyingTextContext, useSelfModifyingText } from "../../interfaces/hooks/useSelfModifyingText";
import { createRebuildingTextSteps } from "shared/component/rebuildingText";
import { GenericReactComponentProps } from "../../interfaces/generic/classNameFallthrough";

export const RebuildingText = ({
	repetitions = 1,
	interval = 2500,
	typingSpeed = 75,
	...props
}: ModifyingTextConfiguration & GenericReactComponentProps) => {
	const triggerTextAnimation = useCallback<TriggerTextAnimationCallback<ModifyingTextContext>>(
		({ context, fromText, toText }) => {
			const steps = createRebuildingTextSteps(fromText, toText);
			for (let i = 0; i < steps.length; i++) {
				setTimeout(() => {
					context.setCurrentTextValue(
						steps[i]
							.filter<string>((s): s is string => Boolean(s))
							.map((letter) => ({
								letter,
								classes: []
							}))
					);

					if (i === steps.length - 1) {
						setTimeout(() => {
							context.onInterval();
						}, interval);
					}
				}, typingSpeed * i);
			}
		},
		[interval, typingSpeed]
	);

	const currentTextValue = useSelfModifyingText({
		strings: props.strings,
		repetitions,
		interval,
		typingSpeed,
		triggerTextAnimation
	});

	return (
		<pre className={props.className}>
			{currentTextValue.map((letter, i) => (
				<span className={letter.classes.join("")} key={`${letter.letter}-${String(i)}`}>
					{letter.letter}
				</span>
			))}
		</pre>
	);
};

// lit/src/components/rebuilding-text/rebuildingText.ts
import { property } from "lit/decorators.js";
import { SelfModifyingText, TriggerTextParams } from "../../interfaces/generic/selfModifyingText";
import { createRebuildingTextSteps } from "shared/component/rebuildingText";

export class RebuildingTextComponent extends SelfModifyingText {
	@property({ type: Number })
	interval = 2500;
	@property({ type: Number })
	typingSpeed = 75;

	triggerTextAnimation({ context, fromText, toText }: TriggerTextParams) {
		const steps = createRebuildingTextSteps(fromText, toText);

		for (let i = 0; i < steps.length; i++) {
			setTimeout(() => {
				this._currentTextValue = steps[i].filter(Boolean).map((letter) => ({
					letter: String(letter),
					classes: []
				}));
				if (i !== steps.length - 1) return;

				setTimeout(() => {
					context.onInterval();
				}, this.interval);
			}, this.typingSpeed * i);
		}
	}
}
