// src/modules/vue-components/ciphering-text/CipheringText.vue
<template>
    <pre ref="element">
        <span v-for="letter in settings.currentTextValue.value" v-text="letter.letter" :class="letter.classes.join('')"></span>
    </pre>
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue';
import { ModifyingTextConfiguration } from 'src/modules/interfaces/generic/selfModifyingText/selfModifyingText';
import { useSelfModifyingText, splitTextAlgorithm } from 'src/modules/interfaces/generic/selfModifyingText/selfModifyingText.vue';

interface CipheringTextConfiguration extends ModifyingTextConfiguration {
    characters?: string[];
}

const props = defineProps<CipheringTextConfiguration>();
const element = ref<HTMLElement | null>(null);
const characters = computed(() => props.characters ?? ['!', '"', '#', '$', '%', '*', '0', '1', ':', ';', '?', '@', '[', ']', '\\', '~', "'", '/', '{', '}', '|', '&', '(', ')', '-', '<', '>']);
const settings = useSelfModifyingText({
    strings: props.strings,
    repetitions: props.repetitions ?? 1,
    interval: props.interval ?? 3000,
    typingSpeed: props.typingSpeed ?? 45,
    triggerTextAnimation,
    splitText
});

const cipherLetter = (properties: { newLetter?: string, delayed: boolean, i: number }) => {
    const { newLetter, delayed, i } = properties;
    const changeNumber = Math.round(Math.random() * ((delayed ? 44 : 14) - 6) + 6);
    let isDone = false, index = 0;
    const definedRandom = (Math.random() * 1000) + (delayed ? settings.settings.typingSpeed * i : 0), speed = 65;
    setTimeout(() => {
        while (index <= changeNumber) {
            (function (index) {
                setTimeout(() => {
                    let newValue: string | undefined;
                    if (!isDone) newValue = characters.value[Math.floor(Math.random() * characters.value.length)];
                    if (index >= changeNumber) {
                        isDone = true;
                        newValue = newLetter ?? "";
                    }

                    if (newValue !== undefined) settings.currentTextValue.value[i] = {
                        letter: newValue,
                        classes: isDone ? [] : ["active"]
                    };
                }, speed * index);
            })(index++);
        }
    }, definedRandom);

    return changeNumber * speed + speed;
};

function splitText(newString?: string) {
    if (newString) settings.currentTextValue.value = splitTextAlgorithm(settings.currentTextValue.value, newString);
}

function triggerTextAnimation(_: string, toText: string) {
    splitText(toText);
    const speeds: number[] = [];
    settings.currentTextValue.value.forEach((character, i) => {
        if (character.letter === toText[i]) return;
        speeds.push(cipherLetter({ newLetter: toText[i], i, delayed: element.value?.textContent?.length === 0 }));
    });

    setTimeout(() => {
        settings.currentTextValue.value = settings.currentTextValue.value.filter(v => Boolean(v.letter));
        settings.onInterval();
    }, Math.max(...speeds) + settings.settings.interval);
}
</script>

<style scoped>
pre {
    white-space: normal;
}
</style>

// lit/src/components/ciphering-text/cipheringText.ts
import { property } from "lit/decorators.js";
import { CipheringTextConfiguration } from "shared/component/cipheringText";
import { SelfModifyingText, SplitTextParams, TriggerTextParams } from "../../interfaces/generic/selfModifyingText";
import { splitTextAlgorithm } from "shared/interfaces/selfModifyingText";

export class CipheringTextComponent extends SelfModifyingText implements CipheringTextConfiguration {
	@property({ type: Number })
	interval = 3000;
	@property({ type: Number })
	typingSpeed = 45;
	@property({ type: Array })
	characters: string[] = [
		"!",
		'"',
		"#",
		"$",
		"%",
		"*",
		"0",
		"1",
		":",
		";",
		"?",
		"@",
		"[",
		"]",
		"\\",
		"~",
		"'",
		"/",
		"{",
		"}",
		"|",
		"&",
		"(",
		")",
		"-",
		"<",
		">"
	];

	splitText({ toText }: SplitTextParams) {
		if (toText) this._currentTextValue = splitTextAlgorithm(this._currentTextValue, toText);
	}

	cipherLetter(properties: { newLetter?: string; delayed: boolean; i: number }) {
		const { newLetter, delayed, i } = properties;
		const changeNumber = Math.round(Math.random() * ((delayed ? 44 : 14) - 6) + 6);
		let isDone = false,
			index = 0;
		const definedRandom = Math.random() * 1000 + (delayed ? this.typingSpeed * i : 0),
			speed = this.typingSpeed;
		setTimeout(() => {
			while (index <= changeNumber) {
				((index) => {
					setTimeout(() => {
						let newValue: string | undefined;
						if (!isDone) newValue = this.characters[Math.floor(Math.random() * this.characters.length)];
						if (index >= changeNumber) {
							isDone = true;
							newValue = newLetter ?? "";
						}

						if (newValue !== undefined) {
              this._currentTextValue[i] = {
								letter: newValue,
								classes: isDone ? [] : ["active"]
							};
            }

            this._currentTextValue = [...this._currentTextValue];
					}, speed * index);
				})(index++);
			}
		}, definedRandom);

		return changeNumber * speed + speed;
	}

	triggerTextAnimation({ context, toText }: TriggerTextParams) {
		this.splitText({ context, toText });
		const speeds: number[] = [];
		this._currentTextValue.forEach((character, i) => {
			if (character.letter === toText[i]) return;
			speeds.push(this.cipherLetter({ newLetter: toText[i], i, delayed: false }));
		});

    setTimeout(() => {
      this._currentTextValue = this._currentTextValue.filter(v => Boolean(v.letter));
      this.onInterval();
    }, Math.max(...speeds) + this.interval);
	}
}
