// src/modules/web-components/table-filtering/tableFiltering.ts
import { LitElement, css, html } from "lit";
import { customElement, property, query, queryAssignedElements, state } from "lit/decorators.js";
import { styleMap } from "lit/directives/style-map.js";
import { classMap } from "lit/directives/class-map.js";
import { assertNonUndefined } from "../../utils";
import { TableSelectInformation } from "src/modules/interfaces/component/table-filtering/types";

declare global {
	interface HTMLElementTagNameMap {
		"table-filtering-component": TableFilteringComponent;
	}
}

interface TabularData {
	headers: HTMLTableCellElement[];
	rows: HTMLTableCellElement[][];
	excludedCriteria: Array<string | null>[];
}

@customElement("table-filtering-component")
export class TableFilteringComponent extends LitElement {
	static styles = css`
		.wrap {
			position: relative;
		}

		.wrap-select {
			position: absolute;
		}

		.wrap-select__option {
			background-color: #333;
			height: inherit;
			cursor: pointer;
		}

		.wrap-select__option--crossed {
			text-decoration: line-through;
		}
	`;

	@property({
		type: Array,
		converter: {
			fromAttribute: (value) => (value ? value.split(",").map(Number) : []),
			toAttribute: (value: number[]) => value.join(",")
		}
	})
	filterableHeaders: number[] = [];

	@queryAssignedElements({ selector: "table" })
	_table!: HTMLTableElement[];
	@query(".wrap")
	_wrap!: HTMLDivElement;

	@state()
	protected tabularData: TabularData = { headers: [], rows: [], excludedCriteria: [] };
	@state()
	private openSelect?: TableSelectInformation;

	private clickListener!: EventListener;

	protected displaySelect(header: HTMLTableCellElement, index: number) {
		if (!this.filterableHeaders.includes(index + 1)) return;
		const headerRect = header.getBoundingClientRect(),
			wrap = this._wrap,
			wrapRect = wrap.getBoundingClientRect();
		const top = headerRect.top - wrapRect.top,
			left = headerRect.left - wrapRect.left;
		this.openSelect = {
			index,
			top,
			left,
			width: headerRect.width,
			height: headerRect.height,
			options: [...new Set(this.tabularData.rows.map((row) => row[index].textContent ?? ""))]
		};
	}

	protected firstUpdated() {
		const [table] = this._table;
		Object.assign(this.tabularData, {
			headers: Array.from(table.querySelectorAll("th")),
			rows: Array.from(table.querySelectorAll("tbody > tr")).map((row) =>
				Array.from(row.children).filter<HTMLTableCellElement>((e): e is HTMLTableCellElement => e instanceof HTMLTableCellElement)
			)
		});
		this.tabularData.excludedCriteria = Array.from({ length: this.tabularData.headers.length }, () => []);

		this._wrap.addEventListener(
			"click",
			(this.clickListener = (event) => {
				if (event.target instanceof HTMLTableCellElement && event.target.parentNode && event.target.tagName === "TH") {
					this.displaySelect(event.target, Array.from(event.target.parentNode.children).indexOf(event.target));
				} else if (!(event.target instanceof HTMLDivElement && event.target.classList.contains("wrap-select__option"))) {
					this.openSelect = undefined;
				} 
			})
		);
	}

	toggleCriterion(option: string) {
		assertNonUndefined(this.openSelect);
		const { index } = this.openSelect;
		const newExcludedCriteria = [...this.tabularData.excludedCriteria];
		if (newExcludedCriteria[index].includes(option)) {
			newExcludedCriteria[index].splice(newExcludedCriteria[index].indexOf(option), 1);
		} else newExcludedCriteria[index].push(option);

		this.tabularData = {
			...this.tabularData,
			excludedCriteria: newExcludedCriteria
		};
	}

	protected updated(_changedProperties: Map<PropertyKey, unknown>): void {
		if (!_changedProperties.has("tabularData")) return;
		for (const row of this.tabularData.rows) {
			const parent = row[0].parentElement;
			if (!parent) continue;
			if (row.some((element, i) => this.tabularData.excludedCriteria[i].includes(element.textContent ?? ""))) {
				parent.style.display = "none";
			} else parent.style.removeProperty("display");
		}
	}

	disconnectedCallback(): void {
		this._wrap.removeEventListener("click", this.clickListener);
		super.disconnectedCallback();
	}

	render() {
		return html`<div class="wrap">
			<slot></slot>
			${this.openSelect
				? html`<div
						class="wrap-select"
						style=${styleMap({
							top: `${this.openSelect.top}px`,
							left: `${this.openSelect.left}px`,
							width: `${this.openSelect.width}px`,
							height: `${this.openSelect.height}px`
						})}
				  >
						${this.openSelect.options.map((option) => {
							assertNonUndefined(this.openSelect);
							return html`<div
								class="wrap-select__option ${classMap({
									"wrap-select__option--crossed": this.tabularData.excludedCriteria[this.openSelect.index].includes(option)
								})}"
								@click="${() => { this.toggleCriterion(option); }}"
							>
								${option}
							</div>`;
						})}
				  </div>`
				: ""}
		</div>`;
	}
}

// src/modules/vue-components/table-filtering/TableFiltering.vue
<template>
	<div class="wrap" ref="wrap">
		<slot></slot>
		<div
			class="wrap-select"
			v-if="openSelect"
			:style="{
				top: `${openSelect.top}px`,
				left: `${openSelect.left}px`,
				width: `${openSelect.width}px`,
				height: `${openSelect.height}px`
			}"
		>
			<div
				v-for="option in openSelect.options"
				class="wrap-select__option"
				:class="{
                    'wrap-select__option--crossed' :excludedCriteria[openSelect.index].includes(option)
                }"
				@click="() => toggleCriterion(option)"
				v-text="option"
			></div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { TableSelectInformation } from "src/modules/interfaces/component/table-filtering/types";
import { LinkedVueItem, useInjectedLinkedItems } from "src/modules/interfaces/generic/hooks/useLinkedItem.vue";
import { assertNonUndefined } from "src/modules/utils";
import { computed, onMounted, ref } from "vue";

const wrap = ref<HTMLElement | null>(null);
const elements = useInjectedLinkedItems();
const elementsAccessors = computed(() => {
	const headers: LinkedVueItem[] = [],
		rows: LinkedVueItem[] = [];
	for (const [key, value] of Object.entries(elements)) {
		if (key.startsWith("table-header-")) {
			headers.push(value);
		} else if (key.startsWith("table-row-")) rows.push(value);
	}

	return { headers, rows };
});

const openSelect = ref<TableSelectInformation | undefined>();
const excludedCriteria = ref<Array<string | null>[]>([]);

const toggleCriterion = (option: string) => {
    assertNonUndefined(openSelect.value);
    const index = openSelect.value.index;
    const newExcludedCriteria = [...excludedCriteria.value];
    if (newExcludedCriteria[index].includes(option)) {
		newExcludedCriteria[index].splice(newExcludedCriteria[index].indexOf(option), 1);
	} else newExcludedCriteria[index].push(option);

    excludedCriteria.value = newExcludedCriteria;
    updateExcludedRows();
};

const updateExcludedRows = () => {
    for (const row of elementsAccessors.value.rows) {
        if (Array.from(row.element.children).some((element, i) => excludedCriteria.value[i].includes(element.textContent ?? ""))) {
            row.styles = {
                display: "none"
            };
        } else {
            row.styles = {
                display: "revert"
            };
        }
    }
};

const onHeaderClicked = (index: number) => {
	if (!wrap.value) return;
	const headerRect = elementsAccessors.value.headers[index].element.getBoundingClientRect();
	const wrapRect = wrap.value.getBoundingClientRect();
	const top = headerRect.top - wrapRect.top,
		left = headerRect.left - wrapRect.left;

	openSelect.value = {
		index,
		top,
		left,
		width: headerRect.width,
		height: headerRect.height,
		options: [...new Set(elementsAccessors.value.rows.map(({ element }) => element.children[index].textContent ?? ""))]
	};
};

const closeSelect = () => {
    openSelect.value = undefined;
};

onMounted(() => {
    excludedCriteria.value =  Array.from({ length: elementsAccessors.value.headers.length }, () => []);
});

defineExpose({ onHeaderClicked, closeSelect });
</script>

<style scoped>
.wrap {
	position: relative;
}

.wrap-select {
	position: absolute;
}

.wrap-select__option {
	background-color: #333;
	height: inherit;
	cursor: pointer;
}

.wrap-select__option--crossed {
	text-decoration: line-through;
}
</style>
