// vue/src/components/image-comparator/ImageComparator.vue
<template>
    <ul class="wrap">
        <slot></slot>
        <div
            v-for="elementKey in Object.keys(elements).slice(1)"
            class="comparison-slider"
            :style="imageData[elementKey].style"
            @mousedown="(e) => onMouseStart(e, elementKey)"
            @pointerdown="(e) => onMouseStart(e, elementKey)"
        ></div>
    </ul>
</template>

<script setup lang="ts">
import { useInjectedLinkedItems } from '../../interfaces/hooks/useLinkedItem';
import { onMounted, onUnmounted, reactive, computed, CSSProperties } from 'vue';

interface ImageComparisonData {
    isClicked: boolean;
    offsetWidth: number;
    style: CSSProperties;
}

const elements = useInjectedLinkedItems();
const imageData = reactive<Record<string, ImageComparisonData>>({});
const clickedElement = computed(() => Object.keys(elements).find((key) => imageData[key].isClicked));

const slide = (elementKey: string, difference: number) => {
    const element = elements[elementKey];
    const imageComparisonData = imageData[elementKey];
    element.styles = {
        width: difference + "px"
    };
    imageComparisonData.style.left = difference + "px";
};

const onMouseStart = (event: Event, elementKey: string) => {
    event.preventDefault();
    imageData[elementKey].isClicked = true;
};

const onMouseMove = (event: MouseEvent | PointerEvent) => {
    if (!clickedElement.value) return;
    const { element, styles } = elements[clickedElement.value];
    styles.left = "0";
    let pos = event.pageX - element.getBoundingClientRect().left - window.scrollX;
    if (pos < 0) pos = 0;
    if (pos > imageData[clickedElement.value].offsetWidth) {
        pos = imageData[clickedElement.value].offsetWidth;
    }

    slide(clickedElement.value, pos);
};

const onMouseUp = () => {
    for (const key of Object.keys(imageData)) imageData[key].isClicked = false;
};

onMounted(() => {
    Object.entries(elements).forEach(([key, { element: { offsetWidth } }], index, arr) => {
        imageData[key] = {
            isClicked: false,
            offsetWidth,
            style: {}
        };
        slide(key, offsetWidth - (offsetWidth / (arr.length) * (index)));
    });
    window.addEventListener("mouseup", onMouseUp, { passive: true });
    window.addEventListener("pointerup", onMouseUp, { passive: true });
    window.addEventListener("mousemove", onMouseMove, { passive: true });
    window.addEventListener("pointermove", onMouseMove, { passive: true });
});

onUnmounted(() => {
    window.removeEventListener("mouseup", onMouseUp);
    window.removeEventListener("pointerup", onMouseUp);
    window.removeEventListener("mousemove", onMouseMove);
    window.removeEventListener("pointermove", onMouseMove);
});
</script>

<style scoped>
.wrap {
    position: relative;
    width: 100%;
    height: 100%;
    list-style-type: none;
    margin: 0;
    padding: 0;
}

.comparison-slider {
    position: absolute;
    top: 50%;
    transform: translate(-50%, -50%);
    z-index: 1;
    width: 40px;
    height: 40px;
    background-color: #333;
    border-radius: 50%;
    cursor: ew-resize;
}
</style>

// src/modules/web-components/image-comparator/imageComparator.ts
import { LitElement, css, html } from "lit";
import { customElement, queryAssignedElements, query } from "lit/decorators.js";

declare global {
  interface HTMLElementTagNameMap {
    "image-comparator-component": ImageComparatorComponent;
  }
}

@customElement("image-comparator-component")
export class ImageComparatorComponent extends LitElement {
  static styles = css`
    .wrap {
      position: relative;
      width: 100%;
      height: 100%;
    }

    .comparison-slider {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      z-index: 1;
      width: 40px;
      height: 40px;
      background-color: #333;
      border-radius: 50%;
      cursor: ew-resize;
    }
  `;

  @queryAssignedElements()
  _comparatorElements!: HTMLElement[];
  @query(".wrap")
  _wrapElement!: HTMLDivElement;

  private windowListeners: Array<(event: MouseEvent | PointerEvent) => void> = [];

  protected initializeImageComparator(index: number) {
    const elements = this._comparatorElements;
    const image = elements[index], { offsetWidth } = image;
    let clicked = false;
    const slider = document.createElement("div");
    slider.setAttribute("class", "comparison-slider");
    this._wrapElement.append(slider);
    slide(offsetWidth - (offsetWidth / (elements.length) * (index)));

    function slide(difference: number) {
      image.style.width = difference + "px";
      slider.style.left = image.offsetWidth - (slider.offsetWidth / 2) + "px";
    }

    const mouseStartListener = (event: Event) => {
      event.preventDefault();
      clicked = true;
    };
    slider.addEventListener("mousedown", mouseStartListener);
    slider.addEventListener("pointerdown", mouseStartListener);

    this.windowListeners.unshift(event => {
      if (!clicked) return false;
      image.style.left = "0";
      let pos = event.pageX - image.getBoundingClientRect().left - window.scrollX;
      if (pos < 0) pos = 0;
      if (pos > offsetWidth) pos = offsetWidth;
      slide(pos);
    });
    window.addEventListener("mousemove", this.windowListeners[0], { passive: true });
    window.addEventListener("pointermove", this.windowListeners[0], { passive: true });

    this.windowListeners.unshift(() => { clicked = false; });
    window.addEventListener("mouseup", this.windowListeners[0], { passive: true });
    window.addEventListener("pointerup", this.windowListeners[0], { passive: true });
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    for (const listener of this.windowListeners) {
      (["mousemove", "pointermove", "mouseup", "pointerup"] as const).forEach((listenerName) => {
        window.removeEventListener(listenerName, listener);
      });
    }
  }

  protected firstUpdated(): void {
    for (let i = 1; i < this._comparatorElements.length; i++) this.initializeImageComparator(i);
  }

  render() {
    return html`<div class="wrap">
      <slot></slot>
    </div>`;
  }
}
