// src/modules/interfaces/generic/carousel/CarouselItem.vue
<template>
    <li class="carousel-item" ref="item">
        <slot></slot>
    </li>
</template>

<script setup lang="ts">
import { uid } from 'src/modules/utils';
import { useLinkedItem } from '../hooks/useLinkedItem.vue';
import { ref } from 'vue';

const item = ref<HTMLElement | null>(null);
useLinkedItem(uid, item);
</script>

// react/src/interfaces/generic/CarouselItem.tsx
import React, { useRef } from "react";
import { useLinkedItem } from "../../../src/interfaces/hooks/useLinkedItem";
import { uid } from "shared/utils/utils";
import { WithChildren } from "react/src/utils/utils";
import { GenericReactComponentProps } from "./classNameFallthrough";

export const CarouselItem = (props: WithChildren<object> & GenericReactComponentProps) => {
    const item = useRef<HTMLLIElement | null>(null);
    const styleObject = useLinkedItem(uid, item);

    return <li ref={item} style={styleObject}>
        {props.children}
    </li>
};
