// react/src/components/tabs/Tabs.tsx
import React from "react";
import { TabsConfiguration, TabsContext } from "../../interfaces/component/tabs";

export const Tabs = (props: TabsConfiguration) => {
    return <TabsContext.Provider value={{ currentTab: props.currentTab }}>
        <div className={props.className}>
            {props.headerChildren}
            {props.tabsChildren}
        </div>
    </TabsContext.Provider>
};

// src/modules/vue-components/tabs/Tabs.vue
<template>
    <div>
        <slot name="headers"></slot>
        <slot name="tabs"></slot>
    </div>
</template>

<script setup lang="ts">
import { computed, provide } from 'vue';
import { TabsConfiguration } from '../../interfaces/component/tabs/types';

const props = defineProps<TabsConfiguration>();
const currentTab = computed(() => props.currentTab);

provide("activeTab", currentTab);
</script>
