// src/modules/vue-components/sticky-header/StickyHeader.vue
<template>
    <div ref="outerWrap">
        <slot></slot>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, reactive, CSSProperties, nextTick } from "vue";
import { generateThreshold } from "src/modules/interfaces/generic/intersectionObserved";
import { StickyHeaderMinimalConfiguration } from "src/modules/interfaces/component/sticky-header/types";
import { useInjectedLinkedItems } from "src/modules/interfaces/generic/hooks/useLinkedItem.vue";

const props = withDefaults(defineProps<Partial<StickyHeaderMinimalConfiguration>>(), {
	rootMargin: "0px",
	ratio: 0.25
});

const headerElements = useInjectedLinkedItems();

const outerWrap = ref<HTMLElement | null>(null);
const isFixed = ref(false);
const intersectionObserver = ref<IntersectionObserver | undefined>();

onMounted(() => {
    const wrap = headerElements["sticky-header"];
	if (!wrap || !outerWrap.value) return;

	const intersectionObserverInstance = new IntersectionObserver(
		async ([entry]) => {
			if (!outerWrap.value) return;

			if (entry.intersectionRatio <= props.ratio && !isFixed.value) {
				isFixed.value = true;
				const { top, left, width, height } = wrap.element.getBoundingClientRect();
                wrap.styles = {
                    ...wrap.styles,
                    position: "fixed",
                    top: `${top}px`,
                    left: `${left}px`,
                    width: `${width}px`,
                    height: `${height}px`,
                    zIndex: 9999
                };

				await nextTick();
				wrap.element.getBoundingClientRect();
				
                setTimeout(() => {
                    wrap.styles = {
                        ...wrap.styles,
                        top: 0,
                        left: 0,
                        right: 0,
                        width: "auto",
                        height: "auto"
                    };
                }, 1);
			} else if (entry.intersectionRatio > props.ratio && isFixed.value) {
				isFixed.value = false;
                wrap.styles = {
                    ...wrap.styles,
                    position: "static",
                    top: "0",
                    left: "0",
                    right: "0"
                };
			}
		},
		{
			rootMargin: props.rootMargin,
			threshold: generateThreshold()
		}
	);
	intersectionObserverInstance.observe(outerWrap.value);
	intersectionObserver.value = intersectionObserverInstance;
});

onUnmounted(() => {
	intersectionObserver.value?.disconnect();
});
</script>

// src/modules/web-components/sticky-header/stickyHeader.ts
import { LitElement, html } from "lit";
import { customElement, property, queryAssignedElements } from "lit/decorators.js";
import { StickyHeaderConfiguration } from "src/modules/interfaces/component/sticky-header/types";
import { generateThreshold } from "src/modules/interfaces/generic/intersectionObserved";

declare global {
	interface HTMLElementTagNameMap {
		"sticky-header-component": StickyHeaderComponent;
	}
}

@customElement("sticky-header-component")
export class StickyHeaderComponent extends LitElement implements StickyHeaderConfiguration {
	@property()
	rootMargin = "0px";
	@property({ type: Number })
	ratio = 0.25;
	@property()
	fixedClassName = "fixed";

	@queryAssignedElements({ flatten: true })
	_headers!: HTMLElement[];

	protected intersectionObserver?: IntersectionObserver;

	protected firstUpdated() {
		const header = this._headers[0];
		this.intersectionObserver = new IntersectionObserver(
			([entry]) => {
				if (entry.intersectionRatio <= this.ratio && !header.classList.contains(this.fixedClassName)) {
					header.classList.add(this.fixedClassName);
					const { top, left } = header.getBoundingClientRect();
					Object.assign(header.style, {
						position: "fixed",
						top: `${top}px`,
						left: `${left}px`
					});
					header.getBoundingClientRect();
					Object.assign(header.style, { top: "0", left: "0", right: "0" });
				} else if (entry.intersectionRatio > this.ratio && header.classList.contains(this.fixedClassName)) {
					header.classList.remove(this.fixedClassName);
					Object.assign(header.style, {
						position: "",
						top: "",
						left: "",
						right: ""
					});
				}
			},
			{
				rootMargin: this.rootMargin,
				threshold: generateThreshold()
			}
		);

		this.intersectionObserver.observe(this);
	}

	disconnectedCallback(): void {
		this.intersectionObserver?.disconnect();
		super.disconnectedCallback();
	}

	render() {
		return html`<slot></slot>`;
	}
}
