// vue/src/components/magnifier/Magnifier.vue
<template>
  <div class="magnifier">
    <div class="magnifier__image" @mousemove="onMouseMove" ref="image">
      <slot name="image"></slot>
    </div>
    <slot name="glass"></slot>
  </div>
</template>

<script setup lang="ts">
import { useInjectedLinkedItems } from "../../interfaces/hooks/useLinkedItem";
import { onMounted, ref } from "vue";
import { MagnifierConfiguration } from "shared/component/magnifier";

const props = withDefaults(defineProps<MagnifierConfiguration>(), {
  zoomScale: 2
});
const elements = useInjectedLinkedItems();
const image = ref<HTMLElement | null>(null);

const moveMagnifier = (x: number, y: number) => {
  if (!image.value) return;
  const glass = elements["magnifier-glass"];
  const width = glass.element.offsetWidth / 2,
    height = glass.element.offsetHeight / 2;
  if (x > image.value.offsetWidth) {
    x = image.value.offsetWidth;
  } else if (x < 0) x = 0;
  if (y > image.value.offsetHeight) {
    y = image.value.offsetHeight;
  } else if (y < 0) y = 0;

  glass.styles = {
    ...glass.styles,
    left: `${x - width}px`,
    top: `${y - height}px`,
    backgroundPosition: "-" + (x * props.zoomScale - width) + "px -" + (y * props.zoomScale - height) + "px"
  };
};

const onMouseMove = (event: MouseEvent) => {
  if (!image.value) return;
  event.preventDefault();
  const rect = image.value.getBoundingClientRect();
  moveMagnifier(event.pageX - rect.left - window.scrollX, event.pageY - rect.top - window.scrollY);
};

onMounted(() => {
  if (!image.value) return;
  const glass = elements["magnifier-glass"];
  glass.styles = {
    backgroundImage: `url("${props.imageSource}")`,
    backgroundSize: `${image.value.offsetWidth * props.zoomScale}px ${image.value.offsetHeight * props.zoomScale}px`
  };
});

defineExpose({ onMouseMove });
</script>

<style scoped>
.magnifier {
  position: relative;
}

.magnifier__image {
  width: 100%;
  height: 100%;
}

.magnifier__glass {
  position: absolute;
  top: -25px;
  left: -25px;
  width: 70px;
  height: 70px;
  border: 2px solid #222;
  border-radius: 50%;
  cursor: zoom-in;
  background-repeat: no-repeat;
}
</style>

// react/src/components/magnifier/Magnifier.tsx
import React, { forwardRef, useCallback, useImperativeHandle, useRef } from "react";
import { MagnifierConfiguration, MagnifierExposedFunctions } from "../../interfaces/component/magnifier";
import { ContextLinkedItems, ExposedContextFunctions } from "../../interfaces/hooks/useLinkedItem";
import { assertNonUndefined } from "shared/utils/utils";
import styles from "./Magnifier.module.css";

const Magnifier = forwardRef<MagnifierExposedFunctions, MagnifierConfiguration>(
	({ zoomScale = 2, ...props }: MagnifierConfiguration, ref) => {
		const linkedItemsContext = useRef<ExposedContextFunctions | null>(null);
		const image = useRef<HTMLDivElement>(null);

		const moveMagnifier = useCallback((x: number, y: number) => {
			if (!image.current) return;
			const glass = linkedItemsContext.current?.getState()?.["magnifier-glass"];
			assertNonUndefined(glass);
			const element = glass.element.current;
			assertNonUndefined(element);

			const width = element.offsetWidth / 2,
				height = element.offsetHeight / 2;
			if (x > image.current.offsetWidth) {
				x = image.current.offsetWidth;
			} else if (x < 0) x = 0;
			if (y > image.current.offsetHeight) {
				y = image.current.offsetHeight;
			} else if (y < 0) y = 0;

			linkedItemsContext.current?.updateState({
				"magnifier-glass": {
					...glass,
					styles: {
						...glass.styles,
						left: `${x - width}px`,
						top: `${y - height}px`,
						backgroundPosition: "-" + (x * zoomScale - width) + "px -" + (y * zoomScale - height) + "px"
					}
				}
			});
		}, [zoomScale]);

		const onMouseMove = useCallback((event: React.MouseEvent) => {
            if (!image.current) return;
            event.preventDefault();
            const rect = image.current.getBoundingClientRect();
            moveMagnifier(event.pageX - rect.left - window.scrollX, event.pageY - rect.top - window.scrollY);
        }, [moveMagnifier]);

		const setup = useCallback(() => {
			if (!image.current) return;
			linkedItemsContext.current?.updateState((elements) => {
				assertNonUndefined(image.current);
				return {
					"magnifier-glass": {
						...elements["magnifier-glass"],
						styles: {
							backgroundImage: `url("${props.imageSource}")`,
							backgroundSize: `${image.current.offsetWidth * zoomScale}px ${image.current.offsetHeight * zoomScale}px`
						}
					}
				};
			});
		}, [props.imageSource, zoomScale]);

		useImperativeHandle(ref, () => ({
			onMouseMove(event) {
				onMouseMove(event);
			}
		}));

		return (
			<ContextLinkedItems ref={linkedItemsContext} innerChildren={props.glassChildren} onAllElementsLoaded={setup}>
				<div className={`${styles.magnifier} ${props.className ?? ""}`}>
					<div className={styles.magnifier__image} onMouseMove={onMouseMove} ref={image}>
						{props.imageChildren}
					</div>
					{props.glassChildren}
				</div>
			</ContextLinkedItems>
		);
	}
);

export { Magnifier };
