// lit/src/components/accordion/accordion.ts
import { LitElement, css, html } from "lit";
import { property } from "lit/decorators.js";
import { AccordionListConfiguration } from "shared/component/accordion";
import { provide } from "@lit/context";
import { AccordionItemComponent } from "./accordionItem";
import { AccordionContext, accordionContext } from "./context";

export class AccordionComponent extends LitElement implements AccordionListConfiguration {
	static styles = css`
		.accordions {
			margin: 0;
			padding-left: 0;
			list-style-type: none;
		}
	`;

	@property({ type: Boolean })
	multiple = false;
	@provide({ context: accordionContext })
	_accordionContext: AccordionContext = {
		expandedIndex: "",
		setExpandedIndex: (newIndex: string) => {
			const newContext = { ...this._accordionContext };
			if (!this.multiple) {
				newContext.expandedIndex = newContext.expandedIndex === newIndex ? "" : newIndex;
			} else {
				if (typeof newContext.expandedIndex === "string") newContext.expandedIndex = [];
				if (newContext.expandedIndex.includes(newIndex)) {
					newContext.expandedIndex = newContext.expandedIndex.filter((id) => id !== newIndex);
				} else newContext.expandedIndex = [...newContext.expandedIndex, newIndex];
			}

			this._accordionContext = newContext;
		}
	};

	render() {
		return html`
			<ul class="accordions">
				<slot></slot>
			</ul>
		`;
	}
}

export { AccordionItemComponent };

// vue/src/components/accordion/AccordionComponent.vue
<template>
  <ul class="accordions">
    <slot />
  </ul>
</template>

<script setup lang="ts">
import { AccordionListConfiguration } from "shared/component/accordion";
import { provide, ref, computed } from "vue";
import { multiplePropKey, selectedIndexKey, expandedIndexKey } from "../../interfaces/component/accordion";

const props = defineProps<AccordionListConfiguration>();
const expandedIndex = ref<string[] | string>(props.multiple ? [] : "");
const selectedIndex = computed({
   get() {
    return expandedIndex.value;
   },
   set(value: unknown) {
    if (typeof value === "string" && typeof expandedIndex.value === "string") {
        expandedIndex.value = value;
    } else if (Array.isArray(value) && value.every(s => typeof s === "string")) expandedIndex.value = value;
   }
});

provide(multiplePropKey, props.multiple);
provide(selectedIndexKey, selectedIndex);
provide(expandedIndexKey, expandedIndex);
</script>

<style scoped>
.accordions {
    margin: 0;
    padding-left: 0;
    list-style-type: none;
}
</style>
