// src/modules/vue-components/perspective-carousel/PerspectiveCarousel.vue
<template>
	<div class="wrap">
		<ul class="images" :style="imagesStyles" ref="parent">
			<slot></slot>
		</ul>
		<div class="carousel-controls">
			<button class="carousel-controls__previous-button" @click="previousItem"></button>
			<button v-if="props.allowSwitchingOrientation" class="carousel-controls__perspective-button" @click="switchOrientation"></button>
			<button class="carousel-controls__next-button" @click="nextItem"></button>
		</div>
	</div>
</template>

<script setup lang="ts">
import {
	PerspectiveCarouselConfiguration,
	PerspectiveCarouselItemState,
	resetInternalState
} from "src/modules/interfaces/component/perspective-carousel/types";
import "../../interfaces/generic/carousel/carouselControlStyles.css";
import { CSSProperties, computed, onMounted, onUnmounted, ref, nextTick } from "vue";
import { useInjectedLinkedItems } from "src/modules/interfaces/generic/hooks/useLinkedItem.vue";
import { CarouselDirection } from "src/modules/interfaces/generic/carousel/carousel";

const props = withDefaults(defineProps<Partial<PerspectiveCarouselConfiguration>>(), {
	imageSize: "300px",
	margin: "250px auto",
	startingItem: 1,
	separation: 175,
	separationMultiplier: 0.6,
	horizonOffset: 0,
	horizonOffsetMultiplier: 1,
	sizeMultiplier: 0.7,
	opacityMultiplier: 0.87,
	horizon: 0,
	flankingItems: 3,
	isVertical: false,
	preloadImages: false,
	forcedImageWidth: 0,
	forcedImageHeight: 0,
	animationLength: 300,
	centralItemClassName: "active",
	allowSwitchingOrientation: false
});
const imagesStyles = computed<CSSProperties>(() => ({
	margin: props.margin,
	height: props.imageSize
}));

const emit = defineEmits<{
	(e: "movingToCenter"): void,
	(e: "movedToCenter"): void,
	(e: "movingFromCenter", elementIndex?: number): void
}>();

const state = ref(resetInternalState<number>());
const elements = useInjectedLinkedItems();
const elementsAccessors = computed(() => ({
	keys: Object.keys(elements),
	values: Object.values(elements),
	entries: Object.entries(elements)
}));
const parent = ref<HTMLElement | null>(null);
const elementsState = ref<Record<string, Partial<PerspectiveCarouselItemState>>>({});
const horizon = ref(props.horizon);
const startingItem = ref(props.startingItem);

const calculatePositionProperties = async () => {
	let horizonOffset = props.horizonOffset;
	let separation = props.separation;
	for (let i = 1; i <= props.flankingItems + 2; i++) {
		if (i > 1) {
			horizonOffset *= props.horizonOffsetMultiplier;
			separation *= props.separationMultiplier;
		}

		const { distance, offset, opacity } = state.value.calculations[i - 1];
		state.value.calculations[i] = {
			distance: distance + separation,
			offset: offset + horizonOffset,
			opacity: opacity * props.opacityMultiplier
		};
		await nextTick();
	}

	state.value.calculations[props.flankingItems + 1] = {
		distance: 0,
		offset: 0,
		opacity: 0
	};
};

const performCalculations = (elementIndex: number, newPosition: number) => {
	const itemState = elementsState.value[elementsAccessors.value.keys[elementIndex]];

	const newDistanceFromCenter = Math.abs(newPosition);
	const calculations =
		newDistanceFromCenter < props.flankingItems + 1
			? state.value.calculations[newDistanceFromCenter]
			: state.value.calculations[props.flankingItems + 1];
	const distanceFactor = props.sizeMultiplier ** newDistanceFromCenter;
	const newWidth = distanceFactor * Number(itemState.originalWidth);
	const newHeight = distanceFactor * Number(itemState.originalHeight);
	const newDistance = newPosition < 0 ? -calculations.distance : calculations.distance;

	const center = state.value.containerDimensions[Number(props.isVertical)] / 2;
	let top: number, left: number;
	if (props.isVertical) {
		left = horizon.value - calculations.offset - newWidth / 2;
		top = center + newDistance - newHeight / 2;
	} else {
		left = center + newDistance - newWidth / 2;
		top = horizon.value - calculations.offset - newHeight / 2;
	}

	itemState.width = newWidth;
	itemState.height = newHeight;
	itemState.top = top;
	itemState.left = left;
	itemState.oldPosition ??= 0;
	itemState.depth = props.flankingItems + 2 - newDistanceFromCenter;
	itemState.opacity = newPosition ? calculations.opacity : 1;
};

const rotateCarousel = async () => {
	if (state.value.currentlyMoving) return;
	// TODO allow removing central item class name
	state.value.currentlyMoving = true;
	state.value.itemsAnimating = 0;
	state.value.carouselRotationsLeft++;
	await nextTick();

	elementsAccessors.value.keys.forEach((key, i) => {
		const currentPosition = elementsState.value[key].currentPosition ?? NaN;
		let newPosition = currentPosition + -Number(state.value.currentDirection);
		if (Math.abs(newPosition) > state.value[newPosition > 0 ? "rightItemsCount" : "leftItemsCount"]) {
			newPosition = -currentPosition;
			if (state.value.totalItems % 2 === 0) newPosition++;
		}

		moveItem(i, newPosition);
	});
};

const itemAnimationComplete = async (elementIndex: number, newPosition: number) => {
	const itemState = elementsState.value[elementsAccessors.value.keys[elementIndex]];

	state.value.itemsAnimating--;
	itemState.currentPosition = newPosition;
	if (newPosition === 0) state.value.currentCenterItem = elementIndex;
	if (state.value.itemsAnimating) return;
	state.value.currentlyMoving = false;

	await nextTick();
	if (--state.value.carouselRotationsLeft <= 0) {
		// TODO allow adding central item class name
		if (!state.value.performingSetup) {
			emit("movingToCenter");
			emit("movedToCenter");
		} else state.value.performingSetup = false;
	} else await rotateCarousel();
};

const moveItem = async (elementIndex: number, newPosition: number) => {
	const item = elementsAccessors.value.values[elementIndex];
	const itemState = elementsState.value[elementsAccessors.value.keys[elementIndex]];

	const assignToItem = () => {
		console.log(itemState.width);
		item.styles = {
			...item.styles,
			left: `${itemState.left}px`,
			width: `${itemState.width}px`,
			height: `${itemState.height}px`,
			top: `${itemState.top}px`,
			opacity: String(itemState.opacity)
		};
	};

	if (Math.abs(newPosition) <= props.flankingItems + 1) {
		performCalculations(elementIndex, newPosition);
		state.value.itemsAnimating++;
		await nextTick();

		item.styles = {
			...item.styles,
			zIndex: itemState.depth ?? ""
		};
		assignToItem();
		setTimeout(() => {
			itemAnimationComplete(elementIndex, newPosition);
		}, props.animationLength);
	} else {
		itemState.currentPosition = newPosition;
		if (!itemState.oldPosition) {
			await nextTick();
			performCalculations(elementIndex, newPosition);
			assignToItem();
		}
	}
};

const moveOnce = (direction: CarouselDirection) => {
	if (state.value.currentlyMoving) return;
	// TODO allow to add central item class
	if (direction === CarouselDirection.BACKWARDS && state.value.currentCenterItem !== undefined) {
		emit("movingFromCenter", state.value.currentCenterItem - 1 < 0 ? undefined : state.value.currentCenterItem - 1);
	} else if (direction === CarouselDirection.FORWARDS && state.value.currentCenterItem !== undefined) {
		emit("movingFromCenter", state.value.currentCenterItem + 1 > state.value.totalItems ? undefined : state.value.currentCenterItem + 1);
	} else emit("movingFromCenter", state.value.currentCenterItem);

	state.value.currentDirection = direction;
};

const previousItem = () => {
	moveOnce(CarouselDirection.BACKWARDS);
	rotateCarousel();
};

const switchOrientation = () => {
	if (!props.allowSwitchingOrientation) return;
};

const nextItem = () => {
	moveOnce(CarouselDirection.FORWARDS);
	rotateCarousel();
};

const initializeCarouselData = (parent: HTMLElement) => {
	const parentStyle = window.getComputedStyle(parent);
	state.value.totalItems = elementsAccessors.value.values.length;
	state.value.containerDimensions = [parseInt(parentStyle.width, 10), parseInt(parentStyle.height, 10)];
};

const forceImageDimensionsIfEnabled = async () => {
	for (const image of elementsAccessors.value.values) {
		image.styles = { display: "none" };
		if (!props.forcedImageWidth || !props.forcedImageHeight) continue;
		image.styles = {
			...image.styles,
			width: `${props.forcedImageWidth}px`,
			height: `${props.forcedImageHeight}px`
		};
	}

	await nextTick();
};

const preload = async () => {
	if (!props.preloadImages) return;

	let loadedImages = 0;
	return new Promise<void>((resolve) => {
		for (const image of elementsAccessors.value.values) {
			image.element.addEventListener("load", () => {
				image.styles = {
					...image.styles,
					display: ""
				};
				if (++loadedImages === elementsAccessors.value.values.length) resolve();
			});
		}
	});
};

const setOriginalItemDimensions = async () => {
	for (const [key, image] of elementsAccessors.value.entries) {
		const state = elementsState.value[key];
		if ((!state.originalWidth && !state.originalHeight) || props.forcedImageWidth > 0 || props.forcedImageHeight > 0) {
			image.styles = {
				...image.styles,
				display: ""
			};
			await nextTick();
			if (!state.originalWidth || props.forcedImageWidth > 0) state.originalWidth = image.element.clientWidth;
			if (!state.originalHeight || props.forcedImageHeight > 0) state.originalHeight = image.element.clientHeight;
			image.styles = {
				...image.styles,
				display: "none"
			};
		}
	}
};

const setupCarousel = async () => {
	if (horizon.value === 0) horizon.value = state.value.containerDimensions[Number(!props.isVertical)] / 2;
	await nextTick();

	for (const [key, item] of elementsAccessors.value.entries) {
		const itemState = elementsState.value[key];
		let left, top;
		if (props.isVertical) {
			left = horizon.value - Number(itemState.originalWidth) / 2;
			top = state.value.containerDimensions[1] / 2 - Number(itemState.originalHeight) / 2;
		} else {
			left = state.value.containerDimensions[0] / 2 - Number(itemState.originalWidth) / 2;
			top = horizon.value - Number(itemState.originalHeight) / 2;
		}

		item.styles = {
			...item.styles,
			left: `${left}px`,
			top: `${top}px`,
			visibility: "visible",
			position: "absolute",
			"z-index": 0,
			opacity: 0,
			display: ""
		};
	}

	await nextTick();
};

const setupStarterRotation = async () => {
	startingItem.value ||= Math.round(state.value.totalItems / 2);
	state.value.rightItemsCount = Math.ceil((state.value.totalItems - 1) / 2);
	state.value.leftItemsCount = Math.floor((state.value.totalItems - 1) / 2);
	state.value.carouselRotationsLeft = 1;
	await nextTick();

	let itemIndex = startingItem.value - 1;
	const moveToIndex = async (pos: number) => {
		elementsAccessors.value.values[itemIndex].styles = {
			...elementsAccessors.value.values[itemIndex].styles,
			opacity: 1
		};
		await moveItem(itemIndex, pos);
	};
	await moveToIndex(0);

	for (let pos = 1; pos <= state.value.rightItemsCount; pos++) {
		itemIndex < state.value.totalItems - 1 ? itemIndex++ : (itemIndex = 0);
		await moveToIndex(pos);
	}
	itemIndex = startingItem.value - 1;
	for (let pos = -1; pos >= -state.value.leftItemsCount; pos--) {
		itemIndex > 0 ? itemIndex-- : (itemIndex = state.value.totalItems - 1);
		await moveToIndex(pos);
	}
};

const initCarousel = async () => {
	if (!parent.value) return;
	state.value = resetInternalState();
	for (const key of elementsAccessors.value.keys) elementsState.value[key] ??= {};
	await nextTick();

	initializeCarouselData(parent.value);
	await forceImageDimensionsIfEnabled();
	await preload();
	await setOriginalItemDimensions();
	await calculatePositionProperties();
	await setupCarousel();
	await setupStarterRotation();
};

onMounted(() => {
	initCarousel();
	window.addEventListener("resize", initCarousel);
});

onUnmounted(() => {
	window.removeEventListener("resize", initCarousel);
});
</script>

<style scoped>
.wrap {
	position: relative;
}

.images {
	width: 80%;
	padding: 0;
	margin: 0;
	list-style-type: none;
}

.carousel-controls {
	position: absolute;
	left: 40%;
	transform: translateX(-50%);
	bottom: -5%;
	z-index: 99;
}
</style>

// src/modules/web-components/perspective-carousel/perspectiveCarousel.ts
import { LitElement, html, css } from "lit";
import { customElement, property, queryAssignedElements, queryAsync, state } from "lit/decorators.js";
import { PerspectiveCarouselConfiguration, resetInternalState } from "../../interfaces/component/perspective-carousel/types";
import { styleMap } from "lit/directives/style-map.js";
import { assertDevOnly } from "../../utils";
import { CarouselDirection } from "src/modules/interfaces/generic/carousel/carousel";
import { carouselControlsStyles } from "src/modules/interfaces/generic/carousel/carousel.lit";

declare global {
	interface HTMLElementTagNameMap {
		"perspective-carousel-component": PerspectiveCarouselComponent;
	}
}

@customElement("perspective-carousel-component")
export class PerspectiveCarouselComponent extends LitElement implements PerspectiveCarouselConfiguration  {
	static styles = css`
		.wrap {
			position: relative;
		}

		.images {
			width: 80%;
		}

		${carouselControlsStyles}

		.carousel-controls {
			position: absolute;
			left: 40%;
			transform: translateX(-50%);
			bottom: -5%;
			z-index: 99;
		}
	`;

	@property()
	imageSize = "300px";
	@property()
	margin = "250px auto";
	@property({ type: Number })
	startingItem = 1;
	@property({ type: Number })
	separation = 175;
	@property({ type: Number })
	separationMultiplier = 0.6;
	@property({ type: Number })
	horizonOffset = 0;
	@property({ type: Number })
	horizonOffsetMultiplier = 1;
	@property({ type: Number })
	sizeMultiplier = 0.7;
	@property({ type: Number })
	opacityMultiplier = 0.87;
	@property({ type: Number })
	horizon = 0;
	@property({ type: Number })
	flankingItems = 3;
	@property({ type: Boolean })
	isVertical = false;
	@property({ type: Boolean })
	preloadImages = false;
	@property({ type: Number })
	forcedImageWidth = 0;
	@property({ type: Number })
	forcedImageHeight = 0;
	@property({ type: Number })
	animationLength = 300;
	@property()
	centralItemClassName = "active";
	@property({ type: Boolean })
	allowSwitchingOrientation = false;

	@queryAsync(".images")
	parent!: Promise<HTMLElement>;
	@queryAssignedElements({ flatten: true })
	images!: HTMLElement[];

	@state()
	_internalState = resetInternalState();

	private windowResizeListener!: EventListener;

	private initializeCarouselData(parent: HTMLElement) {
		const parentStyle = window.getComputedStyle(parent);
		this._internalState.totalItems = this.images.length;
		this._internalState.containerDimensions = [parseInt(parentStyle.width, 10), parseInt(parentStyle.height, 10)];
	}

	private forceImageDimensionIfEnabled() {
		this.images.forEach((el) => (el.style.display = "none"));
		if (!this.forcedImageWidth || !this.forcedImageHeight) return;
		this.images.forEach((image) => {
			image.style.width = `${this.forcedImageWidth}px`;
			image.style.height = `${this.forcedImageHeight}px`;
		});
	}

	private preload(callback: () => void) {
		if (!this.preloadImages) {
			callback();
			return;
		}

		const images = this.images;
		let loadedImages = 0;
		for (const image of images) {
			image.setAttribute("src", image.getAttribute("src") ?? "");
			image.addEventListener("load", () => {
				image.style.display = "";
				if (++loadedImages === images.length) callback();
			});
		}
	}

	private setOriginalItemDimensions() {
		this.images.forEach((element) => {
			if (!element.dataset.originalWidth || this.forcedImageWidth > 0) {
				element.style.display = "";
				element.dataset.originalWidth = String(element.clientWidth);
				element.style.display = "none";
			}
			if (!element.dataset.originalHeight || this.forcedImageHeight > 0) {
				element.style.display = "";
				element.dataset.originalHeight = String(element.clientHeight);
				element.style.display = "none";
			}
		});
	}

	private calculatePositionProperties() {
		let horizonOffset = this.horizonOffset;
		let separation = this.separation;
		for (let i = 1; i <= this.flankingItems + 2; i++) {
			if (i > 1) {
				horizonOffset *= this.horizonOffsetMultiplier;
				separation *= this.separationMultiplier;
			}
			const { distance, offset, opacity } = this._internalState.calculations[i - 1];
			this._internalState.calculations[i] = {
				distance: distance + separation,
				offset: offset + horizonOffset,
				opacity: opacity * this.opacityMultiplier
			};
		}

		this._internalState.calculations[this.flankingItems + 1] = {
			distance: 0,
			offset: 0,
			opacity: 0
		};
	}

	private setupCarousel() {
		this._internalState.items = this.images;
		if (this.horizon === 0) this.horizon = this._internalState.containerDimensions[Number(!this.isVertical)] / 2;
		for (const item of this._internalState.items) {
			let left, top;
			if (this.isVertical) {
				left = this.horizon - Number(item.dataset.originalWidth) / 2;
				top = this._internalState.containerDimensions[1] / 2 - Number(item.dataset.originalHeight) / 2;
			} else {
				left = this._internalState.containerDimensions[0] / 2 - Number(item.dataset.originalWidth) / 2;
				top = this.horizon - Number(item.dataset.originalHeight) / 2;
			}

			Object.assign(item.style, {
				left: `${left}px`,
				top: `${top}px`,
				visibility: "visible",
				position: "absolute",
				"z-index": 0,
				opacity: 0
			});
			item.style.display = "";
		}
	}

	private performCalculations(item: HTMLElement, newPosition: number) {
		const newDistanceFromCenter = Math.abs(newPosition);
		const calculations =
			newDistanceFromCenter < this.flankingItems + 1
				? this._internalState.calculations[newDistanceFromCenter]
				: this._internalState.calculations[this.flankingItems + 1];
		const distanceFactor = this.sizeMultiplier ** newDistanceFromCenter;
		const newWidth = distanceFactor * Number(item.dataset.originalWidth);
		const newHeight = distanceFactor * Number(item.dataset.originalHeight);
		const newDistance = newPosition < 0 ? -calculations.distance : calculations.distance;

		const center = this._internalState.containerDimensions[Number(this.isVertical)] / 2;
		let top: number, left: number;
		if (this.isVertical) {
			left = this.horizon - calculations.offset - newWidth / 2;
			top = center + newDistance - newHeight / 2;
		} else {
			left = center + newDistance - newWidth / 2;
			top = this.horizon - calculations.offset - newHeight / 2;
		}

		item.dataset.width = String(newWidth);
		item.dataset.height = String(newHeight);
		item.dataset.top = String(top);
		item.dataset.left = String(left);
		item.dataset.oldPosition = item.dataset.currentPosition || "0";
		item.dataset.depth = String(this.flankingItems + 2 - newDistanceFromCenter);
		item.dataset.opacity = String(newPosition ? calculations.opacity : 1);
	}

	private itemAnimationComplete(item: HTMLElement, newPosition: number) {
		this._internalState.itemsAnimating--;
		item.dataset.currentPosition = String(newPosition);
		if (newPosition === 0) this._internalState.currentCenterItem = item;
		if (this._internalState.itemsAnimating) return;
		this._internalState.currentlyMoving = false;
		if (--this._internalState.carouselRotationsLeft <= 0) {
			this._internalState.currentCenterItem?.classList.add(this.centralItemClassName);
			if (!this._internalState.performingSetup) {
				this.movingToCenter();
				this.movedToCenter();
			} else this._internalState.performingSetup = false;
		} else this.rotateCarousel();
	}

	protected movingFromCenter(element?: Element) {
		if (element) {
			assertDevOnly(element instanceof HTMLElement);
			return element;
		} else return;
	}

	protected movingToCenter() {
		/* no-op */
	}

	protected movedToCenter() {
		/* no-op */
	}

	protected moveItem(item: HTMLElement, newPosition: number) {
		const assignToItem = () => {
			Object.assign(item.style, {
				left: `${item.dataset.left}px`,
				width: `${item.dataset.width}px`,
				height: `${item.dataset.height}px`,
				top: `${item.dataset.top}px`,
				opacity: String(item.dataset.opacity)
			});
		};

		if (Math.abs(newPosition) <= this.flankingItems + 1) {
			this.performCalculations(item, newPosition);
			this._internalState.itemsAnimating++;
			item.style.zIndex = item.dataset.depth ?? "";
			assignToItem();
			setTimeout(() => {
				this.itemAnimationComplete(item, newPosition);
			}, this.animationLength);
		} else {
			item.dataset.currentPosition = String(newPosition);
			if (item.dataset.oldPosition === "0" || !item.dataset.oldPosition) {
				this.performCalculations(item, newPosition);
				assignToItem();
			}
		}
	}

	private setupStarterRotation() {
		this.startingItem ||= Math.round(this._internalState.totalItems / 2);
		this._internalState.rightItemsCount = Math.ceil((this._internalState.totalItems - 1) / 2);
		this._internalState.leftItemsCount = Math.floor((this._internalState.totalItems - 1) / 2);
		this._internalState.carouselRotationsLeft = 1;
		let itemIndex = this.startingItem - 1;
		this.moveItem(this._internalState.items[itemIndex], 0);
		this._internalState.items[itemIndex].style.opacity = "1";

		for (let pos = 1; pos <= this._internalState.rightItemsCount; pos++) {
			itemIndex < this._internalState.totalItems - 1 ? itemIndex++ : (itemIndex = 0);
			this._internalState.items[itemIndex].style.opacity = "1";
			this.moveItem(this._internalState.items[itemIndex], pos);
		}
		itemIndex = this.startingItem - 1;
		for (let pos = -1; pos >= -this._internalState.leftItemsCount; pos--) {
			itemIndex > 0 ? itemIndex-- : (itemIndex = this._internalState.totalItems - 1);
			this._internalState.items[itemIndex].style.opacity = "1";
			this.moveItem(this._internalState.items[itemIndex], pos);
		}
	}

	initCarousel(parent: HTMLElement) {
		this._internalState = resetInternalState();
		this.initializeCarouselData(parent);
		this.forceImageDimensionIfEnabled();
		this.preload(() => {
			this.setOriginalItemDimensions();
			this.calculatePositionProperties();
			this.setupCarousel();
			this.setupStarterRotation();
		});
	}

	private moveOnce(direction: CarouselDirection) {
		if (this._internalState.currentlyMoving) return;
		this._internalState.previousCenterItem = this._internalState.currentCenterItem;
		this.movingFromCenter(this._internalState.currentCenterItem);
		if (direction === CarouselDirection.BACKWARDS) {
			this.movingFromCenter(this._internalState.currentCenterItem?.previousElementSibling ?? undefined);
		} else if (direction === CarouselDirection.FORWARDS) {
			this.movingFromCenter(this._internalState.currentCenterItem?.nextElementSibling ?? undefined);
		}
		this._internalState.currentDirection = direction;
	}

	private rotateCarousel() {
		if (this._internalState.currentlyMoving) return;
		this._internalState.currentCenterItem?.classList.remove(this.centralItemClassName);
		this._internalState.currentlyMoving = true;
		this._internalState.itemsAnimating = 0;
		this._internalState.carouselRotationsLeft++;
		for (const item of this._internalState.items) {
			const currentPosition = parseInt(item.dataset.currentPosition ?? "", 10);
			let newPosition = currentPosition + -Number(this._internalState.currentDirection);
			if (Math.abs(newPosition) > this._internalState[newPosition > 0 ? "rightItemsCount" : "leftItemsCount"]) {
				newPosition = -currentPosition;
				if (this._internalState.totalItems % 2 === 0) newPosition++;
			}

			this.moveItem(item, newPosition);
		}
	}

	nextItem() {
		this.moveOnce(CarouselDirection.FORWARDS);
		this.rotateCarousel();
	}

	previousItem() {
		this.moveOnce(CarouselDirection.BACKWARDS);
		this.rotateCarousel();
	}

	switchOrientation() {
		this.isVertical = !this.isVertical;
		this.rotateCarousel();
	}

	connectedCallback(): void {
		super.connectedCallback();
		this.parent.then((parent) => { this.initCarousel(parent); }).catch(e => { console.error(e); });
		window.addEventListener(
			"resize",
			(this.windowResizeListener = () => {
				this.parent.then((p) => { this.initCarousel(p); }).catch(e => { console.log(e) });
			})
		);
	}

	disconnectedCallback(): void {
		super.disconnectedCallback();
		window.removeEventListener("resize", this.windowResizeListener);
	}

	render() {
		return html`<div class="wrap">
			<div class="images" style=${styleMap({ height: this.imageSize, margin: this.margin })}>
				<slot></slot>
			</div>
			<div class="carousel-controls">
				<button class="carousel-controls__previous-button" @click="${() => { this.previousItem(); }}"></button>
				${this.allowSwitchingOrientation
					? html`<button class="carousel-controls__perspective-button" @click="${() => { this.switchOrientation(); }}">Switch</button>`
					: ""}
				<button class="carousel-controls__next-button" @click="${() => { this.nextItem(); }}"></button>
			</div>
		</div>`;
	}
}
