// react/src/components/custom-video/CustomVideo.tsx
import React, { useCallback, useMemo, useReducer, useRef } from "react";
import { VideoConfigurationProps, toMinutesSeconds } from "shared/component/customVideo";
import styles from "./CustomVideo.module.css";
import { WithChildren } from "../../utils/utils";
import { RangeInput } from "../range-input/RangeInput";
import { CustomVideoState, CustomVideoStateAction } from "react/src/interfaces/component/customVideo";
import playButton from "../../../../assets/img/play.png";
import pauseButton from "../../../../assets/img/pause.png";
import resetButton from "../../../../assets/img/reset.png";
import muteButton from "../../../../assets/img/volume.png";

function customVideoStateReducer(state: CustomVideoState, action: CustomVideoStateAction): CustomVideoState {
	switch (action.type) {
		case "setVideoVolume":
			return {
				...state,
				volume: action.volume
			};
		case "startVideo":
			return {
				...state,
				isVideoPlaying: true
			};
		case "stopVideo":
			return {
				...state,
				isVideoPlaying: false
			};
        case "resetVideo": {
            return {
                ...state,
                isVideoPlaying: false,
                current: 0,
                currentTimeLabel: toMinutesSeconds(0)
            };
        }
		case "toggleMute":
			if (state.isMuted && state.previousVideoVolume !== undefined) {
				return {
					...state,
					isMuted: false,
					volume: state.previousVideoVolume
				};
			} else {
				return {
					...state,
					previousVideoVolume: state.volume,
					volume: 0,
					isMuted: true
				};
			}
		case "updateCurrent":
			return {
				...state,
				currentTimeLabel: toMinutesSeconds(action.videoTime),
				current: action.videoTime
			};
		case "setVideoState":
			return {
				...state,
				duration: action.duration,
				current: action.current,
				volume: action.volume,
				currentTimeLabel: toMinutesSeconds(action.current)
			};
	}
}

export const CustomVideo = (props: WithChildren<VideoConfigurationProps>) => {
	const video = useRef<HTMLVideoElement>(null);
	const videoPassedProps = useMemo(() => {
		const configuration: Partial<typeof props> = { ...props };
		delete configuration.muted;
		delete configuration.autoplay;
		delete configuration.children;
		return configuration;
	}, [props]);

	const [videoState, dispatch] = useReducer(customVideoStateReducer, {
		isMuted: props.muted ?? false,
		isVideoPlaying: props.autoplay ?? false,
		currentTimeInSeconds: 0,
		volume: 1,
		currentTimeLabel: toMinutesSeconds(0)
	});

	const updateTrackInfo = useCallback(() => {
		dispatch({
			type: "updateCurrent",
			videoTime: video.current?.currentTime ?? 0
		});
	}, [video]);

	const setVolume = useCallback(
		(volume: number) => {
			if (!video.current) return;
			video.current.volume = volume;

			dispatch({
				type: "setVideoVolume",
				volume
			});
		},
		[video]
	);

	const setVideoSecond = useCallback(
		(seconds: number) => {
			if (!video.current) return;
			video.current.currentTime = seconds;
		},
		[video]
	);

	const startVideo = useCallback(() => {
        if (!video.current) return;
        video.current.play().catch(e => { console.debug(e); });
        dispatch({ type: "startVideo" });
    }, [video]);

	const stopVideo = useCallback(() => {
        video.current?.pause();
        dispatch({ type: "stopVideo" });
    }, [video]);

	const resetVideo = useCallback(() => {
        if (!video.current) return;
        video.current.currentTime = 0;
        video.current.pause();
        dispatch({ type: "resetVideo" });
    }, [video]);

	const muteVideo = useCallback(() => {
        if (!video.current) return;
        dispatch({ type: "toggleMute" });

        if (videoState.isMuted && videoState.previousVideoVolume !== undefined) {
            video.current.volume = videoState.previousVideoVolume;
        } else video.current.volume = 0;
    }, [video, videoState.isMuted, videoState.previousVideoVolume]);

	const setupVideo = useCallback(() => {
		if (!video.current || (!props.children && !props.src)) return;
		dispatch({
			type: "setVideoState",
			duration: video.current.duration,
			current: video.current.currentTime,
			volume: video.current.volume
		});
	}, [props.children, props.src, video]);

	return (
		<div className={styles.wrap}>
			<div className={styles.video}>
				<video ref={video} {...videoPassedProps} onTimeUpdate={updateTrackInfo} onLoadedMetadata={setupVideo} onEnded={stopVideo}>
					{props.children}
				</video>
			</div>
			<div className={styles.controls}>
				<RangeInput
					className={styles["volume-range-input"]}
					step={0.01}
					maximum={1}
					hideValue
					defaultValue={videoState.volume}
					onUpdate={setVolume}
				/>
				<RangeInput
					className={styles["time-range-input"]}
					step={0.01}
					maximum={videoState.duration}
					label={videoState.currentTimeLabel}
					hideValue
					allSameLine
					onUpdate={setVideoSecond}
					defaultValue={videoState.current}
				/>
				<ul className={styles["controls-buttons"]}>
					<li
						className={styles["control-button"]}
						style={{ display: videoState.isVideoPlaying ? "none" : "block" }}
						onClick={startVideo}
					>
                        <button className={styles["controls-button__clickable-button"]}>
                            <img alt="Play" src={playButton} className={styles["controls-button__image"]} />
                        </button>
                    </li>
                    <li
						className={styles["control-button"]}
						style={{ display: videoState.isVideoPlaying ? "block" : "none" }}
						onClick={stopVideo}
					>
                        <button className={styles["controls-button__clickable-button"]}>
                            <img alt="Pause" src={pauseButton} className={styles["controls-button__image"]} />
                        </button>
                    </li>
                    <li className={styles["control-button"]} onClick={resetVideo}>
                        <button className={styles["controls-button__clickable-button"]}>
                            <img alt="Reset" src={resetButton} className={styles["controls-button__image"]} />
                        </button>
                    </li>
                    <li className={styles["control-button"]} onClick={muteVideo}>
                        <button className={styles["controls-button__clickable-button"]}>
                            <img alt="Mute" src={muteButton} className={styles["controls-button__image"]} />
                        </button>
                    </li>
				</ul>
			</div>
		</div>
	);
};

// vue/src/components/custom-video/CustomVideo.vue
<template>
	<div class="wrap">
		<div class="video">
			<video ref="video" v-bind="videoPassedProps" @timeupdate="updateTrackInfo">
				<slot></slot>
			</video>
		</div>
		<div class="controls">
			<range-input-component
				id="volume-range-input"
				:step="0.01"
				:maximum="1"
				hide-value
				@change="setVolume"
                :default-value="rangeInputSettings.volume"
			></range-input-component>
			<range-input-component
				id="time-range-input"
				:step="0.01"
				:maximum="rangeInputSettings.duration"
				:label="rangeInputSettings.currentTimeLabel"
				hide-value
				all-same-line
				@change="setVideoSecond"
				:default-value="rangeInputSettings.current"
			></range-input-component>
			<ul class="controls-buttons">
				<li class="controls-button" :style="{ display: isVideoPlaying ? 'none' : 'block' }" @click="startVideo">
					<button class="controls-button__clickable-button">
						<img alt="Play" :src="playButton" class="controls-button__image" />
					</button>
				</li>
				<li class="controls-button" :style="{ display: isVideoPlaying ? 'block' : 'none' }" @click="stopVideo">
					<button class="controls-button__clickable-button">
						<img alt="Pause" :src="pauseButton" class="controls-button__image" />
					</button>
				</li>
				<li class="controls-button" @click="resetVideo">
					<button class="controls-button__clickable-button">
						<img alt="Reset" :src="resetButton" class="controls-button__image" />
					</button>
				</li>
				<li class="controls-button" @click="toggleMute">
					<button class="controls-button__clickable-button">
						<img alt="Mute" :src="muteButton" class="controls-button__image" />
					</button>
				</li>
			</ul>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, reactive } from "vue";
import playButton from "../../../../assets/img/play.png";
import pauseButton from "../../../../assets/img/pause.png";
import resetButton from "../../../../assets/img/reset.png";
import muteButton from "../../../../assets/img/volume.png";
import RangeInputComponent from "../range-input/RangeInput.vue";
import { assertNonUndefined } from "shared/utils/utils";
import { VideoConfigurationProps, toMinutesSeconds } from "shared/component/customVideo";

const props = defineProps<VideoConfigurationProps>();

const video = ref<HTMLVideoElement | null>(null);
const isMuted = ref(props.muted);
const previousVideoVolume = ref<number | undefined>();
const isVideoPlaying = ref(props.autoplay ?? false);
const currentTimeInSeconds = ref(0);

const rangeInputSettings = reactive({
	duration: video.value?.duration,
	current: video.value?.currentTime,
	volume: video.value?.volume ?? 1,
	currentTimeLabel: toMinutesSeconds(video.value?.currentTime ?? 0)
});
const videoPassedProps = computed(() => {
	const configuration: Partial<VideoConfigurationProps> = { ...props };
	delete configuration.muted;
	delete configuration.autoplay;
	return configuration;
});

const updateTrackInfo = () => {
    if (!video.value) return;
    rangeInputSettings.currentTimeLabel = toMinutesSeconds(video.value.currentTime);
    rangeInputSettings.current = video.value.currentTime;
};

const startVideo = () => {
    video.value?.play()?.catch(e => { console.debug(e); });
    isVideoPlaying.value = true; 
};

const stopVideo = () => {
    video.value?.pause();
    isVideoPlaying.value = false; 
};

const resetVideo = () => {
    if (video.value) video.value.currentTime = 0;
    stopVideo();
};

const toggleMute = () => {
    if (!video.value) return;
    if (isMuted.value && previousVideoVolume.value !== undefined) {
        isMuted.value = false;
        video.value.volume = previousVideoVolume.value;
    } else {
        isMuted.value = true;
        previousVideoVolume.value = video.value.volume;
        video.value.volume = 0;
    }

    rangeInputSettings.volume = video.value.volume;
};

const setVideoSecond = (seconds: number) => {
	if (!video.value) return;
    video.value.currentTime = seconds;
    currentTimeInSeconds.value = video.value.currentTime;
    startVideo();
};

const setVolume = (volume: number) => {
    if (video.value) video.value.volume = volume;
    rangeInputSettings.volume = volume;
};

onMounted(() => {
	if (!video.value) return;
	video.value.load();
	video.value.onloadeddata = () => {
		assertNonUndefined(video.value);

		if (props.muted) {
			video.value.volume = 0;
            isMuted.value = true;
            previousVideoVolume.value = 1;
			if (props.autoplay) startVideo();
		}

        rangeInputSettings.duration = video.value.duration;
	};
});
</script>

<style scoped>
.wrap {
	position: relative;
	width: 100%;
	height: 100%;
}

.video {
	width: inherit;
	height: inherit;
}

.controls {
	position: absolute;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 1;
	background-color: #e2e2e2;
	display: flex;
	flex-direction: row-reverse;
	justify-content: space-around;
	height: 12.5%;
	padding: 4px;
	box-sizing: border-box;
}

.controls-buttons {
	display: flex;
	list-style-type: none;
	padding: 0;
	margin: 0;
	gap: 5%;
}

.control-button {
	display: block;
	height: 100%;
	cursor: pointer;
}

.controls-button__clickable-button {
	width: inherit;
	height: 100%;
	padding: 0;
	margin: 0;
	border: none;
	background: none;
	cursor: pointer;
}

.controls-button__image {
	width: inherit;
	height: inherit;
	cursor: pointer;
}

#time-range-input {
	margin-left: 15px;
	color: #000;
}

#volume-range-input {
	width: 33px;
}
</style>
