// lit/src/components/custom-video/customVideo.ts
import { LitElement, css, html } from "lit";
import { property, queryAssignedElements, state } from "lit/decorators.js";
import { RangeInputComponent } from "../range-input/rangeInput";
import playButton from "src/../assets/img/play.png";
import pauseButton from "src/../assets/img/pause.png";
import resetButton from "src/../assets/img/reset.png";
import muteButton from "src/../assets/img/volume.png";
import { assertNonUndefined } from "shared/utils/utils";
import { styleMap } from "lit/directives/style-map.js";
import { VideoConfigurationProps, toMinutesSeconds } from "shared/component/customVideo";
import { createRef, ref } from "lit/directives/ref.js";
import { ifDefined } from "lit/directives/if-defined.js";
import { RangeInputChangeEvent } from "../range-input/events";

window.customElements.define("range-input-component", RangeInputComponent);

export class CustomVideoComponent extends LitElement implements VideoConfigurationProps {
	static styles = css`
		:host {
			display: block;
			position: relative;
		}

		.video {
			width: inherit;
			height: inherit;
		}

		.controls {
			position: absolute;
			left: 0;
			right: 0;
			bottom: 0;
			z-index: 1;
			background-color: #e2e2e2;
			display: flex;
			flex-direction: row-reverse;
			justify-content: space-around;
			height: 12.5%;
			padding: 4px;
			box-sizing: border-box;
		}

		.controls-buttons {
			display: flex;
			list-style-type: none;
			padding: 0;
			margin: 0;
			gap: 5%;
		}

		.control-button {
			display: block;
			height: 100%;
			cursor: pointer;
		}

		.controls-button__clickable-button {
			width: inherit;
			height: 100%;
			padding: 0;
			margin: 0;
			border: none;
			background: none;
			cursor: pointer;
		}

		.controls-button__image {
			width: inherit;
			height: inherit;
			cursor: pointer;
		}

		range-input-component {
			display: block;
		}

		#time-range-input {
			margin-left: 15px;
			color: #000;
		}

		#volume-range-input {
			width: 33px;
		}
	`;

	@queryAssignedElements({ selector: "source" })
	_sourceElements!: HTMLSourceElement[];

	@property({ type: Boolean })
	autoplay = false;
	@property({ type: Boolean })
	muted = false;
	@property({ type: String })
	crossorigin?: "anonymous" | "use-credentials";
	@property({ type: String })
	poster?: string;
	@property({ type: String })
	preload?: "none" | "metadata" | "auto";
	@property({ type: String })
	src?: string;
	@property({ type: Number })
	height?: number;
	@property({ type: Number })
	width?: number;

	@state()
	_isVideoPlaying = false;
	@state()
	_isMuted = false;
	@state()
	_videoDuration?: number;
	@state()
	_currentTimeLabel = toMinutesSeconds(0);
	@state()
	_current?: number;
	@state()
	_volume = 1;

	private _previousVideoVolume?: number;
	private _videoRef = createRef<HTMLVideoElement>();

	protected updateTrackInfo() {
		assertNonUndefined(this._videoRef.value);
		this._currentTimeLabel = toMinutesSeconds(this._videoRef.value.currentTime);
		this._current = this._videoRef.value.currentTime;
	}

	startVideo() {
		this._videoRef.value
			?.play()
			?.then(() => {
				this._isVideoPlaying = true;
			})
			?.catch((e) => {
				console.debug(e);
			});
	}

	stopVideo() {
		this._videoRef.value?.pause();
		this._isVideoPlaying = false;
	}

	resetVideo() {
		if (this._videoRef.value) this._videoRef.value.currentTime = 0;
		this.stopVideo();
	}

	toggleMute() {
		assertNonUndefined(this._videoRef.value);
		if (this._isMuted && this._previousVideoVolume !== undefined) {
			this._isMuted = false;
			this._videoRef.value.volume = this._previousVideoVolume;
		} else {
			this._isMuted = true;
			this._previousVideoVolume = this._videoRef.value.volume;
			this._videoRef.value.volume = 0;
		}

		this._volume = this._videoRef.value.volume;
	}

	setVideoSecond(seconds: number) {
		assertNonUndefined(this._videoRef.value);
		this._videoRef.value.currentTime = seconds;
	}

	setVolume(volume: number) {
		if (this._videoRef.value) this._videoRef.value.volume = volume;
		this._volume = volume;
	}

	protected firstUpdated(): void {
		assertNonUndefined(this._videoRef.value);
		this._videoRef.value.append(...this._sourceElements);
		this._videoRef.value.load();
		this._videoRef.value.onloadeddata = () => {
			assertNonUndefined(this._videoRef.value);
			if (this.muted) {
				this._videoRef.value.volume = 0;
				this._isMuted = true;
				this._previousVideoVolume = 1;
				if (this.autoplay) this.startVideo();
			}

			this._videoDuration = this._videoRef.value.duration;
		};
	}

	render() {
		return html`<div class="video">
				<video
					${ref(this._videoRef)}
					?muted=${this.muted}
					width=${ifDefined(this.width)}
					height=${ifDefined(this.height)}
					poster=${ifDefined(this.poster)}
					preload=${ifDefined(this.preload)}
					src=${ifDefined(this.src)}
					crossorigin=${ifDefined(this.crossorigin)}
					@timeupdate=${() => {
						this.updateTrackInfo();
					}}
					@ended=${() => {
						this.stopVideo();
					}}
				>
					<slot></slot>
				</video>
			</div>
			<div class="controls">
				<range-input-component
					id="volume-range-input"
					step="0.01"
					defaultValue="1"
					.dynamicValue=${this._volume}
					maximum="1"
					hideValue
					@change=${(event: RangeInputChangeEvent) => {
						this.setVolume(event.value);
					}}
				></range-input-component>
				<range-input-component
					id="time-range-input"
					step="0.01"
					label=${this._currentTimeLabel}
					maximum=${ifDefined(this._videoDuration)}
					.dynamicValue=${this._current ?? 0}
					hideValue
					allSameLine
					@change=${(event: RangeInputChangeEvent) => {
						this.setVideoSecond(event.value);
					}}
				></range-input-component>
				<ul class="controls-buttons">
					<li
						class="controls-button"
						@click="${() => {
							this.startVideo();
						}}"
						style=${styleMap({ display: this._isVideoPlaying ? "none" : "block" })}
					>
						<button class="controls-button__clickable-button">
							<img alt="Play" src="${playButton}" class="controls-button__image" />
						</button>
					</li>
					<li
						class="controls-button"
						@click="${() => {
							this.stopVideo();
						}}"
						style=${styleMap({ display: this._isVideoPlaying ? "block" : "none" })}
					>
						<button class="controls-button__clickable-button">
							<img alt="Pause" src="${pauseButton}" class="controls-button__image" />
						</button>
					</li>
					<li
						class="controls-button"
						@click="${() => {
							this.resetVideo();
						}}"
					>
						<button class="controls-button__clickable-button">
							<img alt="Reset" src="${resetButton}" class="controls-button__image" />
						</button>
					</li>
					<li
						class="controls-button"
						@click="${() => {
							this.toggleMute();
						}}"
					>
						<button class="controls-button__clickable-button">
							<img alt="Mute" src="${muteButton}" class="controls-button__image" />
						</button>
					</li>
				</ul>
			</div>`;
	}
}

// src/modules/vue-components/custom-video/CustomVideo.vue
<template>
	<div class="wrap">
		<div class="video">
			<video ref="video" v-bind="videoPassedProps" @timeupdate="updateTrackInfo">
				<slot></slot>
			</video>
		</div>
		<div class="controls">
			<range-input-component
				id="volume-range-input"
				:step="0.01"
				:maximum="1"
				hide-value
				@change="setVolume"
                :default-value="1"
				:value="rangeInputSettings.volume"
			></range-input-component>
			<range-input-component
				id="time-range-input"
				:step="0.01"
				:maximum="rangeInputSettings.duration"
				:label="rangeInputSettings.currentTimeLabel"
				hide-value
				all-same-line
				@change="setVideoSecond"
				:value="rangeInputSettings.current"
			></range-input-component>
			<ul class="controls-buttons">
				<li class="controls-button" :style="{ display: isVideoPlaying ? 'none' : 'block' }" @click="startVideo">
					<button class="controls-button__clickable-button">
						<img alt="Play" :src="playButton" class="controls-button__image" />
					</button>
				</li>
				<li class="controls-button" :style="{ display: isVideoPlaying ? 'block' : 'none' }" @click="stopVideo">
					<button class="controls-button__clickable-button">
						<img alt="Pause" :src="pauseButton" class="controls-button__image" />
					</button>
				</li>
				<li class="controls-button" @click="resetVideo">
					<button class="controls-button__clickable-button">
						<img alt="Reset" :src="resetButton" class="controls-button__image" />
					</button>
				</li>
				<li class="controls-button" @click="toggleMute">
					<button class="controls-button__clickable-button">
						<img alt="Mute" :src="muteButton" class="controls-button__image" />
					</button>
				</li>
			</ul>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, reactive } from "vue";
import playButton from "../../../assets/img/play.png";
import pauseButton from "../../../assets/img/pause.png";
import resetButton from "../../../assets/img/reset.png";
import muteButton from "../../../assets/img/volume.png";
import RangeInputComponent from "../range-input/RangeInput.vue";
import { assertNonUndefined } from "src/modules/utils";
import { VideoConfigurationProps, toMinutesSeconds } from "src/modules/interfaces/component/custom-video/types";

const props = defineProps<VideoConfigurationProps>();

const video = ref<HTMLVideoElement | null>(null);
const isMuted = ref(props.muted);
const previousVideoVolume = ref<number | undefined>();
const isVideoPlaying = ref(props.autoplay ?? false);
const currentTimeInSeconds = ref(0);

const rangeInputSettings = reactive({
	duration: video.value?.duration,
	current: video.value?.currentTime,
	volume: video.value?.volume ?? 1,
	currentTimeLabel: toMinutesSeconds(video.value?.currentTime ?? 0)
});
const videoPassedProps = computed(() => {
	const configuration: Partial<VideoConfigurationProps> = { ...props };
	delete configuration.muted;
	delete configuration.autoplay;
	return configuration;
});

const updateTrackInfo = () => {
    if (!video.value) return;
    rangeInputSettings.currentTimeLabel = toMinutesSeconds(video.value.currentTime);
    rangeInputSettings.current = video.value.currentTime;
};

const startVideo = () => {
    video.value?.play()?.catch(e => { console.debug(e); });
    isVideoPlaying.value = true; 
};

const stopVideo = () => {
    video.value?.pause();
    isVideoPlaying.value = false; 
};

const resetVideo = () => {
    if (video.value) video.value.currentTime = 0;
    stopVideo();
};

const toggleMute = () => {
    if (!video.value) return;
    if (isMuted.value && previousVideoVolume.value !== undefined) {
        isMuted.value = false;
        video.value.volume = previousVideoVolume.value;
    } else {
        isMuted.value = true;
        previousVideoVolume.value = video.value.volume;
        video.value.volume = 0;
    }

    rangeInputSettings.volume = video.value.volume;
};

const setVideoSecond = (seconds: number) => {
	if (!video.value) return;
    video.value.currentTime = seconds;
    currentTimeInSeconds.value = video.value.currentTime;
    startVideo();
};

const setVolume = (volume: number) => {
    if (video.value) video.value.volume = volume;
    rangeInputSettings.volume = volume;
};

onMounted(() => {
	if (!video.value) return;
	video.value.load();
	video.value.onloadeddata = () => {
		assertNonUndefined(video.value);

		if (props.muted) {
			video.value.volume = 0;
            isMuted.value = true;
            previousVideoVolume.value = 1;
			if (props.autoplay) startVideo();
		}

        rangeInputSettings.duration = video.value.duration;
	};
});
</script>

<style scoped>
.wrap {
	position: relative;
	width: 100%;
	height: 100%;
}

.video {
	width: inherit;
	height: inherit;
}

.controls {
	position: absolute;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 1;
	background-color: #e2e2e2;
	display: flex;
	flex-direction: row-reverse;
	justify-content: space-around;
	height: 12.5%;
	padding: 4px;
	box-sizing: border-box;
}

.controls-buttons {
	display: flex;
	list-style-type: none;
	padding: 0;
	margin: 0;
	gap: 5%;
}

.control-button {
	display: block;
	height: 100%;
	cursor: pointer;
}

.controls-button__clickable-button {
	width: inherit;
	height: 100%;
	padding: 0;
	margin: 0;
	border: none;
	background: none;
	cursor: pointer;
}

.controls-button__image {
	width: inherit;
	height: inherit;
	cursor: pointer;
}

#time-range-input {
	margin-left: 15px;
	color: #000;
}

#volume-range-input {
	width: 33px;
}
</style>
