// lit/src/components/accordion/accordion.ts
import { LitElement, css, html } from "lit";
import { property } from "lit/decorators.js";
import { AccordionListConfiguration } from "shared/component/accordion";
import { provide } from "@lit/context";
import { AccordionItemComponent } from "./accordionItem";
import { AccordionContext, accordionContext } from "./context";

export class AccordionComponent extends LitElement implements AccordionListConfiguration {
	static styles = css`
		.accordions {
			margin: 0;
			padding-left: 0;
			list-style-type: none;
		}
	`;

	@property({ type: Boolean })
	multiple = false;
	@provide({ context: accordionContext })
	_accordionContext: AccordionContext = {
		expandedIndex: "",
		setExpandedIndex: (newIndex: string) => {
			const newContext = { ...this._accordionContext };
			if (!this.multiple) {
				newContext.expandedIndex = newContext.expandedIndex === newIndex ? "" : newIndex;
			} else {
				if (typeof newContext.expandedIndex === "string") newContext.expandedIndex = [];
				if (newContext.expandedIndex.includes(newIndex)) {
					newContext.expandedIndex = newContext.expandedIndex.filter((id) => id !== newIndex);
				} else newContext.expandedIndex = [...newContext.expandedIndex, newIndex];
			}

			this._accordionContext = newContext;
		}
	};

	render() {
		return html`
			<ul class="accordions">
				<slot></slot>
			</ul>
		`;
	}
}

export { AccordionItemComponent };

// react/src/components/accordion/Accordion.tsx
import React, { useCallback, useMemo, useState } from "react";
import { AccordionListConfiguration } from "shared/component/accordion";
import styles from "./Accordion.module.css";
import { WithChildren } from "../../../src/utils/utils";
import { AccordionContext } from "./context";

export const Accordion = (props: WithChildren<AccordionListConfiguration>) => {
    const [expandedIndex, setExpandedIndex] = useState<string | string[]>(props.multiple ? [] : "");

    const expandIndex = useCallback((newIndex: string) => {
        if (!props.multiple) {
            setExpandedIndex((expandedIndex) => {
                return expandedIndex === newIndex ? "" : newIndex;
            });
        } else {
            setExpandedIndex((expandedIndex) => {
                if (typeof expandedIndex === "string") return expandedIndex;
                if (expandedIndex.includes(newIndex)) {
                    return expandedIndex.filter(i => i !== newIndex);
                } else return [...expandedIndex, newIndex];
            });
        }
    }, [props.multiple]);

    const context = useMemo(() => ({
        expandedIndex,
        expandIndex
    }), [expandIndex, expandedIndex]);

    return <AccordionContext.Provider value={context}>
        <ul className={styles.accordions}>
            {props.children}
        </ul>
    </AccordionContext.Provider>
};
