// vue/src/components/sticky-header/StickyHeader.vue
<template>
  <div ref="outerWrap">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from "vue";
import { generateThreshold } from "shared/interfaces/intersectionObserved";
import { StickyHeaderConfiguration } from "shared/component/stickyHeader";
import { useInjectedLinkedItems } from "../../interfaces/hooks/useLinkedItem";

const props = withDefaults(defineProps<Partial<StickyHeaderConfiguration>>(), {
	rootMargin: "0px",
	ratio: 0.25
});

const headerElements = useInjectedLinkedItems();

const outerWrap = ref<HTMLElement | null>(null);
const isFixed = ref(false);
const intersectionObserver = ref<IntersectionObserver | undefined>();

onMounted(() => {
	const wrap = headerElements["sticky-header"];
	if (!outerWrap.value) return;

	const intersectionObserverInstance = new IntersectionObserver(
		([entry]) => {
			(async () => {
				if (!outerWrap.value) return;

				if (entry.intersectionRatio <= props.ratio && !isFixed.value) {
					isFixed.value = true;
					const { top, left, width, height } = wrap.element.getBoundingClientRect();
					wrap.styles = {
						...wrap.styles,
						position: "fixed",
						top: `${String(top)}px`,
						left: `${String(left)}px`,
						width: `${String(width)}px`,
						height: `${String(height)}px`,
						zIndex: 9999
					};

					await nextTick();
					wrap.element.getBoundingClientRect();

					setTimeout(() => {
						wrap.styles = {
							...wrap.styles,
							top: 0,
							left: 0,
							right: 0,
							width: "auto",
							height: "auto"
						};
					}, 1);
				} else if (entry.intersectionRatio > props.ratio && isFixed.value) {
					isFixed.value = false;
					wrap.styles = {
						...wrap.styles,
						position: "static",
						top: "0",
						left: "0",
						right: "0"
					};
				}
			})().catch((e: unknown) => {
				console.trace(e);
			});
		},
		{
			rootMargin: props.rootMargin,
			threshold: generateThreshold()
		}
	);
	intersectionObserverInstance.observe(outerWrap.value);
	intersectionObserver.value = intersectionObserverInstance;
});

onUnmounted(() => {
	intersectionObserver.value?.disconnect();
});
</script>

// lit/src/components/sticky-header/stickyHeader.ts
import { LitElement, html } from "lit";
import { property } from "lit/decorators.js";
import { LinkedCarouselMixin } from "../../interfaces/hooks/linkedItems";
import { StickyHeaderConfiguration } from "shared/component/stickyHeader";
import { generateThreshold } from "shared/interfaces/intersectionObserved";
import { StickyHeaderElement } from "./stickyHeaderElement";

export class StickyHeaderComponent extends LinkedCarouselMixin(LitElement) implements StickyHeaderConfiguration {
	@property()
	rootMargin = "0px";
	@property({ type: Number })
	ratio = 0.25;
	@property()
	fixedClassName = "fixed";

	protected intersectionObserver?: IntersectionObserver;

	protected firstUpdated() {
		const header = this.linkedItemsContext["sticky-header"];
		let isFixed = false;

		this.intersectionObserver = new IntersectionObserver(
			([entry]) => {
				if (entry.intersectionRatio <= this.ratio && !isFixed) {
					isFixed = true;
					const { top, left } = header.element.getBoundingClientRect();
					Object.assign(header.element.style, {
						position: "fixed",
						top: `${String(top)}px`,
						left: `${String(left)}px`
					});
					header.element.getBoundingClientRect();

					header.styles = {
						position: "fixed",
						top: "0",
						left: "0",
						right: "0"
					};
				} else if (entry.intersectionRatio > this.ratio && isFixed) {
					isFixed = false;
					header.styles = {};
				}
			},
			{
				rootMargin: this.rootMargin,
				threshold: generateThreshold()
			}
		);

		this.intersectionObserver.observe(this);
	}

	disconnectedCallback(): void {
		this.intersectionObserver?.disconnect();
		super.disconnectedCallback();
	}

	render() {
		return html`<slot></slot>`;
	}
}

export { StickyHeaderElement };
