// vue/src/components/one-page-scroll/OnePageScrollItem.vue
<template>
    <section class="one-page-scroll-item" ref="item">
        <slot></slot>
    </section>
</template>

<script setup lang="ts">
import { uid } from 'shared/utils/utils';
import { useLinkedItem } from '../../interfaces/hooks/useLinkedItem';
import { ref } from 'vue';

const item = ref<HTMLElement | null>(null);
useLinkedItem(uid, item);
</script>

<style scoped>
.one-page-scroll-item {
    flex: 1 0 0;
    box-sizing: border-box;
}
</style>

// react/src/components/one-page-scroll/OnePageScrollItem.tsx
import React, { useRef } from "react";
import { useLinkedItem } from "../../../src/interfaces/hooks/useLinkedItem";
import { uid } from "shared/utils/utils";
import { WithChildren } from "../../utils/utils";
import styles from "./OnePageScroll.module.css";
import { GenericReactComponentProps } from "../../interfaces/generic/classNameFallthrough";

export const OnePageScrollItem = (props: WithChildren<object> & GenericReactComponentProps) => {
	const item = useRef<HTMLDivElement | null>(null);
	const styleObject = useLinkedItem(uid, item);

	return (
		<div ref={item} className={`${styles["one-page-scroll-item"]} ${props.className ?? ""}`} style={styleObject}>
			{props.children}
		</div>
	);
};
