// react/src/components/image-comparator/ImageComparatorItem.tsx
import React, { useRef } from "react";
import { useLinkedItem } from "../../../src/interfaces/hooks/useLinkedItem";
import { uid } from "shared/utils/utils";
import { WithChildren } from "../../utils/utils";
import { GenericReactComponentProps } from "../../interfaces/generic/classNameFallthrough";
import styles from "./ImageComparator.module.css";

export const ImageComparatorItem = (props: WithChildren<object> & GenericReactComponentProps) => {
    const item = useRef<HTMLLIElement | null>(null);
    const styleObject = useLinkedItem(uid, item);

    return <li ref={item} style={styleObject} className={`${styles["image-comparator-item"]} ${props.className ?? ""}`}>
        {props.children}
    </li>
};

// src/modules/vue-components/image-comparator/ImageComparatorItem.vue
<template>
    <li class="image-comparator-item" ref="item">
        <slot></slot>
    </li>
</template>

<script setup lang="ts">
import { uid } from 'src/modules/utils';
import { useLinkedItem } from '../../interfaces/generic/hooks/useLinkedItem.vue';
import { ref } from 'vue';

const item = ref<HTMLElement | null>(null);
useLinkedItem(uid, item);
</script>

<style scoped>
.image-comparator-item {
  position: absolute;
  width: auto;
  height: auto;
  overflow: hidden;
}
</style>
