// vue/src/components/custom-select/CustomSelect.vue
<template>
  <select
    :value="selectedItem?.value ?? ''"
    :name="selectName"
  >
    <option
      v-for="option in internalItems"
      :key="option.value"
      :value="option.value"
      :disabled="option.isDisabled"
      :selected="option.isSelected"
    >
      {{ option.innerContent }}
    </option>
  </select>
  <div
    ref="wrapElement"
    class="wrap"
  >
    <div
      class="custom-select-option custom-select-current"
      :class="{ active: isOpened }"
      @click="toggleOpened"
    >
      {{ selectedItem?.innerContent ?? "" }}
    </div>
    <ul
      class="custom-select-options"
      :class="{ hidden: !(internalItems.length && isOpened) }"
    >
      <li
        v-for="element in internalItems"
        :key="element.value"
        class="custom-select-option"
        :data-disabled="element.isDisabled"
        :data-selected="element.isSelected"
        :value="element.value"
        @click="
          () => {
            onItemSelected(element);
          }
        "
      >
        {{ element.innerContent }}
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted, onUnmounted, computed } from "vue";
import { CustomSelectConfiguration, SelectInternalItem } from "shared/component/customSelect";

const props = defineProps<CustomSelectConfiguration>();
const emit = defineEmits<{
	(e: "change", element: SelectInternalItem): void;
}>();
const internalItems = reactive([...props.items]);
const isOpened = ref(false);
const boundDocumentListener = ref<EventListener | undefined>();
const wrapElement = ref<HTMLElement | null>(null);
const selectedItem = computed(() => internalItems.find((item) => item.isSelected));

const toggleOpened = () => {
	isOpened.value = !isOpened.value;
};

const onItemSelected = (element: SelectInternalItem) => {
	isOpened.value = false;
	if (element.isDisabled) return;
	for (const el of internalItems) {
		if (el === element) {
			el.isSelected = true;
			emit("change", el);
		} else el.isSelected = false;
	}
};

onMounted(() => {
	const documentListener: EventListener = (event) => {
		if (!event.composedPath().some((e) => e === wrapElement.value)) isOpened.value = false;
	};
	boundDocumentListener.value = documentListener;
	document.addEventListener("click", documentListener);
});

onUnmounted(() => {
	if (!boundDocumentListener.value) return;
	document.removeEventListener("click", boundDocumentListener.value);
});
</script>

<style scoped>
select {
	display: none;
}

.wrap {
	position: relative;
	width: 150px;
}

.custom-select-current {
	border-radius: 20px;
	transition: all 0.3s;
	background-color: dodgerblue;
}

.custom-select-current::after {
	position: absolute;
	content: "";
	top: 14px;
	right: 10px;
	width: 0;
	height: 0;
	border: 6px solid transparent;
	border-color: #fff transparent transparent transparent;
	transition: all 0.3s;
}

.custom-select-current.active::after {
	border-color: transparent transparent #fff transparent;
	top: 7px;
}

.custom-select-option.active {
	border-bottom-left-radius: 0;
	border-bottom-right-radius: 0;
	background-color: darkcyan;
}

.custom-select-option {
	color: #ffffff;
	padding: 3px 12px;
	border: 1px solid transparent;
	border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
	user-select: none;
	cursor: pointer;
}

.custom-select-options {
	position: absolute;
	top: 100%;
	left: 0;
	right: 0;
	z-index: 99;
	opacity: 1;
	transition: opacity 0.2s linear;
	padding-left: 0;
	list-style-type: none;
	margin: 0;
	background-color: dodgerblue;
	border-bottom-left-radius: 20px;
	border-bottom-right-radius: 20px;
}

.custom-select-options.hidden {
	opacity: 0;
	pointer-events: none;
	cursor: default;
}

.custom-select-options .custom-select-option:hover {
	background-color: rgba(0, 0, 0, 0.15);
}

.custom-select-options .custom-select-option[data-selected="true"] {
	background-color: rgba(0, 0, 0, 0.1);
}

.custom-select-options .custom-select-option[data-disabled="true"] {
	background-color: rgba(0, 0, 0, 0.33);
}

.custom-select-options .custom-select-option:last-child {
	overflow: hidden;
}
</style>

// react/src/components/custom-select/CustomSelect.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import { CustomSelectReactConfiguration } from "react/src/interfaces/component/customSelect";
import styles from "./CustomSelect.module.css";
import { SelectInternalItem } from "shared/component/customSelect";

export const CustomSelect = (props: CustomSelectReactConfiguration) => {
	const [internalItems, setInternalItems] = useState([...props.items]);
	const [isOpened, setOpened] = useState(false);
	const selectedItem = internalItems.find((item) => item.isSelected);
	const wrap = useRef<HTMLDivElement>(null);

	const toggleOpened = useCallback(() => {
		setOpened((isOpened) => !isOpened);
	}, []);

	const onItemSelected = useCallback(
		(element: SelectInternalItem) => {
			setOpened(false);
			if (element.isDisabled) return;

			const newElements = [...internalItems];
			for (let i = 0; i < newElements.length; i++) {
				if (newElements[i] === element) {
					newElements[i] = {
						...newElements[i],
						isSelected: true
					};
					props.onChange?.(element);
				} else {
					newElements[i] = {
						...newElements[i],
						isSelected: false
					};
				}
			}

			setInternalItems([...newElements]);
		},
		[internalItems, props]
	);

	useEffect(() => {
		const documentListener: EventListener = (event) => {
			if (!event.composedPath().some((e) => e === wrap.current)) setOpened(false);
		};
		document.addEventListener("click", documentListener);

		return () => {
			document.removeEventListener("click", documentListener);
		};
	}, []);

	return (
		<>
			<select
				className={styles["real-select"]}
				value={selectedItem?.value ?? ""}
				name={props.selectName}
				onChange={() => {
					/* */
				}}
			>
				{internalItems.map((option) => (
					<option value={option.value} disabled={option.isDisabled} key={option.value}>
						{option.innerContent}
					</option>
				))}
			</select>
			<div className={styles.wrap} ref={wrap}>
				<div
					onClick={toggleOpened}
					className={`${styles["custom-select-option"]} ${styles["custom-select-current"]} ${isOpened ? styles["active"] : ""}`}
				>
					{selectedItem?.innerContent ?? ""}
				</div>
				<ul className={`${styles["custom-select-options"]} ${!(internalItems.length && isOpened) ? styles["hidden"] : ""}`}>
					{internalItems.map((element) => (
						<li
							key={element.value}
							className={styles["custom-select-option"]}
							data-disabled={element.isDisabled}
							data-selected={element.isSelected}
							value={element.value}
							onClick={() => {
								onItemSelected(element);
							}}
						>
							{element.innerContent}
						</li>
					))}
				</ul>
			</div>
		</>
	);
};
