// lit/src/components/floating-panel/floatingPanel.ts
import { LitElement, html } from "lit";
import { queryAssignedElements, property } from "lit/decorators.js";
import { FloatingPanelConfiguration } from "shared/component/floatingPanel";

export class FloatingPanelComponent extends LitElement implements FloatingPanelConfiguration {
  @property({ type: Boolean })
  isOpen = false;

  @queryAssignedElements({ flatten: true })
	_floatingPanels!: HTMLElement[];

  private listener!: (event: MouseEvent) => void;

  protected firstUpdated(): void {
    if (this._floatingPanels.length === 0) return;
    const [panel] = this._floatingPanels;
    document.addEventListener("mousedown", this.listener = ({ clientX, clientY }) => {
      const panelX = panel.offsetLeft, panelY = panel.offsetTop;
      const changePosition = (event: MouseEvent) => {
        panel.style.left = panelX + event.clientX - clientX + 'px';
        panel.style.top = panelY + event.clientY - clientY + 'px';
      };

      panel.addEventListener("mousemove", changePosition, false);
      window.addEventListener("mouseup", () => { panel.removeEventListener("mousemove", changePosition, false); });
    });
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    document.removeEventListener("mousedown", this.listener);
  }

  render() {
    return this.isOpen ? html`<slot></slot>` : "";
  }
}

// vue/src/components/floating-panel/FloatingPanel.vue
<template>
    <div class="panel" ref="panel" @mousemove="changePosition" :style="panelStyles" v-if="isOpen">
        <slot></slot>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, reactive, CSSProperties } from "vue";
import { FloatingPanelConfiguration } from "shared/component/floatingPanel";

const props = defineProps<FloatingPanelConfiguration>();
const panel = ref<HTMLDivElement | null>(null);
const panelProperties = reactive({
    panelX: panel.value?.offsetLeft ?? 0,
    panelY: panel.value?.offsetTop ?? 0,
    clientX: 0,
    clientY: 0,
    dragging: false
});
const panelStyles = reactive<CSSProperties>({});

const changePosition = ({ clientX, clientY }: MouseEvent) => {
    if (!panelProperties.dragging || !props.isOpen) return;
    panelStyles.left = panelProperties.panelX + clientX - panelProperties.clientX + "px";
    panelStyles.top = panelProperties.panelY + clientY - panelProperties.clientY + "px";
};

const onMouseDown = ({ clientX, clientY }: MouseEvent) => {
    if (!panel.value || !props.isOpen) return;
    panelProperties.panelX = panel.value.offsetLeft;
    panelProperties.panelY = panel.value.offsetTop;
    panelProperties.clientX = clientX;
    panelProperties.clientY = clientY;
    panelProperties.dragging = true;
};

const onMouseUp = () => {
    panelProperties.dragging = false;
};

onMounted(() => {
    window.addEventListener("mouseup", onMouseUp, false);
    document.addEventListener("mousedown", onMouseDown);
});

onUnmounted(() => {
    window.removeEventListener("mouseup", onMouseUp, false);
    document.removeEventListener("mousedown", onMouseDown);
});
</script>
