// src/modules/vue-components/magnifier/Magnifier.vue
<template>
  <div class="magnifier">
    <div class="magnifier__image" @mousemove="onMouseMove" ref="image">
      <slot name="image"></slot>
    </div>
    <slot name="glass"></slot>
  </div>
</template>

<script setup lang="ts">
import { useInjectedLinkedItems } from "src/modules/interfaces/generic/hooks/useLinkedItem.vue";
import { onMounted, ref } from "vue";

interface MagnifierConfiguration {
  imageSource: string;
  zoomScale?: number;
}

const props = withDefaults(defineProps<MagnifierConfiguration>(), {
  zoomScale: 2
});
const elements = useInjectedLinkedItems();
const image = ref<HTMLElement | null>(null);

const moveMagnifier = (x: number, y: number) => {
  if (!image.value) return;
  const glass = elements["magnifier-glass"];
  const width = glass.element.offsetWidth / 2,
    height = glass.element.offsetHeight / 2;
  if (x > image.value.offsetWidth) {
    x = image.value.offsetWidth;
  } else if (x < 0) x = 0;
  if (y > image.value.offsetHeight) {
    y = image.value.offsetHeight;
  } else if (y < 0) y = 0;

  glass.styles = {
    ...glass.styles,
    left: `${x - width}px`,
    top: `${y - height}px`,
    backgroundPosition: "-" + (x * props.zoomScale - width) + "px -" + (y * props.zoomScale - height) + "px"
  };
};

const onMouseMove = (event: MouseEvent) => {
  if (!image.value) return;
  event.preventDefault();
  const rect = image.value.getBoundingClientRect();
  moveMagnifier(event.pageX - rect.left - window.scrollX, event.pageY - rect.top - window.scrollY);
};

onMounted(() => {
  if (!image.value) return;
  const glass = elements["magnifier-glass"];
  glass.styles = {
    backgroundImage: `url("${props.imageSource}")`,
    backgroundSize: `${image.value.offsetWidth * props.zoomScale}px ${image.value.offsetHeight * props.zoomScale}px`
  };
});

defineExpose({ onMouseMove });
</script>

<style scoped>
.magnifier {
  position: relative;
}

.magnifier__image {
  width: 100%;
  height: 100%;
}

.magnifier__glass {
  position: absolute;
  top: -25px;
  left: -25px;
  width: 70px;
  height: 70px;
  border: 2px solid #222;
  border-radius: 50%;
  cursor: zoom-in;
  background-repeat: no-repeat;
}
</style>

// src/modules/web-components/magnifier/magnifier.ts
import { LitElement, html } from "lit";
import { customElement, property, queryAssignedElements } from "lit/decorators.js";
import { assertNonUndefined } from "../../utils";

declare global {
	interface HTMLElementTagNameMap {
		"image-magnifier-component": ImageMagnifierComponent;
	}
}

@customElement("image-magnifier-component")
export class ImageMagnifierComponent extends LitElement {
	@property({ type: Number })
	zoomScale = 2;
	@property({ type: Boolean })
	autoConfigureGlassSource = false;

	@queryAssignedElements({ flatten: true })
	_image!: HTMLElement[];
	@queryAssignedElements({ selector: "[data-magnifier-glass]" })
	_glass!: HTMLElement[];

  protected cachedGlass!: HTMLElement;
  protected cachedImage!: HTMLElement;
	private moveListener?: (event: MouseEvent) => void;

  protected moveMagnifier(x: number, y: number) {
    const image = this.cachedImage, glass = this.cachedGlass;
    const width = glass.offsetWidth / 2, height = glass.offsetHeight / 2;
    if (x > image.offsetWidth) {
      x = image.offsetWidth;
    } else if (x < 0) x = 0;
    if (y > image.offsetHeight) {
      y = image.offsetHeight;
    } else if (y < 0) y = 0;

    glass.style.left = `${x - width}px`;
    glass.style.top = `${y - height}px`;
    glass.style.backgroundPosition = "-" + (x * this.zoomScale - width) + "px -" + (y * this.zoomScale - height) + "px";
  }

	protected firstUpdated(): void {
		const image = this._image[0].querySelector<HTMLElement>("[data-magnifier-content]"), [glass] = this._glass;
    assertNonUndefined(image);
		if (this.autoConfigureGlassSource && image.hasAttribute("src")) {
			glass.style.backgroundImage = `url("${image.getAttribute("src") ?? ""}")`;
		}
		glass.style.backgroundSize = `${image.offsetWidth * this.zoomScale}px ${image.offsetHeight * this.zoomScale}px`;
    this.cachedImage = image, this.cachedGlass = glass;

    this.moveListener = (event) => {
      event.preventDefault();
      const rect = image.getBoundingClientRect();
      this.moveMagnifier(event.pageX - rect.left - window.scrollX, event.pageY - rect.top - window.scrollY);
    };
    image.addEventListener("mousemove", this.moveListener);
    glass.addEventListener("mousemove", this.moveListener);
    image.addEventListener("pointermove", this.moveListener);
    image.addEventListener("pointermove", this.moveListener);
	}

	render() {
		return html`<slot></slot>`;
	}
}
