// react/src/components/rebuilding-text/RebuildingText.tsx
import React, { useCallback } from "react";
import { ModifyingTextConfiguration, TriggerTextAnimationCallback } from "shared/interfaces/selfModifyingText";
import { ModifyingTextContext, useSelfModifyingText } from "../../interfaces/hooks/useSelfModifyingText";
import { createRebuildingTextSteps } from "shared/component/rebuildingText";
import { GenericReactComponentProps } from "../../interfaces/generic/classNameFallthrough";

export const RebuildingText = ({
	repetitions = 1,
	interval = 2500,
	typingSpeed = 75,
	...props
}: ModifyingTextConfiguration & GenericReactComponentProps) => {
	const triggerTextAnimation = useCallback<TriggerTextAnimationCallback<ModifyingTextContext>>(
		({ context, fromText, toText }) => {
			const steps = createRebuildingTextSteps(fromText, toText);
			for (let i = 0; i < steps.length; i++) {
				setTimeout(() => {
					context.setCurrentTextValue(
						steps[i]
							.filter<string>((s): s is string => Boolean(s))
							.map((letter) => ({
								letter,
								classes: []
							}))
					);

					if (i === steps.length - 1) {
						setTimeout(() => {
							context.onInterval();
						}, interval);
					}
				}, typingSpeed * i);
			}
		},
		[interval, typingSpeed]
	);

	const currentTextValue = useSelfModifyingText({
		strings: props.strings,
		repetitions,
		interval,
		typingSpeed,
		triggerTextAnimation
	});

	return (
		<pre className={props.className}>
			{currentTextValue.map((letter, i) => (
				<span className={letter.classes.join("")} key={`${letter.letter}-${i}`}>
					{letter.letter}
				</span>
			))}
		</pre>
	);
};

// vue/src/components/rebuilding-text/RebuildingText.vue
<template>
  <pre>
        <span
			v-for="letter, i in settings.currentTextValue.value"
			:key="i"
			:class="letter.classes.join('')"
			v-text="letter.letter"
			/>
    </pre>
</template>

<script setup lang="ts">
import { createRebuildingTextSteps } from "shared/component/rebuildingText";
import { ModifyingTextConfiguration, TriggerTextAnimationCallback } from "shared/interfaces/selfModifyingText";
import { ModifyingTextContext, useSelfModifyingText } from "../../interfaces/hooks/useSelfModifyingText";

const props = withDefaults(defineProps<ModifyingTextConfiguration>(), {
	repetitions: 1,
	interval: 2500,
	typingSpeed: 75
});

const triggerTextAnimation: TriggerTextAnimationCallback<ModifyingTextContext> = ({ context, fromText, toText }) => {
	const steps = createRebuildingTextSteps(fromText, toText);
	for (let i = 0; i < steps.length; i++) {
		setTimeout(() => {
			context.currentTextValue.value = steps[i]
				.filter<string>((s): s is string => Boolean(s))
				.map((letter) => ({
					letter,
					classes: []
				}));

			if (i === steps.length - 1) {
				setTimeout(() => {
					context.onInterval();
				}, props.interval);
			}
		}, props.typingSpeed * i);
	}
};

const settings = useSelfModifyingText({
	strings: props.strings,
	repetitions: props.repetitions,
	interval: props.interval,
	typingSpeed: props.typingSpeed,
	triggerTextAnimation
});
</script>
