// vue/src/components/magnifier/MagnifierComponent.vue
<template>
  <div class="magnifier">
    <div
      ref="image"
      class="magnifier__image"
      @mousemove="onMouseMove"
    >
      <slot name="image" />
    </div>
    <slot name="glass" />
  </div>
</template>

<script setup lang="ts">
import { useInjectedLinkedItems } from "../../interfaces/hooks/useLinkedItem";
import { onMounted, ref } from "vue";
import { MagnifierConfiguration } from "shared/component/magnifier";

const props = withDefaults(defineProps<MagnifierConfiguration>(), {
  zoomScale: 2
});
const elements = useInjectedLinkedItems();
const image = ref<HTMLElement | null>(null);

const moveMagnifier = (x: number, y: number) => {
  if (!image.value) return;
  const glass = elements["magnifier-glass"];
  const width = glass.element.offsetWidth / 2,
    height = glass.element.offsetHeight / 2;
  if (x > image.value.offsetWidth) {
    x = image.value.offsetWidth;
  } else if (x < 0) x = 0;
  if (y > image.value.offsetHeight) {
    y = image.value.offsetHeight;
  } else if (y < 0) y = 0;

  glass.styles = {
    ...glass.styles,
    left: `${String(x - width)}px`,
    top: `${String(y - height)}px`,
    backgroundPosition: "-" + String(x * props.zoomScale - width) + "px -" + String(y * props.zoomScale - height) + "px"
  };
};

const onMouseMove = (event: MouseEvent) => {
  if (!image.value) return;
  event.preventDefault();
  const rect = image.value.getBoundingClientRect();
  moveMagnifier(event.pageX - rect.left - window.scrollX, event.pageY - rect.top - window.scrollY);
};

onMounted(() => {
  if (!image.value) return;
  const glass = elements["magnifier-glass"];
  glass.styles = {
    backgroundImage: `url("${props.imageSource}")`,
    backgroundSize: `${String(image.value.offsetWidth * props.zoomScale)}px ${String(image.value.offsetHeight * props.zoomScale)}px`
  };
});

defineExpose({ onMouseMove });
</script>

<style scoped>
.magnifier {
  position: relative;
}

.magnifier__image {
  width: 100%;
  height: 100%;
}

.magnifier__glass {
  position: absolute;
  top: -25px;
  left: -25px;
  width: 70px;
  height: 70px;
  border: 2px solid #222;
  border-radius: 50%;
  cursor: zoom-in;
  background-repeat: no-repeat;
}
</style>

// lit/src/components/magnifier/magnifier.ts
import { LitElement, css, html } from "lit";
import { property } from "lit/decorators.js";
import { Ref, createRef, ref } from "lit/directives/ref.js";
import { assertNonUndefined } from "shared/utils/utils";
import { MagnifierConfiguration } from "shared/component/magnifier";
import { LinkedCarouselMixin } from "../../interfaces/hooks/linkedItems";
import { ImageMagnifierGlass } from "./magnifierGlass";

export class ImageMagnifierComponent extends LinkedCarouselMixin(LitElement) implements MagnifierConfiguration {
	static styles = css`
		:host {
			position: relative;
			display: block;
		}
	`;

	@property({ type: Number })
	zoomScale = 2;
	@property({ type: Boolean })
	autoConfigureGlassSource = false;
	@property({ type: String })
	imageSource = "";

	protected _magnifierRef: Ref<HTMLDivElement> = createRef();
	protected get magnifierImage() {
		const image = this._magnifierRef.value;
		assertNonUndefined(image);
		return image;
	}

	moveMagnifier(x: number, y: number) {
		const image = this.magnifierImage,
			glass = this.linkedItemsContext["magnifier-glass"];

		const width = glass.element.offsetWidth / 2,
			height = glass.element.offsetHeight / 2;
		if (x > image.offsetWidth) {
			x = image.offsetWidth;
		} else if (x < 0) x = 0;
		if (y > image.offsetHeight) {
			y = image.offsetHeight;
		} else if (y < 0) y = 0;

		glass.styles = {
			...glass.styles,
			left: `${x - width}px`,
			top: `${y - height}px`,
			backgroundPosition: "-" + (x * this.zoomScale - width) + "px -" + (y * this.zoomScale - height) + "px"
		};
		this.linkedItemsContext = { ...this.linkedItemsContext };
	}

	protected onMouseMove(event: MouseEvent) {
		event.preventDefault();
		const rect = this.magnifierImage.getBoundingClientRect();
		this.moveMagnifier(event.pageX - rect.left - window.scrollX, event.pageY - rect.top - window.scrollY);
	}

	private mouseMoveListener?: (event: MouseEvent) => void;
	protected firstUpdated(): void {
		const glass = this.linkedItemsContext["magnifier-glass"];

		glass.element.addEventListener(
			"mousemove",
			(this.mouseMoveListener ??= (e) => {
				this.onMouseMove(e);
			})
		);
		glass.element.addEventListener("pointermove", this.mouseMoveListener);

		glass.styles = {
			backgroundImage: `url("${this.imageSource}")`,
			backgroundSize: `${this.magnifierImage.offsetWidth * this.zoomScale}px ${this.magnifierImage.offsetHeight * this.zoomScale}px`
		};
		this.linkedItemsContext = { ...this.linkedItemsContext };
	}

	render() {
		return html`<div class="magnifier">
			<div
				class="magnifier__image"
				@mousemove=${(event: MouseEvent) => {
					this.onMouseMove(event);
				}}
				${ref(this._magnifierRef)}
			>
				<slot name="image"></slot>
			</div>
			<slot name="glass"></slot>
		</div>`;
	}
}

export { ImageMagnifierGlass };
