// react/src/components/ciphering-text/CipheringText.tsx
import React, { useCallback, useRef } from "react";
import { ModifyingTextContext, useSelfModifyingText } from "../../interfaces/hooks/useSelfModifyingText";
import { SplitTextCallback, TriggerTextAnimationCallback, splitTextAlgorithm } from "shared/interfaces/selfModifyingText";
import { CipheringTextConfiguration } from "shared/component/cipheringText";

const defaultCharacters = [
	"!",
	'"',
	"#",
	"$",
	"%",
	"*",
	"0",
	"1",
	":",
	";",
	"?",
	"@",
	"[",
	"]",
	"\\",
	"~",
	"'",
	"/",
	"{",
	"}",
	"|",
	"&",
	"(",
	")",
	"-",
	"<",
	">"
];

export const CipheringText = ({
	characters = defaultCharacters,
	repetitions = 1,
	interval = 3000,
	typingSpeed = 45,
	...props
}: CipheringTextConfiguration) => {
	const element = useRef<HTMLPreElement | null>(null);

	const cipherLetter = useCallback(
		async (context: ModifyingTextContext, properties: { newLetter?: string; delayed: boolean; i: number }) => {
			const { newLetter, delayed, i } = properties;
			const changeNumber = Math.round(Math.random() * ((delayed ? 44 : 14) - 6) + 6);
			let isDone = false;
			const definedRandom = Math.random() * 1000 + (delayed ? typingSpeed * i : 0),
				speed = typingSpeed;

			await new Promise((resolve) => {
				setTimeout(resolve, definedRandom);
			});

			for (let index = 0; index <= changeNumber; index++) {
				await new Promise((resolve) => {
					setTimeout(resolve, speed);
				});

				let newValue: string | undefined;
				if (!isDone) newValue = characters[Math.floor(Math.random() * characters.length)];
				if (index >= changeNumber) {
					isDone = true;
					newValue = newLetter ?? "";
				}

				context.setCurrentTextValue((current) => {
					const newCurrentText = [...current];
					if (newValue !== undefined) {
						newCurrentText[i] = {
							letter: newValue,
							classes: isDone ? [] : ["active"]
						};
					}

					return newCurrentText;
				});
			}
		},
		[characters, typingSpeed]
	);

	const splitText = useCallback<SplitTextCallback<ModifyingTextContext>>(({ context, toText, fromText }) => {
		if (toText && fromText) {
			context.setCurrentTextValue(
				splitTextAlgorithm(
					fromText.split("").map((letter) => ({ letter, classes: [] })),
					toText
				)
			);
		}
	}, []);

	const triggerTextAnimation = useCallback<TriggerTextAnimationCallback<ModifyingTextContext>>(
		async ({ context, fromText, toText }) => {
			void splitText({ context, toText, fromText });
			const promises = splitTextAlgorithm(
				fromText.split("").map((letter) => ({ letter, classes: [] })),
				toText
			)
				.map((character, i) => {
					if (character.letter === toText[i]) return;
					return cipherLetter(context, { newLetter: toText[i], i, delayed: element.current?.textContent?.length === 0 });
				})
				.filter(Boolean);
			await Promise.all(promises);

			context.setCurrentTextValue(toText.split("").map((letter) => ({ letter, classes: [] })));
			await new Promise((resolve) => {
				setTimeout(resolve, interval);
			});

			context.onInterval();
		},
		[cipherLetter, interval, splitText]
	);

	const currentTextValue = useSelfModifyingText({
		strings: props.strings,
		repetitions,
		interval,
		typingSpeed,
		splitText,
		triggerTextAnimation
	});

	return (
		<pre ref={element}>
			{currentTextValue.map((letter, i) => (
				<span className={letter.classes.join("")} key={`${letter.letter}-${i}`}>
					{letter.letter}
				</span>
			))}
		</pre>
	);
};

// vue/src/components/ciphering-text/CipheringText.vue
<template>
  <pre ref="element">
        <span
			v-for="letter, i in settings.currentTextValue.value"
			:key="i"
			:class="letter.classes.join('')"
			v-text="letter.letter"
		/>
    </pre>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { useSelfModifyingText, splitTextAlgorithm, ModifyingTextContext } from "../../interfaces/hooks/useSelfModifyingText";
import { CipheringTextConfiguration } from "shared/component/cipheringText";
import { SplitTextCallback, TriggerTextAnimationCallback } from "shared/interfaces/selfModifyingText";

const props = withDefaults(defineProps<CipheringTextConfiguration>(), {
	characters: () => [
		"!",
		'"',
		"#",
		"$",
		"%",
		"*",
		"0",
		"1",
		":",
		";",
		"?",
		"@",
		"[",
		"]",
		"\\",
		"~",
		"'",
		"/",
		"{",
		"}",
		"|",
		"&",
		"(",
		")",
		"-",
		"<",
		">"
	],
	repetitions: 1,
	interval: 3000,
	typingSpeed: 45
});
const element = ref<HTMLElement | null>(null);

const cipherLetter = (context: ModifyingTextContext, properties: { newLetter?: string; delayed: boolean; i: number }) => {
	const { newLetter, delayed, i } = properties;
	const changeNumber = Math.round(Math.random() * ((delayed ? 44 : 14) - 6) + 6);
	let isDone = false,
		index = 0;
	const definedRandom = Math.random() * 1000 + (delayed ? props.typingSpeed * i : 0),
		speed = props.typingSpeed;
	setTimeout(() => {
		while (index <= changeNumber) {
			(function (index) {
				setTimeout(() => {
					let newValue: string | undefined;
					if (!isDone) newValue = props.characters[Math.floor(Math.random() * props.characters.length)];
					if (index >= changeNumber) {
						isDone = true;
						newValue = newLetter ?? "";
					}

					if (newValue !== undefined) {
						context.currentTextValue.value[i] = {
							letter: newValue,
							classes: isDone ? [] : ["active"]
						};
					}
				}, speed * index);
			})(index++);
		}
	}, definedRandom);

	return changeNumber * speed + speed;
};

const splitText: SplitTextCallback<ModifyingTextContext> = ({ context, toText }) => {
	if (toText) context.currentTextValue.value = splitTextAlgorithm(context.currentTextValue.value, toText);
};

const triggerTextAnimation: TriggerTextAnimationCallback<ModifyingTextContext> = ({ context, toText }) => {
	void splitText({ context, toText });
	const speeds: number[] = [];
	context.currentTextValue.value.forEach((character, i) => {
		if (character.letter === toText[i]) return;
		speeds.push(cipherLetter(context, { newLetter: toText[i], i, delayed: element.value?.textContent?.length === 0 }));
	});

	setTimeout(() => {
		context.currentTextValue.value = context.currentTextValue.value.filter((v) => Boolean(v.letter));
		context.onInterval();
	}, Math.max(...speeds) + props.interval);
};

const settings = useSelfModifyingText({
	strings: props.strings,
	repetitions: props.repetitions,
	interval: props.interval,
	typingSpeed: props.typingSpeed,
	triggerTextAnimation,
	splitText
});
</script>

<style scoped>
pre {
	white-space: normal;
}
</style>
