// lit/src/components/magnifier/magnifierGlass.ts
import { LitElement, css, html } from "lit";
import { styleMap } from "lit/directives/style-map.js";
import { LinkedItemMixin } from "../../interfaces/hooks/linkedItems";

export class ImageMagnifierGlass extends LinkedItemMixin(LitElement) {
	static styles = [
		css`
			:host {
				display: contents;
			}

			.magnifier-glass {
				position: absolute;
				border-radius: 50%;
				background-repeat: no-repeat;
			}
		`
	];

	protected getUid() {
		return "magnifier-glass";
	}

	render() {
		return html`<div class="magnifier-glass" style=${styleMap(this.linkedItemStyles)}>
			<slot></slot>
		</div>`;
	}
}

// vue/src/components/magnifier/MagnifierGlass.vue
<template>
  <div
    ref="glass"
    class="magnifier-glass"
    @pointermove="(e) => emit('glassMove', e)"
    @mousemove="(e) => emit('glassMove', e)"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { useLinkedItem } from '../../interfaces/hooks/useLinkedItem';
import { ref } from 'vue';

const emit = defineEmits<{
    (e: 'glassMove', event: MouseEvent): void;
}>();
const glass = ref<HTMLElement | null>(null);
useLinkedItem(() => "magnifier-glass", glass);
</script>

<style scoped>
.magnifier-glass {
    position: absolute;
    border-radius: 50%;
    background-repeat: no-repeat;
}
</style>
