// lit/src/components/zooming-image/zoomingImage.ts
import { LitElement, css, html } from "lit";
import { property } from "lit/decorators.js";
import { LinkedCarouselMixin } from "../../interfaces/hooks/linkedItems";
import { ZoomingImageConfiguration } from "shared/component/zoomingImage";
import { ZoomingImageGlass } from "./zoomingImageGlass";

export class ZoomingImage extends LinkedCarouselMixin(LitElement) implements ZoomingImageConfiguration {
	static styles = css`
		:host {
			position: relative;
			display: block;
		}
	`;

	@property({ type: Number })
	moveRatio = 0.15;
	@property({ type: Number })
	backgroundShift = 9;
	@property({ type: Number })
	positionShift = 34;

	private mouseMoveListener?: (event: MouseEvent) => void;

	onMouseMove(event: MouseEvent) {
		const { top, left } = this.getBoundingClientRect();
		const x = event.x - left,
			y = event.pageY - top;
		const { offsetWidth, offsetHeight } = this;
		let xMove = (x / offsetWidth) * 100,
			yMove = (y / offsetHeight) * 100;
		if (x >= 0.01 * offsetWidth) xMove += this.moveRatio * xMove;
		if (y >= 0.01 * offsetHeight) yMove += this.moveRatio * yMove;

		this.linkedItemsContext["zooming-image-glass"].styles = {
			backgroundPositionX: `${String(xMove - this.backgroundShift)}%`,
			backgroundPositionY: `${String(yMove - this.backgroundShift)}%`,
			left: `${String(x - this.positionShift)}px`,
			top: `${String(y - this.positionShift)}px`
		};
	}

	connectedCallback(): void {
		super.connectedCallback();
		this.addEventListener("mousemove", (this.mouseMoveListener ??= this.onMouseMove.bind(this)));
		this.addEventListener("pointermove", this.mouseMoveListener);
	}

	disconnectedCallback(): void {
		super.disconnectedCallback();
		if (this.mouseMoveListener) {
			this.removeEventListener("mousemove", this.mouseMoveListener);
			this.removeEventListener("pointermove", this.mouseMoveListener);
		}
	}

	render() {
		return html`
			<slot name="image"></slot>
			<slot name="glass"></slot>
		`;
	}
}

export { ZoomingImageGlass };

// vue/src/components/zooming-image/ZoomingImage.vue
<template>
  <div
    ref="wrap"
    class="wrap"
    @mousemove="onMouseMove"
    @pointermove="onMouseMove"
  >
    <slot name="image" />
    <slot name="glass" />
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { ZoomingImageConfiguration } from "shared/component/zoomingImage";
import { useInjectedLinkedItems } from "../../interfaces/hooks/useLinkedItem";

const props = withDefaults(defineProps<Partial<ZoomingImageConfiguration>>(), {
	moveRatio: 0.15,
	backgroundShift: 9,
	positionShift: 34
});
const elements = useInjectedLinkedItems();
const glass = computed(() => elements["zooming-image-glass"]);
const wrap = ref<HTMLElement | null>(null);

const onMouseMove = (event: MouseEvent) => {
	if (!wrap.value) return;
	const { top, left } = wrap.value.getBoundingClientRect();
	const x = event.x - left,
		y = event.pageY - top;
	const { offsetWidth, offsetHeight } = wrap.value;
	let xMove = (x / offsetWidth) * 100,
		yMove = (y / offsetHeight) * 100;
	if (x >= 0.01 * offsetWidth) xMove += props.moveRatio * xMove;
	if (y >= 0.01 * offsetHeight) yMove += props.moveRatio * yMove;

	glass.value.styles = {
		backgroundPositionX: `${String(xMove - props.backgroundShift)}%`,
		backgroundPositionY: `${String(yMove - props.backgroundShift)}%`,
		left: `${String(x - props.positionShift)}px`,
		top: `${String(y - props.positionShift)}px`
	};
};

defineExpose({ onMouseMove });
</script>

<style scoped>
.wrap {
	position: relative;
}
</style>
