// vue/src/components/sticky-header/StickyHeaderElement.vue
<template>
    <div ref="header">
        <slot></slot>
    </div>
</template>

<script setup lang="ts">
import { useLinkedItem } from '../../interfaces/hooks/useLinkedItem';
import { ref } from 'vue';

const header = ref<HTMLElement | null>(null);
useLinkedItem(() => "sticky-header", header);
</script>

// react/src/components/sticky-header/StickyHeaderElement.tsx
import React, { useRef } from "react";
import { useLinkedItem } from "../../interfaces/hooks/useLinkedItem";
import { GenericReactComponentProps } from "../../interfaces/generic/classNameFallthrough";
import { WithChildren } from "react/src/utils/utils";

export const StickyHeaderElement = (props: WithChildren<object> & GenericReactComponentProps) => {
	const item = useRef<HTMLDivElement>(null);
	const styleObject = useLinkedItem(() => "sticky-header", item);

	return (
		<div ref={item} style={styleObject} className={props.className}>
			{props.children}
		</div>
	);
};
