// vue/src/components/parallax/Parallax.vue
<template>
  <div
    ref="wrap"
    class="wrap"
    :style="styles"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ParallaxConfiguration } from "shared/component/parallax";
import { getFirstScrollableParent } from "shared/utils/domUtils";
import { ref, onMounted, onUnmounted, reactive, CSSProperties } from "vue";

const wrap = ref<HTMLElement | null>(null);
const styles = reactive<CSSProperties>({});
const props = withDefaults(defineProps<Partial<ParallaxConfiguration>>(), {
	isHorizontal: false,
	isHorizontalTranslation: false,
	effect: 1.968,
	speed: 2.7,
	margin: 0
});

const scrollListener = ref<EventListener | undefined>();

const rerender = () => {
	if (!wrap.value) return;
	const parent = getFirstScrollableParent(wrap.value, props.isHorizontal);
	if (scrollListener.value) parent.removeEventListener("scroll", scrollListener.value);
	const getScrollPoint = (parent: HTMLElement | Window) => {
		if (parent instanceof HTMLElement) {
			return props.isHorizontal ? parent.scrollLeft : parent.scrollTop;
		} else return props.isHorizontal ? parent.scrollX : parent.scrollY;
	};

	const animationOffset = wrap.value.getBoundingClientRect()[props.isHorizontal ? "left" : "top"] + getScrollPoint(parent);
	const innerHeight =
		(parent instanceof HTMLElement
			? props.isHorizontal
				? parent.clientWidth
				: parent.clientHeight
			: props.isHorizontal
			? parent.innerWidth
			: parent.innerHeight) / props.effect;

	const scrollEventListener = () => {
        if (!wrap.value) return;
		const scrollPoint = getScrollPoint(getFirstScrollableParent(wrap.value, props.isHorizontal));
		if (scrollPoint > animationOffset - innerHeight * 2 && scrollPoint < animationOffset + innerHeight) {
			const point = (scrollPoint - (animationOffset - innerHeight)) / props.speed - props.margin;
			styles.transform = `translate${props.isHorizontalTranslation ? "X" : "Y"}(${point}px)`;
		}
	};

	scrollListener.value = scrollEventListener;
	parent.addEventListener("scroll", scrollEventListener, { passive: true });
	scrollEventListener();
};

onMounted(() => {
	rerender();
	window.addEventListener("resize", rerender);
});

onUnmounted(() => {
	window.removeEventListener("resize", rerender);
});
</script>

<style scoped>
.wrap {
	position: relative;
	transition: 0.1s;
}
</style>

// react/src/components/parallax/Parallax.tsx
import React, { CSSProperties, useCallback, useEffect, useRef, useState } from "react";
import { ParallaxConfiguration } from "../../interfaces/component/parallax";
import { getFirstScrollableParent } from "shared/utils/domUtils";
import cssStyles from "./Parallax.module.css";

export const Parallax = ({
	isHorizontal = false,
	isHorizontalTranslation = false,
	effect = 1.968,
	speed = 2.7,
	margin = 0,
	...props
}: Partial<ParallaxConfiguration>) => {
	const wrap = useRef<HTMLDivElement>(null);
	const scrollListener = useRef<EventListener | undefined>();
	const [styles, setStyles] = useState<CSSProperties>({});

	const rerender = useCallback(() => {
		if (!wrap.current) return;
		const parent = getFirstScrollableParent(wrap.current, isHorizontal);
		if (scrollListener.current) parent.removeEventListener("scroll", scrollListener.current);
		const getScrollPoint = (parent: HTMLElement | Window) => {
			if (parent instanceof HTMLElement) {
				return isHorizontal ? parent.scrollLeft : parent.scrollTop;
			} else return isHorizontal ? parent.scrollX : parent.scrollY;
		};

		const animationOffset = wrap.current.getBoundingClientRect()[isHorizontal ? "left" : "top"] + getScrollPoint(parent);
		const innerHeight =
			(parent instanceof HTMLElement
				? isHorizontal
					? parent.clientWidth
					: parent.clientHeight
				: isHorizontal
				? parent.innerWidth
				: parent.innerHeight) / effect;

		const scrollEventListener = () => {
			if (!wrap.current) return;
			const scrollPoint = getScrollPoint(getFirstScrollableParent(wrap.current, isHorizontal));
			if (scrollPoint > animationOffset - innerHeight * 2 && scrollPoint < animationOffset + innerHeight) {
				const point = (scrollPoint - (animationOffset - innerHeight)) / speed - margin;
				setStyles({ transform: `translate${isHorizontalTranslation ? "X" : "Y"}(${point}px)` });
			}
		};

		scrollListener.current = scrollEventListener;
		parent.addEventListener("scroll", scrollEventListener, { passive: true });
		scrollEventListener();
	}, [effect, isHorizontal, isHorizontalTranslation, margin, speed]);

	useEffect(() => {
		rerender();
		window.addEventListener("resize", rerender);

		return () => {
			window.removeEventListener("resize", rerender);
		};
	}, [rerender]);

	return (
		<div className={`${cssStyles.wrap} ${props.className ?? ""}`} ref={wrap} style={styles}>
			{props.children}
		</div>
	);
};
