// vue/src/components/toast/ToastComponent.vue
<template>
  <Teleport to="body">
    <Transition :name="transitionName">
      <slot v-if="isOpen" />
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from "vue";
import { ToastVueConfiguration } from "../../interfaces/component/toast";

const props = defineProps<ToastVueConfiguration>();
const timeout = ref<number | undefined>();
const isToastOpen = ref(props.isOpen);

const close = () => {
    isToastOpen.value = false;
    window.clearTimeout(timeout.value);
    timeout.value = undefined;
};

watch(
    () => props.isOpen,
    (_, newValue) => {
        isToastOpen.value = newValue;
        if (!props.autoCloseDelay || !newValue) return;
        timeout.value = window.setTimeout(() => {
            close();
        }, props.autoCloseDelay);
    }
);

onMounted(() => {
    if (isToastOpen.value) {
        timeout.value = window.setTimeout(() => {
            close();
        }, props.autoCloseDelay);
    }
});

onUnmounted(() => {
    window.clearTimeout(timeout.value);
});
</script>

// react/src/components/toast/Toast.tsx
import React, { useEffect, useRef } from "react";
import { ToastConfiguration } from "../../interfaces/component/toast";
import { createPortal } from "react-dom";
import { CSSTransition } from "react-transition-group";

export const Toast = ({ isOpen, autoCloseDelay, closeToast, ...props }: ToastConfiguration) => {
	const timeout = useRef<number>();

	useEffect(() => {
		if (!autoCloseDelay || !isOpen) return;
		timeout.current = window.setTimeout(() => {
			closeToast?.();
			timeout.current = undefined;
		}, autoCloseDelay);

		return () => {
			window.clearTimeout(timeout.current);
		};
	}, [autoCloseDelay, closeToast, isOpen]);

	return createPortal(
		<CSSTransition timeout={props.animationDuration} in={isOpen} unmountOnExit classNames={props.classes}>
			{props.children}
		</CSSTransition>,
		document.body
	);
};
